import { experimental_createToolkit, experimental_createTool } from '@composio/core';
import { z } from 'zod/v3';
import { WuzzufOrchestratorClient, type WuzzufOrchestratorClientOptions } from './orchestrator-client.ts';

const errorSchema = z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string(), retryable: z.boolean(), correlationId: z.string(), actionRequired: z.string().optional(), diagnostics: z.record(z.unknown()).optional() }).strict() }).strict();
const jobSchema = z.object({ id: z.string(), fingerprint: z.string(), source: z.literal('wuzzuf'), sourceId: z.string(), url: z.string().url(), title: z.string(), employer: z.string(), location: z.string(), description: z.string(), requiredSkills: z.array(z.string()).optional(), preferredSkills: z.array(z.string()).optional(), remote: z.boolean().optional(), seniority: z.string().optional(), salary: z.string().optional(), requirements: z.array(z.string()).optional(), responsibilities: z.array(z.string()).optional(), experienceLevel: z.string().optional(), employmentType: z.string().optional(), applicationAvailable: z.boolean().optional(), discoveredAt: z.string().optional(), matchScore: z.number(), scoreExplanation: z.array(z.object({ factor: z.string(), points: z.number(), reason: z.string() }).strict()) }).strict();
const success = <T extends z.ZodTypeAny>(data: T) => z.object({ ok: z.literal(true), data }).strict();
const response = <T extends z.ZodTypeAny>(data: T) => z.union([success(data), errorSchema]);
const jobRef = { jobId: z.string().optional(), url: z.string().url().optional(), profileId: z.string().optional() };
const answerSchema = z.object({ fieldId: z.string(), label: z.string(), value: z.string(), confidence: z.number(), supportingFactIds: z.array(z.string()), confirmationRequired: z.boolean(), reason: z.string().optional(), generatedAt: z.string(), model: z.string() }).strict();
const reviewSchema = z.object({ id: z.string(), correlationId: z.string(), jobId: z.string(), job: jobSchema, profileId: z.string(), selectedResume: z.object({ id: z.string(), name: z.string(), sourceName: z.string(), approved: z.boolean() }).strict().optional(), answers: z.array(answerSchema), filledFields: z.array(z.string()), skippedFields: z.array(z.string()), validationErrors: z.array(z.string()), sensitiveFields: z.array(z.string()), screenshots: z.array(z.string()), state: z.string(), dryRun: z.boolean(), submissionAllowed: z.boolean(), lastSuccessfulStep: z.string(), errors: z.array(z.object({ code: z.string(), message: z.string(), at: z.string() }).strict()), createdAt: z.string(), updatedAt: z.string(), submittedAt: z.string().optional(), submissionResult: z.object({ submitted: z.boolean(), confirmation: z.string().optional(), at: z.string() }).strict().optional(), reviewRevision: z.string().optional(), auditTimeline: z.array(z.object({ id: z.string(), correlationId: z.string(), applicationId: z.string().optional(), type: z.string(), state: z.string().optional(), at: z.string(), detail: z.record(z.unknown()) }).strict()) }).strict();

export function createWuzzufToolkit(options: WuzzufOrchestratorClientOptions = {}) {
  const client = new WuzzufOrchestratorClient(options); const call = (action: string) => (input: Record<string, unknown>) => client.execute(action, input);
  const tools = [
    experimental_createTool('CREATE_CONNECTION', { name: 'WUZZUF_CREATE_CONNECTION', description: 'Open Wuzzuf in the existing local Chrome profile and verify authentication. No credentials or browser data leave the machine.', inputParams: z.object({}).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_CREATE_CONNECTION') }),
    experimental_createTool('OPEN_LOGIN', { name: 'WUZZUF_OPEN_LOGIN', description: 'Open or reuse the application-managed Wuzzuf login tab in existing Chrome for manual login or security verification.', inputParams: z.object({}).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_OPEN_LOGIN') }),
    experimental_createTool('GET_AUTH_STATUS', { name: 'WUZZUF_GET_AUTH_STATUS', description: 'Read cached local Wuzzuf connection state without returning cookies or browser internals.', preload: true, inputParams: z.object({}).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_GET_AUTH_STATUS') }),
    experimental_createTool('VERIFY_CONNECTION', { name: 'WUZZUF_VERIFY_CONNECTION', description: 'Verify the live Wuzzuf authentication and security-check state.', inputParams: z.object({}).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_VERIFY_CONNECTION') }),
    experimental_createTool('DISCONNECT', { name: 'WUZZUF_DISCONNECT', description: 'Logically disconnect local Wuzzuf automation without closing personal Chrome.', inputParams: z.object({}).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_DISCONNECT') }),
    experimental_createTool('SEARCH_JOBS', { name: 'WUZZUF_SEARCH_JOBS', description: 'Search Wuzzuf and return normalized jobs. Safe read-only action.', preload: true, inputParams: z.object({ queries: z.array(z.string()).min(1).max(10), locations: z.array(z.string()).min(1).max(10), remote: z.boolean().optional(), experienceLevel: z.string().optional(), employmentTypes: z.array(z.string()).max(10).optional(), limit: z.number().int().min(1).max(100).optional() }).strict(), outputParams: response(z.object({ correlationId: z.string(), jobs: z.array(jobSchema) }).strict()), execute: call('WUZZUF_SEARCH_JOBS') }),
    experimental_createTool('GET_JOB_DETAILS', { name: 'WUZZUF_GET_JOB_DETAILS', description: 'Read and normalize full details for a supported Wuzzuf job URL. Safe read-only action.', inputParams: z.object({ url: z.string().url() }).strict(), outputParams: response(z.object({ correlationId: z.string(), job: jobSchema }).strict()), execute: call('WUZZUF_GET_JOB_DETAILS') }),
    experimental_createTool('SCORE_JOB', { name: 'WUZZUF_SCORE_JOB', description: 'Score a Wuzzuf job against the verified local candidate profile using the shared profile engine. Provide jobId or url.', preload: true, inputParams: z.object(jobRef).strict(), outputParams: response(z.object({ correlationId: z.string(), jobId: z.string(), score: z.number().min(0).max(100), matchingSkills: z.array(z.string()), missingSkills: z.array(z.string()), explanation: z.array(z.object({ factor: z.string(), points: z.number(), reason: z.string() }).strict()), confidence: z.number().min(0).max(1), recommendation: z.enum(['prepare_application', 'review', 'skip']) }).strict()), execute: call('WUZZUF_SCORE_JOB') }),
    experimental_createTool('PREPARE_APPLICATION', { name: 'WUZZUF_PREPARE_APPLICATION', description: 'Prepare a review-first Wuzzuf application from jobId or url. It inspects the form and proposes grounded answers but never submits.', preload: true, inputParams: z.object({ ...jobRef, dryRun: z.boolean().default(true), idempotencyKey: z.string().max(128).optional() }).strict(), outputParams: response(reviewSchema), execute: call('WUZZUF_PREPARE_APPLICATION') }),
    experimental_createTool('FILL_APPLICATION', { name: 'WUZZUF_FILL_APPLICATION', description: 'Fill only approved high-confidence non-sensitive fields, then stop before submission. Defaults to dry-run.', inputParams: z.object({ applicationId: z.string(), approvedAnswerOverrides: z.array(z.object({ fieldId: z.string().optional(), label: z.string().optional(), value: z.string(), approved: z.literal(true) }).strict()).optional(), dryRun: z.boolean().default(true), idempotencyKey: z.string().max(128).optional() }).strict(), outputParams: response(reviewSchema), execute: call('WUZZUF_FILL_APPLICATION') }),
    experimental_createTool('GET_APPLICATION_REVIEW', { name: 'WUZZUF_GET_APPLICATION_REVIEW', description: 'Get the complete local application review, safety blockers, screenshots, and audit timeline.', preload: true, inputParams: z.object({ applicationId: z.string() }).strict(), outputParams: response(reviewSchema), execute: call('WUZZUF_GET_APPLICATION_REVIEW') }),
    experimental_createTool('REQUEST_SUBMISSION_APPROVAL', { name: 'WUZZUF_REQUEST_SUBMISSION_APPROVAL', description: 'Request short-lived human approval in the paired extension. This operation cannot grant approval or submit.', inputParams: z.object({ applicationId: z.string(), ttlSeconds: z.number().int().min(30).max(300).optional(), idempotencyKey: z.string().max(128).optional() }).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_REQUEST_SUBMISSION_APPROVAL') }),
    experimental_createTool('SUBMIT_APPLICATION', { name: 'WUZZUF_SUBMIT_APPLICATION', description: 'DESTRUCTIVE: submit once using a short-lived one-use token issued by the paired extension. Never retry an uncertain result.', preload: false, inputParams: z.object({ applicationId: z.string(), approvalRequestId: z.string(), approvalToken: z.string().min(32).max(256), idempotencyKey: z.string().max(128).optional() }).strict(), outputParams: response(z.object({ applicationId: z.string(), correlationId: z.string(), submitted: z.boolean(), confirmation: z.string().optional(), submittedAt: z.string() }).strict()), execute: call('WUZZUF_SUBMIT_APPLICATION') }),
    experimental_createTool('GET_APPLICATION_STATUS', { name: 'WUZZUF_GET_APPLICATION_STATUS', description: 'Read the current state, progress, errors, timestamps, and submission result.', preload: true, inputParams: z.object({ applicationId: z.string() }).strict(), outputParams: response(z.object({ applicationId: z.string(), state: z.string(), lastSuccessfulStep: z.string(), errors: z.array(z.object({ code: z.string(), message: z.string(), at: z.string() }).strict()), timestamps: z.object({ createdAt: z.string(), updatedAt: z.string(), submittedAt: z.string().optional() }).strict(), correlationId: z.string(), submissionResult: z.object({ submitted: z.boolean(), confirmation: z.string().optional(), at: z.string() }).strict().optional() }).strict()), execute: call('WUZZUF_GET_APPLICATION_STATUS') }),
    experimental_createTool('CANCEL_APPLICATION', { name: 'WUZZUF_CANCEL_APPLICATION', description: 'Cancel an active Wuzzuf application and close only application-managed browser resources.', inputParams: z.object({ applicationId: z.string(), idempotencyKey: z.string().max(128).optional() }).strict(), outputParams: response(z.record(z.unknown())), execute: call('WUZZUF_CANCEL_APPLICATION') })
  ];
  return experimental_createToolkit('WUZZUF', { name: 'wuzzuf', description: 'Local review-first Wuzzuf search and application automation routed through the authenticated orchestrator.', tools });
}

export { WuzzufOrchestratorClient } from './orchestrator-client.ts';
