export interface WuzzufOrchestratorClientOptions { baseUrl?: string; toolToken?: string; pairingCode?: string; timeoutMs?: number }

export class WuzzufOrchestratorClient {
  private readonly baseUrl: string; private readonly toolToken: string; private readonly timeoutMs: number;
  constructor(options: WuzzufOrchestratorClientOptions = {}) { this.baseUrl = options.baseUrl ?? process.env.WUZZUF_ORCHESTRATOR_URL ?? 'http://127.0.0.1:18790'; this.toolToken = options.toolToken ?? process.env.COMPOSIO_WUZZUF_TOOL_TOKEN ?? ''; this.timeoutMs = options.timeoutMs ?? 60_000; const url = new URL(this.baseUrl); if (url.protocol !== 'http:' || url.hostname !== '127.0.0.1') throw new Error('Wuzzuf orchestrator must be an HTTP loopback URL'); }
  async execute(action: string, input: Record<string, unknown>): Promise<Record<string, unknown>> { try { if (!this.toolToken) throw new Error('COMPOSIO_WUZZUF_TOOL_TOKEN is not configured'); const response = await fetch(`${this.baseUrl}/v1/wuzzuf/tools/${encodeURIComponent(action)}`, { method: 'POST', headers: { 'x-composio-tool-token': this.toolToken, 'content-type': 'application/json' }, body: JSON.stringify(input), signal: AbortSignal.timeout(this.timeoutMs), redirect: 'error' }); const result = await response.json() as unknown; if (!result || typeof result !== 'object' || Array.isArray(result)) return failure('ORCHESTRATOR_UNAVAILABLE', `Orchestrator returned ${response.status}.`, response.status >= 500); return result as Record<string, unknown>; } catch { return failure('ORCHESTRATOR_UNAVAILABLE', 'The local Wuzzuf orchestrator is unavailable. Start it, verify the Composio client credential, and retry.', true); } }
}

function failure(code: string, message: string, retryable: boolean): Record<string, unknown> { return { ok: false, error: { code, message, retryable, correlationId: crypto.randomUUID(), actionRequired: 'Start or restart the local extension-jobs orchestrator and verify COMPOSIO_WUZZUF_TOOL_TOKEN.' } }; }
