import test from 'node:test'; import assert from 'node:assert/strict'; import { once } from 'node:events'; import { mkdtempSync } from 'node:fs'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { Store } from '../apps/orchestrator/src/store.ts'; import { importCvText } from '../packages/profile-engine/src/index.ts'; import { OrchestratorService } from '../apps/orchestrator/src/service.ts'; import { FixtureJobSource } from '../packages/site-adapters/src/index.ts'; import { DevelopmentProvider } from '../packages/provider-sdk/src/index.ts'; import { createBridge } from '../apps/orchestrator/src/server.ts';
test('bridge validates exact origin and pairing before protected access', async (t) => { const store = new Store(join(mkdtempSync(join(tmpdir(), 'bridge-')), 'db.sqlite')); const server = createBridge(new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider()), { allowedOrigin: 'http://127.0.0.1:9999', pairingCode: 'correct' }); server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => { server.close(); store.close(); }); const address = server.address(); if (!address || typeof address === 'string') throw new Error('No address'); const base = `http://127.0.0.1:${address.port}`;
  const denied = await fetch(`${base}/health`, { headers: { origin: 'http://127.0.0.1:8888' } }); assert.equal(denied.status, 403);
  const health = await fetch(`${base}/health`, { headers: { origin: 'http://127.0.0.1:9999' } }); const healthBody = await health.json() as { chrome: { status: string } }; assert.equal(healthBody.chrome.status, 'not_connected');
  const unauth = await fetch(`${base}/v1/dashboard`, { headers: { origin: 'http://127.0.0.1:9999' } }); assert.equal(unauth.status, 401);
  const paired = await fetch(`${base}/v1/pair`, { method: 'POST', headers: { origin: 'http://127.0.0.1:9999', 'content-type': 'application/json' }, body: JSON.stringify({ code: 'correct' }) }); const session = await paired.json() as { token: string }; assert.ok(session.token);
  const dashboard = await fetch(`${base}/v1/dashboard`, { headers: { origin: 'http://127.0.0.1:9999', authorization: `Bearer ${session.token}` } }); assert.equal(dashboard.status, 200);
});
test('OpenClaw tool token is separate from extension pairing and cannot grant approval', async (t) => { const store = new Store(join(mkdtempSync(join(tmpdir(), 'tool-')), 'db.sqlite')); const server = createBridge(new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider()), { allowedOrigin: 'http://127.0.0.1:9999', pairingCode: 'pair', toolToken: 'tool-secret' }); server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => { server.close(); store.close(); }); const address = server.address(); if (!address || typeof address === 'string') throw new Error('No address'); const base = `http://127.0.0.1:${address.port}`; assert.equal((await fetch(`${base}/v1/dashboard`, { headers: { 'x-openclaw-tool-token': 'wrong' } })).status, 401); assert.equal((await fetch(`${base}/v1/dashboard`, { headers: { 'x-openclaw-tool-token': 'tool-secret' } })).status, 200); assert.equal((await fetch(`${base}/v1/wuzzuf/approval-requests/not-found/decision`, { method: 'POST', headers: { 'x-openclaw-tool-token': 'tool-secret', 'content-type': 'application/json' }, body: JSON.stringify({ approved: true }) })).status, 401); });
test('Composio uses a distinct scoped credential and cannot approve or submit by default', async (t) => { const store = new Store(join(mkdtempSync(join(tmpdir(), 'composio-tool-')), 'db.sqlite')); const server = createBridge(new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider()), { allowedOrigin: 'http://127.0.0.1:9999', pairingCode: 'pair', toolToken: 'openclaw-secret', composioToolToken: 'composio-secret' }); server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => { server.close(); store.close(); }); const address = server.address(); if (!address || typeof address === 'string') throw new Error('No address'); const base = `http://127.0.0.1:${address.port}`; assert.equal((await fetch(`${base}/v1/dashboard`, { headers: { 'x-composio-tool-token': 'composio-secret' } })).status, 200); assert.equal((await fetch(`${base}/v1/dashboard`, { headers: { 'x-composio-tool-token': 'openclaw-secret' } })).status, 401); assert.equal((await fetch(`${base}/v1/wuzzuf/approval-requests/not-found/decision`, { method: 'POST', headers: { 'x-composio-tool-token': 'composio-secret', 'content-type': 'application/json' }, body: JSON.stringify({ approved: true }) })).status, 401); assert.equal((await fetch(`${base}/v1/wuzzuf/tools/WUZZUF_SUBMIT_APPLICATION`, { method: 'POST', headers: { 'x-composio-tool-token': 'composio-secret', 'content-type': 'application/json' }, body: '{}' })).status, 403); assert.equal((await fetch(`${base}/v1/wuzzuf/tools/WUZZUF_SUBMIT_APPLICATION`, { method: 'POST', headers: { 'x-openclaw-tool-token': 'openclaw-secret', 'content-type': 'application/json' }, body: '{}' })).status, 403); });


test('dashboard requires all read scopes, excludes raw CV text, and redacts historical answers', async (t) => {
  const store = new Store(join(mkdtempSync(join(tmpdir(), 'dashboard-privacy-')), 'db.sqlite')); const service = new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider()); const profile = importCvText('Private', 'cv.md', 'Email: private@example.com\nPhone: +201234567890\nSkills: TypeScript'); service.saveProfile(profile); service.audit('privacy', 'application.preview_ready', { answers: [{ label: 'Email address', value: 'private@example.com' }, { label: 'Phone number', value: '+201234567890' }] });
  const server = createBridge(service, { allowedOrigin: 'http://127.0.0.1:9999', pairingCode: 'correct', toolToken: 'audit-only-secret', openclawScopes: ['audit:read'] }); server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => { server.close(); store.close(); }); const address = server.address(); if (!address || typeof address === 'string') throw new Error('No address'); const base = `http://127.0.0.1:${address.port}`;
  assert.equal((await fetch(`${base}/v1/dashboard`, { headers: { 'x-openclaw-tool-token': 'audit-only-secret' } })).status, 403);
  const paired = await fetch(`${base}/v1/pair`, { method: 'POST', headers: { origin: 'http://127.0.0.1:9999', 'content-type': 'application/json' }, body: JSON.stringify({ code: 'correct' }) }); const session = await paired.json() as { token: string };
  const response = await fetch(`${base}/v1/dashboard`, { headers: { origin: 'http://127.0.0.1:9999', authorization: `Bearer ${session.token}` } }); const dashboard = await response.json() as { profiles: Array<{ facts: Array<{ path: string }> }>; timeline: Array<{ detail: unknown }> };
  assert.equal(dashboard.profiles[0]?.facts.some((fact) => fact.path === 'source.rawText'), false); const timeline = JSON.stringify(dashboard.timeline); assert.equal(timeline.includes('private@example.com'), false); assert.equal(timeline.includes('+201234567890'), false);
});
