import test from 'node:test'; import assert from 'node:assert/strict';
import { parseFriendlySchedule, schedulePreview, assertTransition } from '../packages/shared/src/validation.ts';
import { deduplicateJobs, normalizeJob, scoreJob } from '../packages/shared/src/jobs.ts';
import { approveAnswer, generatedAnswerCannotVerify, importCvText, isSensitiveField, prepareAnswer } from '../packages/profile-engine/src/index.ts';
import type { JobCampaign } from '../packages/shared/src/domain.ts';

const profile = importCvText('Backend', 'cv.md', 'Developer\nEmail: dev@example.com\nSkills: TypeScript, Node.js, React');
const now = new Date().toISOString();
const campaign: JobCampaign = { id: 'c1', name: 'Backend', state: 'enabled', searchQueries: ['Node.js'], locations: ['Egypt'], workplace: ['remote'], includedKeywords: ['Node.js'], excludedKeywords: ['unpaid'], seniority: ['senior'], minimumMatchScore: 50, allowedSites: ['development'], maxApplicationsPerRun: 10, maxApplicationsPerDay: 20, schedule: parseFriendlySchedule('Every weekday at 9:00 AM', 'Africa/Cairo'), executionMode: 'prepare_and_review', profileId: profile.id, cvStrategy: 'selected', providerId: 'openclaw', model: 'default', dryRun: true, createdAt: now, updatedAt: now };
test('friendly schedule becomes timezone-aware structured cron', () => { assert.equal(campaign.schedule?.cron, '0 9 * * 1-5'); assert.match(schedulePreview(campaign), /09:00 Africa\/Cairo/); assert.throws(() => parseFriendlySchedule('weekly', 'Mars/Olympus')); });
test('normalization and source-id deduplication are deterministic', () => { const raw = { source: 'x', sourceId: '42', url: 'https://x/42', title: ' Engineer ', employer: ' ACME ', location: ' Cairo ', description: 'Node.js' }; const a = normalizeJob(raw), b = normalizeJob({ ...raw, title: 'Engineer' }); assert.equal(a.fingerprint, b.fingerprint); assert.equal(deduplicateJobs([a, b]).duplicateIds.length, 1); });
test('scoring is explainable and exclusions penalize', () => { const job = normalizeJob({ source: 'x', sourceId: '1', url: 'https://x/1', title: 'Senior Node.js Engineer', employer: 'ACME', location: 'Egypt', description: 'TypeScript Node.js unpaid', requiredSkills: ['TypeScript', 'Node.js'], remote: true, seniority: 'senior' }); const scored = scoreJob(job, profile, campaign); assert.ok(scored.scoreExplanation.length >= 5); assert.ok(scored.matchScore < 100); });
test('sensitive and unknown fields require approval', () => { assert.equal(isSensitiveField('Expected salary'), true); assert.equal(prepareAnswer('Email address', profile).confirmationRequired, false); assert.equal(prepareAnswer('Work authorization', profile).confirmationRequired, true); });
test('generated prose cannot silently become verified fact', () => { const answer = { ...prepareAnswer('Why you?', profile), value: 'Generated pitch' }; assert.equal(generatedAnswerCannotVerify(answer).kind, 'generated_prose'); assert.equal(approveAnswer(answer).kind, 'approved_answer'); assert.notEqual(approveAnswer(answer).kind, 'verified_fact'); });
test('state machine rejects skips and duplicate submit paths', () => { assert.doesNotThrow(() => assertTransition('READY_TO_SUBMIT', 'SUBMITTING')); assert.throws(() => assertTransition('SUBMITTED', 'SUBMITTING')); });
