import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtempSync } from 'node:fs'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { Store } from '../apps/orchestrator/src/store.ts'; import { OrchestratorService } from '../apps/orchestrator/src/service.ts'; import { FixtureJobSource } from '../packages/site-adapters/src/index.ts'; import type { JobSource } from '../packages/site-adapters/src/index.ts'; import { DevelopmentProvider } from '../packages/provider-sdk/src/index.ts'; import { importCvText } from '../packages/profile-engine/src/index.ts'; import type { JobCampaign, RawJob } from '../packages/shared/src/domain.ts';
import type { ChatRequest, LlmProvider } from '../packages/provider-sdk/src/index.ts';
const makeCampaign = (profileId: string, executionMode: JobCampaign['executionMode']): JobCampaign => { const now = new Date().toISOString(); return { id: crypto.randomUUID(), name: 'Test', state: 'enabled', searchQueries: ['Node.js'], locations: ['Egypt'], workplace: ['remote'], includedKeywords: ['Node.js'], excludedKeywords: [], seniority: ['senior'], minimumMatchScore: 50, allowedSites: ['development'], maxApplicationsPerRun: 10, maxApplicationsPerDay: 20, executionMode, profileId, cvStrategy: 'selected', providerId: 'development', model: 'development', dryRun: true, createdAt: now, updatedAt: now }; };
test('vertical slice discovers, scores, prepares approval metadata, and audits', async () => { const store = new Store(join(mkdtempSync(join(tmpdir(), 'orchestrator-')), 'db.sqlite')); const service = new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider()); const profile = importCvText('Test', 'cv.md', 'Email: dev@example.com\nSkills: TypeScript, Node.js'); store.saveProfile(profile); const result = await service.runCampaign(makeCampaign(profile.id, 'prepare_and_review')); assert.equal(result.jobs.length, 1); assert.equal(result.applications.length, 1); assert.equal(result.applications[0]!.answers.find((a) => a.label.includes('sponsorship'))?.confirmationRequired, true); assert.ok(store.timeline(result.correlationId).some((e) => e.type === 'application.preview_ready')); store.close(); });
test('research-only mode and emergency stop cannot start applications', async () => { const store = new Store(join(mkdtempSync(join(tmpdir(), 'research-')), 'db.sqlite')); const service = new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider()); const profile = importCvText('Test', 'cv.md', 'Skills: TypeScript, Node.js'); store.saveProfile(profile); const result = await service.runCampaign(makeCampaign(profile.id, 'research_only')); assert.equal(result.applications.length, 0); service.emergencyStop.engage(); await assert.rejects(service.runCampaign(makeCampaign(profile.id, 'prepare_and_review')), /Emergency stop/); store.close(); });
test('chat is grounded in selected resume facts and treats pages as untrusted', async () => { class CaptureProvider implements LlmProvider { id = 'capture'; request?: ChatRequest; async testConnection() { return { ok: true, detail: 'ok' }; } async discoverModels() { return [{ id: 'local', name: 'Local' }]; } async *streamChat(request: ChatRequest) { this.request = request; yield 'Professional answer'; } } const provider = new CaptureProvider(); const store = new Store(join(mkdtempSync(join(tmpdir(), 'grounded-')), 'db.sqlite')); const service = new OrchestratorService(store, new FixtureJobSource(), provider); const profile = importCvText('Backend', 'cv.md', 'Email: dev@example.com\nSkills: TypeScript, Node.js'); store.saveProfile(profile); store.saveAgentSettings({ chatModel: 'local', answerModel: 'local', matchingModel: 'local', activeProfileId: profile.id, temperature: 0.2, maximumAnswerLength: 500, confidenceThreshold: 0.8, maximumConcurrentRuns: 1, defaultDryRun: true, browserHeadless: true, updatedAt: new Date().toISOString() }); let reply = ''; for await (const chunk of service.chat('Answer this question')) reply += chunk; assert.equal(reply, 'Professional answer'); assert.match(provider.request?.messages[0]?.content ?? '', /TypeScript/); assert.match(provider.request?.messages[0]?.content ?? '', /untrusted data/); assert.equal(provider.request?.model, 'local'); const answers = await service.prepareQuestions(['Why should we hire you?']); assert.equal(answers[0]?.confirmationRequired, true); assert.equal(answers[0]?.confidence, 0.5); store.close(); });


test('campaign run and local-day limits are enforced across repeated runs', async () => {
  class ChangingSource implements JobSource { id = 'changing'; run = 0; async discover(): Promise<RawJob[]> { const run = this.run++; return Array.from({ length: 5 }, (_, index) => ({ source: 'test', sourceId: `${run}-${index}`, url: `https://example.test/jobs/${run}-${index}`, title: 'TypeScript Engineer', employer: 'Example', location: 'Egypt', description: 'TypeScript role', requiredSkills: ['TypeScript'], remote: true, seniority: 'senior' })); } }
  const store = new Store(join(mkdtempSync(join(tmpdir(), 'campaign-limits-')), 'db.sqlite')); const source = new ChangingSource(); const service = new OrchestratorService(store, source, new DevelopmentProvider()); const profile = importCvText('Test', 'cv.md', 'Skills: TypeScript, Node.js'); store.saveProfile(profile);
  const campaign = { ...makeCampaign(profile.id, 'prepare_and_review'), maxApplicationsPerRun: 2, maxApplicationsPerDay: 3, timezone: 'Africa/Cairo' };
  const first = await service.runCampaign(campaign); const second = await service.runCampaign(campaign);
  assert.equal(first.applications.length, 2); assert.equal(second.applications.length, 1);
  const reasons = store.timeline().filter((event) => event.type === 'job.skipped').map((event) => event.detail.reason); assert.ok(reasons.includes('per_run_limit')); assert.ok(reasons.includes('daily_limit')); store.close();
});
