import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
import { detectWuzzufPageState, normalizeWuzzufUrl, parseWuzzufJobHtml, parseWuzzufSearchHtml, sourceIdFromWuzzufUrl } from '../packages/site-adapters/src/wuzzuf-parser.ts';
import { deduplicateJobs, normalizeJob } from '../packages/shared/src/jobs.ts';

const fixture = (name: string) => readFile(`apps/playwright-worker/fixtures/wuzzuf/${name}.html`, 'utf8');
test('Wuzzuf search parser normalizes real fields, URLs, and discovery metadata', async () => { const jobs = parseWuzzufSearchHtml(await fixture('search-results'), 'https://wuzzuf.net', '2026-01-02T03:04:05.000Z'); assert.equal(jobs.length, 2); assert.deepEqual(jobs[0]?.requiredSkills, ['Node.js', 'TypeScript']); assert.equal(jobs[0]?.remote, true); assert.equal(jobs[0]?.sourceId, 'mock-node-1'); assert.equal(jobs[0]?.url, 'https://wuzzuf.net/jobs/p/mock-node-1'); assert.equal(jobs[0]?.discoveredAt, '2026-01-02T03:04:05.000Z'); });
test('Wuzzuf search parser ignores rendered CSS and accepts a real empty result', () => { const html = '<html><body><article><h2><a href="/jobs/p/current-layout">Backend Engineer</a></h2><a href="/company/acme"><style>.css-x{color:red}</style>Acme</a><a href="/a/node"><style>.css-y{display:block}</style>Node.js</a></article></body></html>'; const jobs = parseWuzzufSearchHtml(html); assert.equal(jobs[0]?.employer, 'Acme'); assert.deepEqual(jobs[0]?.requiredSkills, ['Node.js']); assert.deepEqual(parseWuzzufSearchHtml('<html><body><p>No jobs found</p></body></html>'), []); });
test('Wuzzuf details parser replaces placeholders with description, requirements, and availability', async () => { const job = parseWuzzufJobHtml(await fixture('job-details'), 'https://wuzzuf.net/jobs/p/mock-node-1'); assert.equal(job.title, 'Senior Node.js Engineer'); assert.equal(job.employer, 'Example Labs'); assert.match(job.description, /production Node.js/); assert.deepEqual(job.responsibilities, ['Design TypeScript APIs', 'Review production changes']); assert.deepEqual(job.requirements, ['Three years of Node.js experience', 'Strong TypeScript knowledge']); assert.equal(job.applicationAvailable, true); });
test('Wuzzuf URL allowlist and source IDs reject unsupported origins', () => { assert.equal(normalizeWuzzufUrl('https://www.wuzzuf.net/jobs/p/abc/?utm_source=x'), 'https://wuzzuf.net/jobs/p/abc'); assert.equal(sourceIdFromWuzzufUrl('https://wuzzuf.net/jobs/p/abc'), 'abc'); assert.throws(() => normalizeWuzzufUrl('https://evil.example/jobs/p/abc'), /Only supported Wuzzuf/); });
test('parser detects login, challenge, unsupported layout, and deduplication', async () => { assert.equal(detectWuzzufPageState(await fixture('login-required')), 'login_required'); assert.equal(detectWuzzufPageState(await fixture('challenge')), 'challenge'); assert.equal(detectWuzzufPageState('<html><body>Performing security verification. This website uses a security service to protect against malicious bots.</body></html>'), 'challenge'); const unsupported = await fixture('unsupported-layout'); assert.throws(() => parseWuzzufJobHtml(unsupported, 'https://wuzzuf.net/jobs/p/x'), /Required job detail/); const raw = parseWuzzufSearchHtml(await fixture('search-results')); const result = deduplicateJobs([normalizeJob(raw[0]!), normalizeJob(raw[0]!)]); assert.equal(result.unique.length, 1); });
