import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtempSync } from 'node:fs'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { startMockSite } from '../apps/playwright-worker/src/mock-server.ts'; import { WuzzufAdapter } from '../packages/site-adapters/src/wuzzuf-adapter.ts'; import { FixtureJobSource } from '../packages/site-adapters/src/index.ts'; import { Store } from '../apps/orchestrator/src/store.ts'; import { OrchestratorService } from '../apps/orchestrator/src/service.ts'; import { DevelopmentProvider } from '../packages/provider-sdk/src/index.ts'; import { importCvText } from '../packages/profile-engine/src/index.ts'; import { WuzzufToolError } from '../packages/shared/src/wuzzuf.ts';
import { chromium, type Browser, type BrowserContext, type Page } from 'playwright'; import type { BrowserConnectionManager } from '../packages/site-adapters/src/chrome-cdp-manager.ts';

class IsolatedTestBrowserManager implements BrowserConnectionManager { private browser: Browser | undefined; private context: BrowserContext | undefined; async connect() { this.browser ??= await chromium.launch({ headless: true }); this.context ??= await this.browser.newContext(); return this.context; } async openTab(url: string): Promise<Page> { const page = await (await this.connect()).newPage(); await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60_000 }); return page; } async disconnect() { await this.browser?.close(); this.browser = undefined; this.context = undefined; } isConnected() { return this.browser?.isConnected() === true; } status(): 'connected' | 'disconnected' | 'not_connected' { return this.isConnected() ? 'connected' : 'not_connected'; } }

async function setup(t: test.TestContext) { const server = await startMockSite(0); const address = server.address(); if (!address || typeof address === 'string') throw new Error('Mock site did not bind'); const root = mkdtempSync(join(tmpdir(), 'wuzzuf-integration-')); const adapter = new WuzzufAdapter({ baseUrl: `http://127.0.0.1:${address.port}`, browserManager: new IsolatedTestBrowserManager(), screenshotDir: join(root, 'screenshots') }); const store = new Store(join(root, 'db.sqlite')); const service = new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider(), adapter); const profile = importCvText('Backend', 'cv.md', 'Email: dev@example.com\nPhone: +201234567890\nSkills: TypeScript, Node.js, SQL'); profile.cvVariants[0]!.approved = true; store.saveProfile(profile); store.saveAgentSettings({ activeProfileId: profile.id, chatModel: 'development', answerModel: 'development', matchingModel: 'development', temperature: 0.2, maximumAnswerLength: 800, confidenceThreshold: 0.8, maximumConcurrentRuns: 1, defaultDryRun: false, browserHeadless: true, updatedAt: new Date().toISOString() }); t.after(async () => { await service.wuzzuf.close(); store.close(); server.close(); }); return { service, profile }; }

test('local Wuzzuf flow searches, reads, scores, prepares, fills, reviews and submits once', async (t) => { const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], remote: true, limit: 10 }); assert.equal(search.jobs.length, 1); const details = await service.wuzzuf.details(search.jobs[0]!.url); assert.notEqual(details.job.title, 'Job on Wuzzuf'); assert.equal(details.job.applicationAvailable, true); const score = await service.wuzzuf.score({ jobId: details.job.id, profileId: profile.id }); assert.ok(score.score >= 80); const review = await service.wuzzuf.prepare({ jobId: details.job.id, profileId: profile.id, dryRun: false }); assert.equal(review.state, 'WAITING_FOR_APPROVAL'); const filled = await service.wuzzuf.fill({ applicationId: review.id, dryRun: false }); assert.equal(filled.state, 'READY_TO_SUBMIT'); assert.equal(filled.submissionAllowed, true); const approval = service.wuzzuf.createApprovalToken(review.id, 60); await assert.rejects(service.wuzzuf.submit({ applicationId: review.id, approvalToken: 'invalid-token-invalid-token' }), (error: unknown) => error instanceof WuzzufToolError && error.code === 'WUZZUF_APPROVAL_TOKEN_MISSING'); const submitted = await service.wuzzuf.submit({ applicationId: review.id, approvalToken: approval.approvalToken }); assert.equal(submitted.submitted, true); await assert.rejects(service.wuzzuf.submit({ applicationId: review.id, approvalToken: approval.approvalToken }), /already been submitted/); assert.ok(service.store.applicationTimeline(review.id).some((event) => event.type === 'wuzzuf.submission_completed')); });

test('dry-run, emergency stop, and duplicate preparation are centrally blocked', async (t) => { const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: true }); await assert.rejects(service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id }), /already exists/); const filled = await service.wuzzuf.fill({ applicationId: prepared.id, dryRun: false }); assert.equal(filled.dryRun, true); assert.equal(filled.submissionAllowed, false); assert.throws(() => service.wuzzuf.createApprovalToken(prepared.id), /dry-run/i); service.emergencyStop.engage(); await assert.rejects(service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }), /Emergency stop/); const cancelled = await service.wuzzuf.cancel(prepared.id); assert.equal(cancelled.state, 'CANCELLED'); });
