import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtempSync } from 'node:fs'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { startMockSite } from '../apps/playwright-worker/src/mock-server.ts'; import { WuzzufAdapter } from '../packages/site-adapters/src/wuzzuf-adapter.ts'; import { FixtureJobSource } from '../packages/site-adapters/src/index.ts'; import { Store } from '../apps/orchestrator/src/store.ts'; import { OrchestratorService } from '../apps/orchestrator/src/service.ts'; import { DevelopmentProvider } from '../packages/provider-sdk/src/index.ts'; import { importCvText } from '../packages/profile-engine/src/index.ts'; import { WuzzufToolError } from '../packages/shared/src/wuzzuf.ts';
import { chromium, type Browser, type BrowserContext, type Page } from 'playwright'; import type { BrowserConnectionManager } from '../packages/site-adapters/src/chrome-cdp-manager.ts';

class IsolatedTestBrowserManager implements BrowserConnectionManager { private browser: Browser | undefined; private context: BrowserContext | undefined; activePages(): Page[] { return this.context?.pages() ?? []; } async connect() { this.browser ??= await chromium.launch({ headless: true }); this.context ??= await this.browser.newContext(); return this.context; } async openTab(url: string): Promise<Page> { const page = await (await this.connect()).newPage(); await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60_000 }); return page; } async disconnect() { await this.browser?.close(); this.browser = undefined; this.context = undefined; } isConnected() { return this.browser?.isConnected() === true; } status(): 'connected' | 'disconnected' | 'not_connected' { return this.isConnected() ? 'connected' : 'not_connected'; } }

async function setup(t: test.TestContext) { const server = await startMockSite(0); const address = server.address(); if (!address || typeof address === 'string') throw new Error('Mock site did not bind'); const root = mkdtempSync(join(tmpdir(), 'wuzzuf-integration-')); const browserManager = new IsolatedTestBrowserManager(); const adapter = new WuzzufAdapter({ baseUrl: `http://127.0.0.1:${address.port}`, browserManager, navigationTimeoutMs: 2_000, screenshotDir: join(root, 'screenshots') }); const store = new Store(join(root, 'db.sqlite')); const service = new OrchestratorService(store, new FixtureJobSource(), new DevelopmentProvider(), adapter); const profile = importCvText('Backend', 'cv.md', 'Email: dev@example.com\nPhone: +201234567890\nSkills: TypeScript, Node.js, SQL'); profile.cvVariants[0]!.approved = true; store.saveProfile(profile); store.saveAgentSettings({ activeProfileId: profile.id, chatModel: 'development', answerModel: 'development', matchingModel: 'development', temperature: 0.2, maximumAnswerLength: 800, confidenceThreshold: 0.8, maximumConcurrentRuns: 1, defaultDryRun: false, browserHeadless: true, updatedAt: new Date().toISOString() }); t.after(async () => { await service.wuzzuf.close(); store.close(); server.close(); }); return { service, profile, browserManager }; }

test('local Wuzzuf flow searches, reads, scores, prepares, fills, reviews and submits once', async (t) => { const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], remote: true, limit: 10 }); assert.equal(search.jobs.length, 1); const details = await service.wuzzuf.details(search.jobs[0]!.url); assert.notEqual(details.job.title, 'Job on Wuzzuf'); assert.equal(details.job.applicationAvailable, true); const score = await service.wuzzuf.score({ jobId: details.job.id, profileId: profile.id }); assert.ok(score.score >= 80); const review = await service.wuzzuf.prepare({ jobId: details.job.id, profileId: profile.id, dryRun: false }); assert.equal(review.state, 'WAITING_FOR_APPROVAL'); const filled = await service.wuzzuf.fill({ applicationId: review.id, dryRun: false }); assert.equal(filled.state, 'READY_TO_SUBMIT'); assert.equal(filled.submissionAllowed, true); const approval = service.wuzzuf.requestSubmissionApproval({ applicationId: review.id, ttlSeconds: 60 }); await assert.rejects(service.wuzzuf.submit({ applicationId: review.id, approvalRequestId: 'invalid-request' }), (error: unknown) => error instanceof WuzzufToolError && error.code === 'WUZZUF_APPROVAL_REQUIRED'); const decision = service.wuzzuf.decideApproval(approval.id, true); assert.ok(decision.approvalToken); const submitted = await service.wuzzuf.submit({ applicationId: review.id, approvalRequestId: approval.id, approvalToken: decision.approvalToken! }); assert.equal((submitted as { submitted: boolean }).submitted, true); const duplicate = await service.wuzzuf.submit({ applicationId: review.id, approvalRequestId: approval.id, approvalToken: decision.approvalToken! }); assert.equal((duplicate as { submitted: boolean }).submitted, true); assert.ok(service.store.applicationTimeline(review.id).some((event) => event.type === 'wuzzuf.submission_completed')); });

test('generic application service and deprecated Wuzzuf facade share one lifecycle record', async (t) => {
  const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 });
  const prepared = await service.jobs.prepareApplication({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: true });
  assert.equal(service.wuzzuf.review(prepared.id).id, prepared.id); assert.equal(service.jobs.getApplicationStatus(prepared.id).state, prepared.state);
  const cancelled = await service.wuzzuf.cancel(prepared.id); assert.equal(cancelled.state, 'CANCELLED'); assert.equal(service.jobs.getApplicationStatus(prepared.id).state, 'CANCELLED');
});

test('dry-run, emergency stop, and duplicate preparation are centrally blocked', async (t) => { const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: true }); await assert.rejects(service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id }), /already exists/); const filled = await service.wuzzuf.fill({ applicationId: prepared.id, dryRun: false }); assert.equal(filled.dryRun, true); assert.equal(filled.submissionAllowed, false); assert.throws(() => service.wuzzuf.requestSubmissionApproval({ applicationId: prepared.id }), /dry-run/i); service.emergencyStop.engage(); await assert.rejects(service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }), /Emergency stop/); const cancelled = await service.wuzzuf.cancel(prepared.id); assert.equal(cancelled.state, 'CANCELLED'); });

test('approval is invalidated when the reviewed answers change', async (t) => { const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: false }); await service.wuzzuf.fill({ applicationId: prepared.id, dryRun: false }); const approval = service.wuzzuf.requestSubmissionApproval({ applicationId: prepared.id }); const changed = service.store.getPreparedApplication(prepared.id)!; changed.answers[0] = { ...changed.answers[0]!, value: 'changed after review' }; service.store.savePreparedApplication(changed); assert.throws(() => service.wuzzuf.decideApproval(approval.id, true), (error: unknown) => error instanceof WuzzufToolError && error.code === 'WUZZUF_APPROVAL_INVALIDATED'); });

test('form fingerprint changes stop filling and invalidate the workflow', async (t) => { const { service, profile } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: false }); const changed = service.store.getPreparedApplication(prepared.id)!; changed.formFingerprint = { ...changed.formFingerprint!, formVersion: 'changed-form-version' }; service.store.savePreparedApplication(changed); await assert.rejects(service.wuzzuf.fill({ applicationId: prepared.id, dryRun: false }), (error: unknown) => error instanceof WuzzufToolError && error.code === 'FORM_CHANGED'); assert.equal(service.store.getPreparedApplication(prepared.id)?.state, 'FORM_CHANGED'); });


test('submission is blocked when browser values change after approval', async (t) => {
  const { service, profile, browserManager } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: false }); await service.wuzzuf.fill({ applicationId: prepared.id, dryRun: false }); const approval = service.wuzzuf.requestSubmissionApproval({ applicationId: prepared.id }); const decision = service.wuzzuf.decideApproval(approval.id, true); const page = browserManager.activePages().find((item) => item.url().includes('/apply/')); assert.ok(page); await page.locator('#email').fill('changed-after-approval@example.com');
  await assert.rejects(service.wuzzuf.submit({ applicationId: prepared.id, approvalRequestId: approval.id, approvalToken: decision.approvalToken! }), (error: unknown) => error instanceof WuzzufToolError && error.code === 'FORM_VALUES_CHANGED'); assert.equal(service.store.getPreparedApplication(prepared.id)?.state, 'FORM_CHANGED'); assert.equal(service.store.getApprovalRequest(approval.id)?.status, 'invalidated');
});

test('checkbox No is applied instead of being falsely reported as filled', async (t) => {
  const { service, profile, browserManager } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: false }); const record = service.store.getPreparedApplication(prepared.id)!; const page = browserManager.activePages().find((item) => item.url().includes('/apply/')); assert.ok(page); await page.locator('form').evaluate((form) => { const label = document.createElement('label'); label.htmlFor = 'newsletter'; label.textContent = 'Newsletter'; const input = document.createElement('input'); input.id = 'newsletter'; input.type = 'checkbox'; input.checked = true; form.append(label, input); });
  const result = await service.wuzzuf.adapter.fillFields({ id: record.adapterSessionId! }, [{ fieldId: 'field-2', label: 'Newsletter', value: 'No', confidence: 1, supportingFactIds: [], confirmationRequired: false, generatedAt: new Date().toISOString(), model: 'test' }], { correlationId: record.correlationId, dryRun: false, signal: new AbortController().signal }); const values = await service.wuzzuf.adapter.collectFieldValues({ id: record.adapterSessionId! }); assert.deepEqual(result, { filled: ['Newsletter'], skipped: [] }); assert.equal(values.find((value) => value.id === 'field-2')?.value, 'false');
});

test('unconfirmed submit is marked outcome-unknown and never reported successful', async (t) => {
  const { service, profile, browserManager } = await setup(t); const search = await service.wuzzuf.search({ queries: ['Node.js'], locations: ['Egypt'], limit: 1 }); const prepared = await service.wuzzuf.prepare({ jobId: search.jobs[0]!.id, profileId: profile.id, dryRun: false }); await service.wuzzuf.fill({ applicationId: prepared.id, dryRun: false }); const approval = service.wuzzuf.requestSubmissionApproval({ applicationId: prepared.id }); const decision = service.wuzzuf.decideApproval(approval.id, true); const page = browserManager.activePages().find((item) => item.url().includes('/apply/')); assert.ok(page); await page.locator('#application-status').evaluate((node) => node.removeAttribute('role'));
  await assert.rejects(service.wuzzuf.submit({ applicationId: prepared.id, approvalRequestId: approval.id, approvalToken: decision.approvalToken! }), (error: unknown) => error instanceof WuzzufToolError && error.code === 'WUZZUF_SUBMISSION_OUTCOME_UNKNOWN'); assert.equal(service.store.getPreparedApplication(prepared.id)?.state, 'FAILED_PERMANENT'); assert.equal(service.store.getPreparedApplication(prepared.id)?.submissionResult, undefined);
});
