const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
let latestRun: any;
function send(message: Record<string, unknown>): Promise<any> { return chrome.runtime.sendMessage(message).then((result: any) => { if (result?.ok === false) throw new Error(result.error); return result; }); }
function setStatus(text: string, error = false) { $('#status').textContent = text; $('#status').className = error ? 'error' : ''; }

$('#pair').addEventListener('submit', async (event) => { event.preventDefault(); try { await send({ type: 'pair', code: ($('#pair-code') as HTMLInputElement).value }); setStatus('Paired securely'); await refresh(); } catch (e) { setStatus(String(e), true); } });
$('#chat').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#chat-input') as HTMLInputElement; $('#messages').append(document.createTextNode(`You: ${input.value}\nOpenClaw: `)); await send({ type: 'chat', text: input.value }); input.value = ''; });
chrome.runtime.onMessage.addListener((message: any) => { if (message.type === 'chat-event') { if (message.event.type === 'chunk') $('#messages').append(document.createTextNode(message.event.text)); if (message.event.type === 'done') $('#messages').append(document.createTextNode('\n')); } });
$('#import-profile').addEventListener('submit', async (event) => { event.preventDefault(); const file = ($('#cv-file') as HTMLInputElement).files?.[0]; if (!file) return; try { const profile = await send({ type: 'importProfile', body: { name: ($('#profile-name') as HTMLInputElement).value, sourceName: file.name, text: await file.text() } }); ($('#profile-id') as HTMLInputElement).value = profile.id; setStatus(`Imported ${profile.facts.length} provenance-tagged facts`); await refresh(); } catch (e) { setStatus(String(e), true); } });
$('#create-campaign').addEventListener('submit', async (event) => { event.preventDefault(); try { const body = { name: ($('#campaign-name') as HTMLInputElement).value, profileId: ($('#profile-id') as HTMLInputElement).value, searchQueries: [($('#query') as HTMLInputElement).value], locations: [($('#location') as HTMLInputElement).value], schedule: ($('#schedule') as HTMLInputElement).value, timezone: ($('#timezone') as HTMLInputElement).value, includedKeywords: ['Node.js', 'TypeScript'], excludedKeywords: [], allowedSites: ['development'], executionMode: 'prepare_and_review', minimumMatchScore: 50, dryRun: ($('#dry-run') as HTMLInputElement).checked }; const result = await send({ type: 'createCampaign', body }); setStatus(result.preview); await refresh(); } catch (e) { setStatus(String(e), true); } });
$('#campaigns').addEventListener('click', async (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]'); if (!button) return; try { const action = button.dataset.action; if (action === 'run') { latestRun = await send({ type: 'runCampaign', id: button.dataset.id }); renderRun(latestRun); } else await send({ type: action === 'pause' ? 'pauseCampaign' : 'resumeCampaign', id: button.dataset.id }); await refresh(); } catch (e) { setStatus(String(e), true); } });
$('#profiles').addEventListener('change', async (event) => { const input = (event.target as HTMLElement).closest<HTMLInputElement>('input[data-fact]'); if (!input) return; try { await send({ type: 'updateFact', profileId: input.dataset.profile, factId: input.dataset.fact, value: input.value }); setStatus('Verified fact updated'); await refresh(); } catch (e) { setStatus(String(e), true); } });
$('#fill').addEventListener('click', async () => { const application = latestRun?.applications?.[0]; if (!application) return; const answers = application.answers.map((a: any) => ({ ...a, approved: !a.confirmationRequired || confirm(`Approve ${a.label}: ${a.value || '(unknown)'}?`) })); const result = await send({ type: 'fill-approved', answers, dryRun: ($('#dry-run') as HTMLInputElement).checked }); await send({ type: 'recordFill', applicationId: application.id, body: { correlationId: latestRun.correlationId, filled: result.filled, skipped: result.skipped } }); setStatus(`Fill result: ${result.filled.length} filled, ${result.skipped.length} skipped`); await refresh(); });
$('#stop').addEventListener('click', async () => { await send({ type: 'emergencyStop' }); setStatus('EMERGENCY STOP ENGAGED'); await refresh(); });
$('#reset-stop').addEventListener('click', async () => { await send({ type: 'resetStop' }); setStatus('Emergency stop reset'); await refresh(); });
async function refresh() { try { const data = await send({ type: 'dashboard' }); $('#health').textContent = data.emergencyStop ? 'Stopped' : 'Connected'; $('#campaigns').innerHTML = data.campaigns.map((c: any) => `<article><b>${escapeHtml(c.name)}</b> · ${escapeHtml(c.executionMode)} · ${escapeHtml(c.state)} · ${c.dryRun ? 'dry-run' : 'live'} <button data-action="run" data-id="${c.id}" ${c.state === 'paused' ? 'disabled' : ''}>Run</button><button data-action="${c.state === 'paused' ? 'resume' : 'pause'}" data-id="${c.id}">${c.state === 'paused' ? 'Resume' : 'Pause'}</button></article>`).join('') || 'No campaigns'; $('#profiles').innerHTML = data.profiles.map((p: any) => `<article><b>${escapeHtml(p.name)}</b>${p.facts.filter((f: any) => f.path !== 'source.rawText').map((f: any) => `<label>${escapeHtml(f.path)}<input data-profile="${p.id}" data-fact="${f.id}" value="${escapeHtml(String(f.value))}"></label>`).join('')}</article>`).join('') || 'No profiles'; $('#timeline').textContent = data.timeline.map((e: any) => `${e.at}  ${e.type}`).join('\n') || 'No events'; } catch { $('#health').textContent = 'Not paired'; } }
function renderRun(run: any) { const app = run.applications?.[0]; $('#preview').innerHTML = app ? `<h3>${escapeHtml(app.job.title)} · ${app.job.matchScore}%</h3>${app.answers.map((a: any) => `<div>${escapeHtml(a.label)}: ${escapeHtml(a.value || 'Unknown')} <b>${a.confirmationRequired ? 'Approval required' : 'Verified'}</b></div>`).join('')}` : 'No selected applications'; }
function escapeHtml(value: string) { const el = document.createElement('span'); el.textContent = value; return el.innerHTML; }
void refresh();
