const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
let dashboard: any = { profiles: [], agentSettings: {} }; let preparedAnswers: any[] = [];
const send = (message: Record<string, unknown>): Promise<any> => chrome.runtime.sendMessage(message).then((result: any) => { if (result?.ok === false) throw new Error(result.error); return result; });
const notice = (text = '', error = false) => { $('#notice').textContent = text; $('#notice').style.color = error ? '#d33' : '#0c9b68'; };

document.querySelectorAll<HTMLButtonElement>('nav button').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('nav button,.view').forEach((el) => el.classList.remove('active')); button.classList.add('active'); $(`#tab-${button.dataset.tab}`).classList.add('active'); }));
$('#pair').addEventListener('submit', async (event) => { event.preventDefault(); try { await send({ type: 'pair', code: ($('#pair-code') as HTMLInputElement).value }); notice('Connected securely'); await refresh(); await loadModels(); } catch (error) { notice(message(error), true); } });
$('#chat').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#chat-input') as HTMLTextAreaElement; const text = input.value.trim(); if (!text) return; addBubble('user', text); addBubble('assistant', '', 'streaming'); input.value = ''; try { await send({ type: 'chat', text, profileId: ($('#active-profile') as HTMLSelectElement).value }); } catch (error) { finishStream(message(error)); } });
chrome.runtime.onMessage.addListener((event: any) => { if (event.type !== 'chat-event') return; if (event.event.type === 'chunk') $('.bubble[data-stream="streaming"] p').append(document.createTextNode(event.event.text)); if (event.event.type === 'done') finishStream(); if (event.event.type === 'error') finishStream(event.event.text); });
$('#import-profile').addEventListener('submit', async (event) => { event.preventDefault(); const file = ($('#cv-file') as HTMLInputElement).files?.[0]; if (!file) return; if (file.size > 4 * 1024 * 1024) return notice('Resume must be smaller than 4 MB', true); try { notice('Reading and structuring your resume…'); const base64 = arrayBufferToBase64(await file.arrayBuffer()); const profile = await send({ type: 'importProfile', body: { name: ($('#profile-name') as HTMLInputElement).value, sourceName: file.name, base64 } }); notice(`Resume ready · ${profile.facts.length - 1} verified facts`); await refresh(); } catch (error) { notice(message(error), true); } });
$('#profiles').addEventListener('change', async (event) => { const input = (event.target as HTMLElement).closest<HTMLInputElement>('input[data-fact]'); if (!input) return; try { await send({ type: 'updateFact', profileId: input.dataset.profile, factId: input.dataset.fact, value: input.value }); notice('Verified fact saved'); } catch (error) { notice(message(error), true); } });
$('#analyze').addEventListener('click', async () => { try { const page = await send({ type: 'inspect-form' }); $('#page-context').textContent = `${page.fields.length} fields · ${page.title}`; if (!page.fields.length) return notice('No visible application fields found', true); preparedAnswers = await send({ type: 'prepareAnswers', body: { labels: page.fields.map((f: any) => f.label), profileId: ($('#active-profile') as HTMLSelectElement).value } }); renderAnswers(); } catch (error) { notice(message(error), true); } });
$('#answers').addEventListener('input', (event) => { const input = (event.target as HTMLElement).closest<HTMLTextAreaElement>('textarea[data-index]'); if (input) preparedAnswers[Number(input.dataset.index)].value = input.value; });
$('#fill').addEventListener('click', async () => { try { const answers = preparedAnswers.map((answer, index) => ({ ...answer, approved: !answer.confirmationRequired || ($(`#approve-${index}`) as HTMLInputElement).checked })); const result = await send({ type: 'fill-approved', answers, dryRun: dashboard.agentSettings.defaultDryRun }); notice(`${result.filled.length} fields ${result.dryRun ? 'previewed' : 'filled'} · ${result.skipped.length} skipped`); } catch (error) { notice(message(error), true); } });
$('#agent-settings').addEventListener('submit', async (event) => { event.preventDefault(); try { dashboard.agentSettings = await send({ type: 'saveAgentSettings', body: { activeProfileId: ($('#active-profile') as HTMLSelectElement).value, chatModel: ($('#chat-model') as HTMLSelectElement).value, answerModel: ($('#answer-model') as HTMLSelectElement).value, matchingModel: ($('#matching-model') as HTMLSelectElement).value, temperature: Number(($('#temperature') as HTMLInputElement).value), maximumAnswerLength: Number(($('#max-answer') as HTMLInputElement).value), confidenceThreshold: Number(($('#confidence') as HTMLInputElement).value), maximumConcurrentRuns: Number(($('#concurrency') as HTMLInputElement).value), defaultDryRun: ($('#default-dry-run') as HTMLInputElement).checked, browserHeadless: ($('#headless') as HTMLInputElement).checked } }); notice('Local agent configuration saved'); } catch (error) { notice(message(error), true); } });
$('#stop').addEventListener('click', async () => { await send({ type: 'emergencyStop' }); notice('Emergency stop engaged', true); await refresh(); }); $('#reset-stop').addEventListener('click', async () => { await send({ type: 'resetStop' }); notice('Emergency stop reset'); await refresh(); });

async function refresh() { try { dashboard = await send({ type: 'dashboard' }); $('#health').textContent = dashboard.emergencyStop ? 'Stopped' : 'Connected'; $('#health').classList.toggle('online', !dashboard.emergencyStop); renderProfiles(); renderSettings(); } catch { $('#health').textContent = 'Pair required'; } }
async function loadModels() { try { const models = await send({ type: 'models' }); ['chat-model','answer-model','matching-model'].forEach((id) => { const select = $(`#${id}`) as HTMLSelectElement; select.innerHTML = models.map((model: any) => `<option value="${escapeHtml(model.id)}">${escapeHtml(model.name)}</option>`).join(''); }); renderSettings(); } catch (error) { notice(`Model discovery: ${message(error)}`, true); } }
function renderProfiles() { const active = dashboard.agentSettings.activeProfileId ?? dashboard.profiles[0]?.id ?? ''; ($('#active-profile') as HTMLSelectElement).innerHTML = dashboard.profiles.map((p: any) => `<option value="${p.id}" ${p.id === active ? 'selected' : ''}>${escapeHtml(p.name)}</option>`).join(''); $('#profiles').innerHTML = dashboard.profiles.map((p: any) => `<article><b>${escapeHtml(p.name)}</b>${p.facts.filter((f: any) => f.path !== 'source.rawText').map((f: any) => `<label>${escapeHtml(f.path)}<input data-profile="${p.id}" data-fact="${f.id}" value="${escapeHtml(String(f.value))}"></label>`).join('')}</article>`).join(''); }
function renderSettings() { const s = dashboard.agentSettings; const values: Record<string, any> = { 'chat-model': s.chatModel, 'answer-model': s.answerModel, 'matching-model': s.matchingModel, temperature: s.temperature, 'max-answer': s.maximumAnswerLength, confidence: s.confidenceThreshold, concurrency: s.maximumConcurrentRuns }; for (const [id, value] of Object.entries(values)) { const el = $(`#${id}`) as HTMLInputElement | HTMLSelectElement; if (value !== undefined) el.value = String(value); } ($('#default-dry-run') as HTMLInputElement).checked = s.defaultDryRun !== false; ($('#headless') as HTMLInputElement).checked = s.browserHeadless !== false; }
function renderAnswers() { $('#approval-panel').classList.remove('hidden'); $('#answers').innerHTML = preparedAnswers.map((a, i) => `<div class="answer"><b>${escapeHtml(a.label)}</b><textarea data-index="${i}">${escapeHtml(a.value || '')}</textarea>${a.confirmationRequired ? `<label><input id="approve-${i}" type="checkbox"> Approve this answer</label><small>${escapeHtml(a.reason || 'Confirmation required')}</small>` : '<small>Grounded in verified resume facts</small>'}</div>`).join(''); }
function addBubble(role: 'user'|'assistant', text: string, stream?: string) { const div = document.createElement('div'); div.className = `bubble ${role}`; if (stream) div.dataset.stream = stream; const name = document.createElement('b'); name.textContent = role === 'assistant' ? 'OpenClaw' : 'You'; const p = document.createElement('p'); p.textContent = text; div.append(name, p); $('#messages').append(div); $('#messages').scrollTop = $('#messages').scrollHeight; }
function finishStream(error?: string) { const bubble = document.querySelector<HTMLElement>('.bubble[data-stream="streaming"]'); if (!bubble) return; delete bubble.dataset.stream; if (error) bubble.querySelector('p')!.textContent = error; }
function arrayBufferToBase64(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); let binary = ''; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(binary); }
function escapeHtml(value: string) { const span = document.createElement('span'); span.textContent = value; return span.innerHTML; } function message(error: unknown) { return error instanceof Error ? error.message : String(error); }
void refresh().then(loadModels);
