const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
let dashboard: any = { profiles: [], resumes: [], campaigns: [], timeline: [], queue: {}, agentSettings: {} }; let preparedAnswers: any[] = [];
let wuzzufApplicationId = ''; let wuzzufApprovalRequestId = ''; let wuzzufApprovalToken = '';
let currentJob: any; let currentTailoring: any; let pdfPreviewUrl = '';
const send = (message: Record<string, unknown>): Promise<any> => chrome.runtime.sendMessage(message).then((result: any) => { if (result?.ok === false) throw new Error(typeof result.error === 'object' ? `${result.error.code}: ${result.error.message}` : result.error); return result; });
const notice = (text = '', error = false) => { $('#notice').textContent = text; $('#notice').style.color = error ? '#d33' : '#0c9b68'; };

document.querySelectorAll<HTMLButtonElement>('nav button').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('nav button,.view').forEach((el) => el.classList.remove('active')); button.classList.add('active'); $(`#tab-${button.dataset.tab}`).classList.add('active'); }));
$('#pair').addEventListener('submit', async (event) => { event.preventDefault(); try { await send({ type: 'pair', code: ($('#pair-code') as HTMLInputElement).value }); notice('Connected securely'); $('#pairing-card').classList.add('hidden'); await refresh(); await loadModels(); } catch (error) { notice(message(error), true); } });
$('#chat').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#chat-input') as HTMLTextAreaElement; const text = input.value.trim(); if (!text) return; addBubble('user', text); addBubble('assistant', '', 'streaming'); input.value = ''; try { await send({ type: 'chat', text, profileId: ($('#active-profile') as HTMLSelectElement).value }); } catch (error) { finishStream(message(error)); } });
chrome.runtime.onMessage.addListener((event: any) => { if (event.type !== 'chat-event') return; if (event.event.type === 'chunk') $('.bubble[data-stream="streaming"] p').append(document.createTextNode(event.event.text)); if (event.event.type === 'done') finishStream(); if (event.event.type === 'error') finishStream(event.event.text); });
$('#import-profile').addEventListener('submit', async (event) => { event.preventDefault(); const file = ($('#cv-file') as HTMLInputElement).files?.[0]; if (!file) return; if (file.size > 4 * 1024 * 1024) return notice('Resume must be smaller than 4 MB', true); try { notice('Validating and extracting your resume locally…'); const base64 = arrayBufferToBase64(await file.arrayBuffer()); const response = await send({ type: 'importProfile', body: { profileId: 'default', sourceName: file.name, base64 } }); const imported = response.data; notice(`Resume imported · review ${imported.facts.length} extracted facts before approval`); await refresh(); } catch (error) { notice(message(error), true); } });
$('#registered-resumes').addEventListener('click', async (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button[data-resume-action]'); if (!button) return; const resumeId = button.dataset.resumeId!; try { if (button.dataset.resumeAction === 'approve') { await send({ type: 'approveRegisteredResume', resumeId }); notice('Resume facts approved and immutable snapshot created'); } else if (button.dataset.resumeAction === 'remove' && confirm('Delete this resume source and its private local artifact?')) { await send({ type: 'removeRegisteredResume', resumeId }); notice('Resume source and artifact deleted'); } await refresh(); } catch (error) { notice(message(error), true); } });
$('#profiles').addEventListener('change', async (event) => { const target = event.target as HTMLElement; const resume = target.closest<HTMLInputElement>('input[data-resume]'); if (resume) { try { await send({ type: 'approveResume', profileId: resume.dataset.profile, resumeId: resume.dataset.resume, approved: resume.checked }); notice(resume.checked ? 'Resume approved for applications' : 'Resume approval removed'); await refresh(); } catch (error) { notice(message(error), true); } return; } const input = target.closest<HTMLInputElement>('input[data-fact]'); if (!input) return; try { await send({ type: 'updateFact', profileId: input.dataset.profile, factId: input.dataset.fact, value: input.value }); notice('Verified fact saved'); } catch (error) { notice(message(error), true); } });
$('#analyze').addEventListener('click', async () => { try { const imported = await send({ type: 'analyzeCurrentJob' }); currentJob = imported.data?.job ?? imported.job; let scoreText = ''; try { const scored = await send({ type: 'scoreJob', jobId: currentJob.id, profileId: ($('#active-profile') as HTMLSelectElement).value }); currentJob.matchScore = scored.data.score; scoreText = ` · ${scored.data.score}% match`; } catch { scoreText = ' · import a verified profile to score'; } $('#page-context').textContent = `${currentJob.title} · ${currentJob.source.connectorId} → ${currentJob.applicationDestination?.adapterId ?? 'manual'}${scoreText}`; $('#current-job').classList.remove('hidden'); $('#current-job-content').textContent = `${currentJob.title} at ${currentJob.employer} · ${currentJob.location}${scoreText}`; const page = await send({ type: 'inspect-form' }); if (!page.fields.length) return notice('Job imported; no visible application fields found'); preparedAnswers = await send({ type: 'prepareAnswers', body: { labels: page.fields.map((field: any) => field.label), profileId: ($('#active-profile') as HTMLSelectElement).value } }); renderAnswers(); notice('Job analyzed, scored, and application fields mapped'); } catch (error) { notice(message(error), true); } });
$('#tailor-current').addEventListener('click', async () => { const resume = dashboard.resumes?.find((item: any) => item.source.approved); if (!currentJob) return notice('Analyze a current job first', true); if (!resume) return notice('Approve a resume before tailoring', true); try { const response = await send({ type: 'tailorResume', jobId: currentJob.id, resumeId: resume.source.id }); currentTailoring = response.data; renderTailoring(); notice('Grounded tailoring review created; missing requirements were not invented'); } catch (error) { notice(message(error), true); } });
$('#approve-tailoring').addEventListener('click', async () => { if (!currentTailoring || !confirm('Approve this exact factual tailoring diff?')) return; try { await send({ type: 'approveTailoredResume', tailoredResumeId: currentTailoring.tailoredResume.id }); currentTailoring.tailoredResume.approved = true; renderTailoring(); notice('Tailored resume approved'); } catch (error) { notice(message(error), true); } });
$('#tailoring-review-content').addEventListener('click', async (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button[data-preview-pdf]'); if (!button) return; try { const response = await send({ type: 'artifactContent', artifactId: button.dataset.previewPdf }); const bytes = Uint8Array.from(atob(response.data.base64), (character) => character.charCodeAt(0)); if (pdfPreviewUrl) URL.revokeObjectURL(pdfPreviewUrl); pdfPreviewUrl = URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' })); const frame = $('#pdf-preview') as HTMLIFrameElement; frame.src = pdfPreviewUrl; frame.classList.remove('hidden'); } catch (error) { notice(message(error), true); } });
$('#connector-list').addEventListener('change', async (event) => { const input = (event.target as HTMLElement).closest<HTMLInputElement>('input[data-connector]'); if (!input) return; try { await send({ type: 'configureConnector', connectorId: input.dataset.connector, enabled: input.checked }); notice(`${input.dataset.connector} ${input.checked ? 'enabled' : 'disabled'}`); await renderConnectors(); } catch (error) { input.checked = !input.checked; notice(message(error), true); } });
$('#export-data').addEventListener('click', () => { const safe = { exportedAt: new Date().toISOString(), campaigns: dashboard.campaigns, resumes: dashboard.resumes, timeline: dashboard.timeline, queue: dashboard.queue }; const url = URL.createObjectURL(new Blob([JSON.stringify(safe, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'extension-jobs-export.json'; anchor.click(); URL.revokeObjectURL(url); });
$('#delete-data').addEventListener('click', async () => { const confirmation = prompt('This stops active work and deletes local profiles, resumes, jobs, campaigns, history, queues, and private artifacts. Type DELETE LOCAL DATA to continue.'); if (confirmation !== 'DELETE LOCAL DATA') return; try { await send({ type: 'deleteData', confirmation }); if (pdfPreviewUrl) URL.revokeObjectURL(pdfPreviewUrl); pdfPreviewUrl = ''; currentJob = undefined; currentTailoring = undefined; notice('Local personal data deleted; emergency stop remains engaged'); await refresh(); } catch (error) { notice(message(error), true); } });
$('#campaign-create').addEventListener('submit', async (event) => { event.preventDefault(); const profileId = ($('#active-profile') as HTMLSelectElement).value; if (!profileId) return notice('Approve a resume before creating a campaign', true); try { await send({ type: 'createCampaign', body: { name: ($('#campaign-name') as HTMLInputElement).value, profileId, searchQueries: splitInput(($('#campaign-queries') as HTMLInputElement).value), locations: splitInput(($('#campaign-locations') as HTMLInputElement).value), executionMode: 'prepare_and_review', dryRun: true } }); notice('Review-only campaign created'); await refresh(); } catch (error) { notice(message(error), true); } });
$('#campaigns').addEventListener('click', async (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button[data-campaign-action]'); if (!button) return; const id = button.dataset.campaignId!; try { await send({ type: button.dataset.campaignAction === 'run' ? 'runCampaign' : button.dataset.campaignAction === 'pause' ? 'pauseCampaign' : 'resumeCampaign', id }); notice(`Campaign ${button.dataset.campaignAction} complete`); await refresh(); } catch (error) { notice(message(error), true); } });
$('#answers').addEventListener('input', (event) => { const input = (event.target as HTMLElement).closest<HTMLTextAreaElement>('textarea[data-index]'); if (input) preparedAnswers[Number(input.dataset.index)].value = input.value; });
$('#fill').addEventListener('click', async () => { try { const answers = preparedAnswers.map((answer, index) => ({ ...answer, approved: !answer.confirmationRequired || ($(`#approve-${index}`) as HTMLInputElement).checked })); const result = await send({ type: 'fill-approved', answers, dryRun: dashboard.agentSettings.defaultDryRun }); notice(`${result.filled.length} fields ${result.dryRun ? 'previewed' : 'filled'} · ${result.skipped.length} skipped`); } catch (error) { notice(message(error), true); } });
$('#agent-settings').addEventListener('submit', async (event) => { event.preventDefault(); try { dashboard.agentSettings = await send({ type: 'saveAgentSettings', body: { activeProfileId: ($('#active-profile') as HTMLSelectElement).value, chatModel: ($('#chat-model') as HTMLSelectElement).value, answerModel: ($('#answer-model') as HTMLSelectElement).value, matchingModel: ($('#matching-model') as HTMLSelectElement).value, temperature: Number(($('#temperature') as HTMLInputElement).value), maximumAnswerLength: Number(($('#max-answer') as HTMLInputElement).value), confidenceThreshold: Number(($('#confidence') as HTMLInputElement).value), maximumConcurrentRuns: Number(($('#concurrency') as HTMLInputElement).value), defaultDryRun: ($('#default-dry-run') as HTMLInputElement).checked, browserHeadless: ($('#headless') as HTMLInputElement).checked } }); notice('Local agent configuration saved'); } catch (error) { notice(message(error), true); } });
$('#stop').addEventListener('click', async () => { await send({ type: 'emergencyStop' }); notice('Emergency stop engaged', true); await refresh(); }); $('#reset-stop').addEventListener('click', async () => { await send({ type: 'resetStop' }); notice('Emergency stop reset'); await refresh(); });

let wuzzufLoginPending = false;
$('#wuzzuf-login').addEventListener('click', async () => {
  if (wuzzufLoginPending) return;
  const button = $('#wuzzuf-login') as HTMLButtonElement; wuzzufLoginPending = true; button.disabled = true;
  try { const result = await wuzzuf('WUZZUF_OPEN_LOGIN', {}); notice(result.data.message); await refreshWuzzufAuth(); }
  catch (error) { notice(message(error), true); }
  finally { wuzzufLoginPending = false; button.disabled = false; }
});
$('#wuzzuf-pending').addEventListener('click', async () => { try { const result = await send({ type: 'wuzzufPendingApprovals' }); const approval = result.data?.[0]; if (!approval) return notice('No pending Wuzzuf approvals'); await decideWuzzufApproval(approval); } catch (error) { notice(message(error), true); } });
$('#wuzzuf-search').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await wuzzuf('WUZZUF_SEARCH_JOBS', { queries: splitInput(($('#wuzzuf-queries') as HTMLInputElement).value), locations: splitInput(($('#wuzzuf-locations') as HTMLInputElement).value), remote: ($('#wuzzuf-remote') as HTMLInputElement).checked, limit: 25 }); renderWuzzufJobs(result.data.jobs); } catch (error) { notice(message(error), true); } });
$('#wuzzuf-results').addEventListener('click', async (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('button[data-job]'); if (!button) return; try { const score = await wuzzuf('WUZZUF_SCORE_JOB', { jobId: button.dataset.job }); if (score.data.score < 80 && !confirm(`This job scored ${score.data.score}%. Prepare it anyway?`)) return; const prepared = await wuzzuf('WUZZUF_PREPARE_APPLICATION', { jobId: button.dataset.job, dryRun: true }); renderWuzzufReview(prepared.data); } catch (error) { notice(message(error), true); } });
$('#wuzzuf-fill').addEventListener('click', async () => { try { const result = await wuzzuf('WUZZUF_FILL_APPLICATION', { applicationId: wuzzufApplicationId, dryRun: dashboard.agentSettings.defaultDryRun !== false }); renderWuzzufReview(result.data); } catch (error) { notice(message(error), true); } });
$('#wuzzuf-approve').addEventListener('click', async () => { try { const result = await wuzzuf('WUZZUF_REQUEST_SUBMISSION_APPROVAL', { applicationId: wuzzufApplicationId }); await decideWuzzufApproval(result.data); } catch (error) { notice(message(error), true); } });
$('#wuzzuf-submit').addEventListener('click', async () => { try { if (!wuzzufApprovalRequestId || !wuzzufApprovalToken || !confirm('Submit this Wuzzuf application now? This cannot be undone.')) return; const result = await wuzzuf('WUZZUF_SUBMIT_APPLICATION', { applicationId: wuzzufApplicationId, approvalRequestId: wuzzufApprovalRequestId, approvalToken: wuzzufApprovalToken }); wuzzufApprovalRequestId = ''; wuzzufApprovalToken = ''; notice(result.data.submitted ? 'Application submitted' : 'Submission was not completed'); } catch (error) { notice(message(error), true); } });
$('#wuzzuf-cancel').addEventListener('click', async () => { try { await wuzzuf('WUZZUF_CANCEL_APPLICATION', { applicationId: wuzzufApplicationId }); wuzzufApprovalRequestId = ''; notice('Application cancelled'); } catch (error) { notice(message(error), true); } });

async function refresh(): Promise<boolean> { try { dashboard = await send({ type: 'dashboard' }); const resumes = await send({ type: 'registeredResumes' }); dashboard.resumes = (resumes.data ?? []).map((item: any) => ({ ...item, factCount: item.facts.length })); $('#health').textContent = dashboard.emergencyStop ? 'Stopped' : 'Connected'; $('#health').classList.toggle('online', !dashboard.emergencyStop); $('#pairing-card').classList.add('hidden'); renderProfiles(); renderRegisteredResumes(); renderOperations(); renderSettings(); await renderConnectors(); $('#wuzzuf-dry-run').textContent = dashboard.agentSettings.defaultDryRun !== false ? 'Dry run on' : 'Dry run off'; void refreshWuzzufAuth(); return true; } catch { $('#health').textContent = 'Pair required'; $('#pairing-card').classList.remove('hidden'); notice('Pair once to unlock local controls.'); return false; } }
async function loadModels() { try { const models = await send({ type: 'models' });['chat-model', 'answer-model', 'matching-model'].forEach((id) => { const select = $(`#${id}`) as HTMLSelectElement; select.innerHTML = models.map((model: any) => `<option value="${escapeHtml(model.id)}">${escapeHtml(model.name)}</option>`).join(''); }); renderSettings(); } catch (error) { notice(`Model discovery: ${message(error)}`, true); } }
function renderProfiles() { const active = dashboard.agentSettings.activeProfileId ?? dashboard.profiles[0]?.id ?? ''; ($('#active-profile') as HTMLSelectElement).innerHTML = dashboard.profiles.map((p: any) => `<option value="${p.id}" ${p.id === active ? 'selected' : ''}>${escapeHtml(p.name)}</option>`).join(''); $('#profiles').innerHTML = dashboard.profiles.map((p: any) => `<article><b>${escapeHtml(p.name)}</b>${p.cvVariants.map((resume: any) => `<label class="toggle"><input type="checkbox" data-profile="${p.id}" data-resume="${resume.id}" ${resume.approved ? 'checked' : ''}> Approved resume: ${escapeHtml(resume.sourceName)}</label>`).join('')}${p.facts.filter((f: any) => f.path !== 'source.rawText').map((f: any) => `<label>${escapeHtml(f.path)}<input data-profile="${p.id}" data-fact="${f.id}" value="${escapeHtml(String(f.value))}"></label>`).join('')}</article>`).join(''); }
function renderRegisteredResumes() { $('#registered-resumes').innerHTML = (dashboard.resumes ?? []).map((item: any) => `<article class="card"><b>${escapeHtml(item.source.displayName)}</b><p>${escapeHtml(item.source.mediaType)} · ${item.factCount} facts · ${item.source.approved ? 'Approved' : 'Review required'}</p><details><summary>Review extracted facts and provenance</summary>${(item.facts ?? []).map((fact: any) => `<p><b>${escapeHtml(fact.path)}</b>: ${escapeHtml(String(fact.value))}<br><small>${escapeHtml(fact.status)} · confidence ${Math.round(Number(fact.confidence) * 100)}%</small></p>`).join('')}</details><div class="action-row">${item.source.approved ? '' : `<button class="primary" data-resume-action="approve" data-resume-id="${item.source.id}">Approve these facts</button>`}<button class="danger" data-resume-action="remove" data-resume-id="${item.source.id}">Delete</button></div></article>`).join('') || '<p>No canonical resume sources imported.</p>'; }
async function renderConnectors() { const response = await send({ type: 'connectors' }); $('#connector-list').innerHTML = response.data.map((item: any) => `<label class="toggle"><input type="checkbox" data-connector="${item.policy.connectorId}" ${item.enabled ? 'checked' : ''} ${item.policy.connectorId === 'unsupported' ? 'disabled' : ''}> ${escapeHtml(item.policy.connectorId)} · ${escapeHtml(item.policy.capabilities.fill)} fill / ${escapeHtml(item.policy.capabilities.submit)} submit</label>`).join(''); }
function renderOperations() { $('#campaigns').innerHTML = (dashboard.campaigns ?? []).map((campaign: any) => `<article><b>${escapeHtml(campaign.name)}</b><p>${escapeHtml(campaign.state)} · ${escapeHtml(campaign.executionMode)}</p><div class="action-row"><button data-campaign-action="run" data-campaign-id="${campaign.id}">Run</button><button data-campaign-action="${campaign.state === 'paused' ? 'resume' : 'pause'}" data-campaign-id="${campaign.id}">${campaign.state === 'paused' ? 'Resume' : 'Pause'}</button></div></article>`).join('') || '<p>No campaigns.</p>'; $('#queue-status').textContent = Object.entries(dashboard.queue ?? {}).map(([state, count]) => `${state}: ${count}`).join(' · ') || 'Queue empty'; $('#history').innerHTML = (dashboard.timeline ?? []).slice(0, 20).map((item: any) => `<p><small>${escapeHtml(item.at)}</small> ${escapeHtml(item.type)}</p>`).join('') || '<p>No audit events.</p>'; }
function renderTailoring() { $('#tailoring-review').classList.remove('hidden'); const review = currentTailoring.review; const pdf = currentTailoring.artifacts?.pdf; $('#tailoring-review-content').innerHTML = `<p><b>${currentTailoring.validation.valid ? 'Fact validation passed' : 'Validation blocked'}</b></p><p>Matched: ${escapeHtml(review.matchedKeywords.join(', ') || 'none')}</p><p>Missing (not invented): ${escapeHtml(review.missingRequirements.join(', ') || 'none')}</p>${review.changes.map((change: any) => `<article><b>${escapeHtml(change.section)}</b><pre>${escapeHtml(change.after ?? '')}</pre></article>`).join('')}${pdf ? `<p>Private ATS-safe PDF generated · ${Math.ceil(pdf.size / 1024)} KB · SHA-256 ${escapeHtml(pdf.sha256.slice(0, 12))}…</p><button data-preview-pdf="${pdf.id}" class="ghost">Preview private PDF</button>` : '<p>PDF rendering is pending or the standalone worker is unavailable.</p>'}<p>${currentTailoring.tailoredResume.approved ? 'Approved' : 'Awaiting approval'}</p>`; }
function renderSettings() { const s = dashboard.agentSettings; const values: Record<string, any> = { 'chat-model': s.chatModel, 'answer-model': s.answerModel, 'matching-model': s.matchingModel, temperature: s.temperature, 'max-answer': s.maximumAnswerLength, confidence: s.confidenceThreshold, concurrency: s.maximumConcurrentRuns }; for (const [id, value] of Object.entries(values)) { const el = $(`#${id}`) as HTMLInputElement | HTMLSelectElement; if (value !== undefined) el.value = String(value); } ($('#default-dry-run') as HTMLInputElement).checked = s.defaultDryRun !== false; ($('#headless') as HTMLInputElement).checked = s.browserHeadless !== false; }
function renderAnswers() { $('#approval-panel').classList.remove('hidden'); $('#answers').innerHTML = preparedAnswers.map((a, i) => `<div class="answer"><b>${escapeHtml(a.label)}</b><textarea data-index="${i}">${escapeHtml(a.value || '')}</textarea>${a.confirmationRequired ? `<label><input id="approve-${i}" type="checkbox"> Approve this answer</label><small>${escapeHtml(a.reason || 'Confirmation required')}</small>` : '<small>Grounded in verified resume facts</small>'}</div>`).join(''); }
async function wuzzuf(action: string, body: Record<string, unknown>) { return send({ type: 'wuzzuf', action, body }); }
async function decideWuzzufApproval(approval: any) { const answers = approval.answers.map((answer: any) => `${answer.label}: ${answer.value || '(blank)'}`).join('\n'); const summary = `${approval.job.title} at ${approval.job.employer}\nResume: ${approval.resume?.sourceName ?? 'none'}\n\nFinal answers:\n${answers || '(none)'}\n\nExpires: ${approval.expiresAt}\n\nApprove this exact application for one submission?`; const approved = confirm(summary); const decision = await send({ type: 'wuzzufApprovalDecision', approvalRequestId: approval.id, approved }); if (!approved) return notice('Submission approval rejected'); wuzzufApplicationId = approval.applicationId; wuzzufApprovalRequestId = approval.id; wuzzufApprovalToken = decision.data.approvalToken; notice(`Approved until ${approval.expiresAt}`); }
async function refreshWuzzufAuth() { try { const result = await wuzzuf('WUZZUF_GET_AUTH_STATUS', {}); $('#wuzzuf-auth').textContent = result.data.authenticated ? 'Connected' : result.data.code; } catch (error) { $('#wuzzuf-auth').textContent = message(error); } }
function renderWuzzufJobs(jobs: any[]) { $('#wuzzuf-results').innerHTML = jobs.map((job) => `<article class="job-card"><b>${escapeHtml(job.title)}</b><span>${escapeHtml(job.employer)}</span><small>${escapeHtml(job.location)}${job.remote ? ' · Remote' : ''}</small><button class="primary" data-job="${escapeHtml(job.id)}">Score and prepare</button></article>`).join(''); }
function renderWuzzufReview(review: any) { wuzzufApplicationId = review.id; wuzzufApprovalRequestId = ''; $('#wuzzuf-review').classList.remove('hidden'); $('#wuzzuf-review-content').innerHTML = `<h3>${escapeHtml(review.job.title)}</h3><p>State: ${escapeHtml(review.state)} · ${review.dryRun ? 'Dry run' : 'Live fill'}</p><p>${review.filledFields.length} filled · ${review.skippedFields.length} skipped · ${review.validationErrors.length} errors</p><p>${escapeHtml(review.skippedFields.join(', '))}</p><p>Submission ${review.submissionAllowed ? 'allowed after approval' : 'blocked'}</p>`; }
function splitInput(value: string) { return value.split(',').map((item) => item.trim()).filter(Boolean); }
function addBubble(role: 'user' | 'assistant', text: string, stream?: string) { const div = document.createElement('div'); div.className = `bubble ${role}`; if (stream) div.dataset.stream = stream; const name = document.createElement('b'); name.textContent = role === 'assistant' ? 'OpenClaw' : 'You'; const p = document.createElement('p'); p.textContent = text; div.append(name, p); $('#messages').append(div); $('#messages').scrollTop = $('#messages').scrollHeight; }
function finishStream(error?: string) { const bubble = document.querySelector<HTMLElement>('.bubble[data-stream="streaming"]'); if (!bubble) return; delete bubble.dataset.stream; if (error) bubble.querySelector('p')!.textContent = error; }
function arrayBufferToBase64(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); let binary = ''; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(binary); }
function escapeHtml(value: string) { const span = document.createElement('span'); span.textContent = value; return span.innerHTML; } function message(error: unknown) { return error instanceof Error ? error.message : String(error); }
void refresh().then((connected) => { if (connected) return loadModels(); });
