import { Type } from 'typebox';
import { defineToolPlugin } from 'openclaw/plugin-sdk/tool-plugin';
import { failure, request, type PluginConfig } from './client.ts';

const empty = Type.Object({}, { additionalProperties: false }); const id = Type.String({ minLength: 1, maxLength: 100 }); const idempotencyKey = Type.Optional(Type.String({ minLength: 1, maxLength: 128 }));
const jobRef = Type.Object({ jobId: Type.Optional(id), url: Type.Optional(Type.String({ maxLength: 4000 })), profileId: Type.Optional(id) }, { additionalProperties: false });
const applicationRef = Type.Object({ applicationId: id }, { additionalProperties: false });
const configSchema = Type.Object({ bridgeUrl: Type.Optional(Type.String({ default: 'http://127.0.0.1:18790' })), toolToken: Type.Optional(Type.String({ minLength: 32, description: 'Distinct scoped token for the local daemon. Tools fail closed until configured.' })), timeoutMs: Type.Optional(Type.Integer({ minimum: 1000, maximum: 300000, default: 60000 })), enableSubmissionTool: Type.Optional(Type.Boolean({ default: false, description: 'Explicitly enable the submission tool. Human approval is still mandatory.' })) }, { additionalProperties: false });
type ToolFactory = any;
const remote = (tool: ToolFactory, name: string, description: string, path: string, method: 'GET' | 'POST', parameters: unknown, options: { preload?: boolean; transform?: (value: any, params: Record<string, unknown>) => unknown } = {}) => tool({ name, description, parameters, ...(options.preload === false ? { preload: false } : {}), execute: async (params: Record<string, unknown>, config: PluginConfig) => { const value = await request(config, interpolate(path, params), method, method === 'POST' ? params : undefined); return options.transform ? options.transform(value, params) : value; } });
const legacy = (tool: ToolFactory, name: string, action: string, description: string, parameters: unknown, preload = true) => remote(tool, name, `[Deprecated compatibility alias] ${description}`, `/v1/wuzzuf/tools/${action}`, 'POST', parameters, { preload });
const dashboard = (tool: ToolFactory, name: string, description: string, parameters: unknown, select: (data: any, params: Record<string, unknown>) => unknown) => remote(tool, name, description, '/v1/dashboard', 'GET', parameters, { transform: (value, params) => value?.error ? value : { ok: true, data: select(value, params), correlationId: crypto.randomUUID() } });
const unavailable = (tool: ToolFactory, name: string, description: string, parameters: unknown, next: string) => tool({ name, description, parameters, preload: false, execute: async () => failure('AUTOMATION_NOT_PERMITTED', 'This operation requires the trusted local CLI or extension UI in this release.', false, next) });

export const runtimeRegisteredToolNames = [
  'job_automation_status', 'job_automation_doctor', 'job_automation_emergency_stop', 'job_automation_clear_emergency_stop', 'job_automation_get_audit_events',
  'jobs_get_connector_capabilities', 'jobs_get_connection_status', 'jobs_open_login', 'candidate_profile_list', 'candidate_profile_get', 'candidate_profile_update_preferences', 'candidate_profile_list_resumes', 'candidate_profile_import_resume', 'candidate_profile_select_resume', 'candidate_profile_approve_resume', 'candidate_profile_get_resume_variants',
  'jobs_search', 'jobs_import_current_page', 'jobs_get_details', 'jobs_score', 'jobs_explain_match', 'jobs_shortlist', 'jobs_reject', 'jobs_tailor_resume', 'jobs_get_tailored_resume_review', 'jobs_approve_tailored_resume', 'jobs_get_resume_artifact',
  'jobs_prepare_application', 'jobs_get_application_review', 'jobs_set_application_answer', 'jobs_fill_application', 'jobs_validate_application', 'jobs_request_submission_approval', 'jobs_submit_application', 'jobs_cancel_application', 'jobs_get_application_status',
  'campaign_create', 'campaign_preview', 'campaign_update', 'campaign_run', 'campaign_pause', 'campaign_resume', 'campaign_cancel', 'campaign_get', 'campaign_list', 'campaign_get_activity',
  'wuzzuf_create_connection', 'wuzzuf_open_login', 'wuzzuf_get_auth_status', 'wuzzuf_verify_connection', 'wuzzuf_disconnect', 'wuzzuf_search_jobs', 'wuzzuf_get_job_details', 'wuzzuf_score_job', 'wuzzuf_prepare_application', 'wuzzuf_fill_application', 'wuzzuf_get_application_review', 'wuzzuf_request_submission_approval', 'wuzzuf_submit_application', 'wuzzuf_get_application_status', 'wuzzuf_cancel_application'
] as const;

export default defineToolPlugin({
  id: 'extension-jobs', name: 'Extension Jobs', description: 'Local-first review-gated job search, resume, application, and campaign tools.', configSchema,
  tools: (tool: ToolFactory) => [
    remote(tool, 'job_automation_status', 'Read local daemon, queue, browser, and emergency-stop status. Read-only and safe to retry.', '/health', 'GET', empty),
    remote(tool, 'job_automation_doctor', 'Run local readiness diagnostics. Read-only and safe to retry.', '/health/ready', 'GET', empty),
    remote(tool, 'job_automation_emergency_stop', 'Immediately stop trusted automation. Mutates safety state; use only when requested or unsafe activity is suspected.', '/v1/emergency-stop', 'POST', empty),
    remote(tool, 'job_automation_clear_emergency_stop', 'Clear an emergency stop only after explicit user confirmation. Mutates safety state.', '/v1/emergency-stop/reset', 'POST', empty, { preload: false }),
    dashboard(tool, 'job_automation_get_audit_events', 'Read sanitized local audit events. Read-only and safe to retry.', Type.Object({ limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 200 })) }, { additionalProperties: false }), (data, params) => ({ events: data.timeline.slice(0, Number(params.limit ?? 50)) })),
    remote(tool, 'jobs_get_connector_capabilities', 'Inspect fail-closed connector policy before search, fill, or submit. Read-only and safe to retry.', '/v1/connectors', 'GET', Type.Object({ connectorId: Type.Optional(Type.String({ maxLength: 100 })) }, { additionalProperties: false })),
    remote(tool, 'jobs_get_connection_status', 'Read connector authentication state.', '/v1/connectors/wuzzuf/connection', 'GET', empty), remote(tool, 'jobs_open_login', 'Open the managed connector login tab for user action.', '/v1/connectors/wuzzuf/login', 'POST', empty),
    dashboard(tool, 'candidate_profile_list', 'List sanitized local profiles. Raw resume content and paths are never returned.', empty, (data) => ({ profiles: data.profiles.map((profile: any) => ({ id: profile.id, name: profile.name })) })),
    dashboard(tool, 'candidate_profile_get', 'Read sanitized verified profile facts. Read-only.', Type.Object({ profileId: id }, { additionalProperties: false }), (data, params) => ({ profile: data.profiles.find((profile: any) => profile.id === params.profileId) ?? null })),
    unavailable(tool, 'candidate_profile_update_preferences', 'Update candidate preferences after explicit user confirmation.', Type.Object({ profileId: id, preferences: Type.Record(Type.String(), Type.Union([Type.String(), Type.Number(), Type.Boolean()])), idempotencyKey }, { additionalProperties: false }), 'extension-jobs resume inspect'),
    dashboard(tool, 'candidate_profile_list_resumes', 'List approved resume metadata without bytes or local paths.', Type.Object({ profileId: id }, { additionalProperties: false }), (data, params) => ({ resumes: data.profiles.find((profile: any) => profile.id === params.profileId)?.cvVariants ?? [] })),
    unavailable(tool, 'candidate_profile_import_resume', 'Initiate resume import. Paths may only be selected in the trusted local CLI or extension.', empty, 'extension-jobs resume add'),
    unavailable(tool, 'candidate_profile_select_resume', 'Select an imported resume for a profile.', Type.Object({ profileId: id, resumeId: id, idempotencyKey }, { additionalProperties: false }), 'extension-jobs resume list'),
    unavailable(tool, 'candidate_profile_approve_resume', 'Approve a resume only through a trusted local interface.', Type.Object({ profileId: id, resumeId: id, idempotencyKey }, { additionalProperties: false }), 'extension-jobs resume approve'),
    dashboard(tool, 'candidate_profile_get_resume_variants', 'List resume variants and approval state without bytes.', Type.Object({ profileId: id }, { additionalProperties: false }), (data, params) => ({ resumes: data.profiles.find((profile: any) => profile.id === params.profileId)?.cvVariants ?? [] })),
    remote(tool, 'jobs_search', 'Search enabled sources and return normalized jobs. Read-only search; safe to retry.', '/v1/jobs/search', 'POST', Type.Object({ queries: Type.Array(Type.String({ maxLength: 200 }), { minItems: 1, maxItems: 10 }), locations: Type.Array(Type.String({ maxLength: 200 }), { minItems: 1, maxItems: 10 }), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100 })) }, { additionalProperties: false })),
    remote(tool, 'jobs_import_current_page', 'Import allowlisted structured metadata from the user-opened page. Never accepts full HTML.', '/v1/jobs/import-current-page', 'POST', Type.Object({ url: Type.String({ maxLength: 4000 }), title: Type.Optional(Type.String({ maxLength: 500 })), jsonLd: Type.Optional(Type.Unknown()), safeMetadata: Type.Optional(Type.Record(Type.String(), Type.Union([Type.String(), Type.Array(Type.String()), Type.Boolean()]))) }, { additionalProperties: false })),
    remote(tool, 'jobs_get_details', 'Read normalized job details from the daemon system of record.', '/v1/jobs/details', 'POST', Type.Object({ jobId: Type.Optional(id), url: Type.Optional(Type.String({ maxLength: 4000 })) }, { additionalProperties: false })), remote(tool, 'jobs_score', 'Score a job against verified profile facts.', '/v1/jobs/score', 'POST', Type.Object({ jobId: id, profileId: Type.Optional(id) }, { additionalProperties: false })), remote(tool, 'jobs_explain_match', 'Explain a deterministic job match score.', '/v1/jobs/score', 'POST', Type.Object({ jobId: id, profileId: Type.Optional(id) }, { additionalProperties: false })),
    unavailable(tool, 'jobs_shortlist', 'Shortlist a normalized job.', Type.Object({ jobId: id, idempotencyKey }, { additionalProperties: false }), 'jobs_get_details'), unavailable(tool, 'jobs_reject', 'Reject a normalized job with an audited reason.', Type.Object({ jobId: id, reason: Type.Optional(Type.String({ maxLength: 1000 })), idempotencyKey }, { additionalProperties: false }), 'jobs_get_details'),
    remote(tool, 'jobs_tailor_resume', 'Generate a verified-fact-only resume tailoring review. Never submits.', '/v1/jobs/{jobId}/tailor-resume', 'POST', Type.Object({ jobId: id, resumeId: id, idempotencyKey }, { additionalProperties: false }), { preload: false }), remote(tool, 'jobs_get_tailored_resume_review', 'Read a tailoring diff, matched keywords, missing requirements, facts, and warnings.', '/v1/tailored-resumes/{tailoredResumeId}', 'GET', Type.Object({ tailoredResumeId: id }, { additionalProperties: false })), unavailable(tool, 'jobs_approve_tailored_resume', 'Approve a factual tailoring result through trusted local review.', Type.Object({ tailoredResumeId: id, idempotencyKey }, { additionalProperties: false }), 'extension-jobs resume approve'), remote(tool, 'jobs_get_resume_artifact', 'Read sanitized resume artifact metadata. Resume bytes remain local.', '/v1/artifacts/{artifactId}', 'GET', Type.Object({ artifactId: id }, { additionalProperties: false })),
    remote(tool, 'jobs_prepare_application', 'Prepare and inspect an application. Never submits.', '/v1/applications/prepare', 'POST', Type.Intersect([jobRef, Type.Object({ dryRun: Type.Optional(Type.Boolean({ default: true })), idempotencyKey })])), remote(tool, 'jobs_get_application_review', 'Read the final review and blockers.', '/v1/applications/review', 'POST', applicationRef), unavailable(tool, 'jobs_set_application_answer', 'Set one reviewed answer with supporting facts.', Type.Object({ applicationId: id, fieldId: id, value: Type.String({ maxLength: 5000 }), supportingFactIds: Type.Array(id, { maxItems: 100 }), idempotencyKey }, { additionalProperties: false }), 'jobs_get_application_review'), remote(tool, 'jobs_fill_application', 'Fill reviewed fields and stop before submission.', '/v1/applications/fill', 'POST', Type.Object({ applicationId: id, dryRun: Type.Optional(Type.Boolean({ default: true })), idempotencyKey }, { additionalProperties: false })), unavailable(tool, 'jobs_validate_application', 'Validate current form values and fingerprints without submitting.', applicationRef, 'jobs_get_application_review'), remote(tool, 'jobs_request_submission_approval', 'Request trusted-UI approval. The agent cannot approve.', '/v1/applications/request-submission-approval', 'POST', Type.Object({ applicationId: id, ttlSeconds: Type.Optional(Type.Integer({ minimum: 30, maximum: 300 })), idempotencyKey }, { additionalProperties: false })),
    tool({ name: 'jobs_submit_application', description: 'Submit exactly once only after trusted-UI approval. Disabled unless enableSubmissionTool is true; never safe to retry after uncertainty.', parameters: Type.Object({ applicationId: id, approvalRequestId: id, approvalToken: Type.String({ minLength: 32, maxLength: 256 }), idempotencyKey }, { additionalProperties: false }), preload: false, execute: (params: Record<string, unknown>, config: PluginConfig) => config.enableSubmissionTool ? request(config, '/v1/applications/submit', 'POST', params) : failure('AUTOMATION_NOT_PERMITTED', 'Submission tool is disabled in plugin configuration.', false, 'jobs_get_application_review') }),
    remote(tool, 'jobs_cancel_application', 'Cancel active local application work.', '/v1/applications/cancel', 'POST', Type.Object({ applicationId: id, idempotencyKey }, { additionalProperties: false })), remote(tool, 'jobs_get_application_status', 'Read persistent application status.', '/v1/applications/status', 'POST', applicationRef),
    remote(tool, 'campaign_create', 'Create a durable review-gated campaign. Scheduling never bypasses approval.', '/v1/campaigns', 'POST', Type.Object({ name: Type.String({ maxLength: 100 }), profileId: id, searchQueries: Type.Array(Type.String(), { minItems: 1, maxItems: 10 }), locations: Type.Array(Type.String(), { minItems: 1, maxItems: 10 }), minimumMatchScore: Type.Optional(Type.Number({ minimum: 0, maximum: 100 })), maxApplicationsPerRun: Type.Optional(Type.Integer({ minimum: 1, maximum: 100 })), maxApplicationsPerDay: Type.Optional(Type.Integer({ minimum: 1, maximum: 200 })), dryRun: Type.Optional(Type.Boolean({ default: true })), idempotencyKey }, { additionalProperties: false })),
    dashboard(tool, 'campaign_preview', 'Preview durable campaigns without running them.', Type.Object({ campaignId: id }, { additionalProperties: false }), (data, params) => ({ campaign: data.campaigns.find((campaign: any) => campaign.id === params.campaignId) ?? null })), unavailable(tool, 'campaign_update', 'Update campaign policy without bypassing approval.', Type.Object({ campaignId: id, patch: Type.Record(Type.String(), Type.Unknown()), idempotencyKey }, { additionalProperties: false }), 'campaign_get'),
    remote(tool, 'campaign_run', 'Run one campaign under daemon limits and approval policy.', '/v1/campaigns/{campaignId}/run', 'POST', Type.Object({ campaignId: id, idempotencyKey }, { additionalProperties: false })), remote(tool, 'campaign_pause', 'Pause future campaign work.', '/v1/campaigns/{campaignId}/pause', 'POST', Type.Object({ campaignId: id, idempotencyKey }, { additionalProperties: false })), remote(tool, 'campaign_resume', 'Resume a paused campaign without changing approval policy.', '/v1/campaigns/{campaignId}/resume', 'POST', Type.Object({ campaignId: id, idempotencyKey }, { additionalProperties: false })), unavailable(tool, 'campaign_cancel', 'Cancel a campaign and pending work.', Type.Object({ campaignId: id, idempotencyKey }, { additionalProperties: false }), 'campaign_pause'), dashboard(tool, 'campaign_get', 'Read one durable campaign.', Type.Object({ campaignId: id }, { additionalProperties: false }), (data, params) => ({ campaign: data.campaigns.find((campaign: any) => campaign.id === params.campaignId) ?? null })), dashboard(tool, 'campaign_list', 'List durable campaigns.', empty, (data) => ({ campaigns: data.campaigns })), dashboard(tool, 'campaign_get_activity', 'Read sanitized campaign audit activity.', Type.Object({ campaignId: id }, { additionalProperties: false }), (data, params) => ({ events: data.timeline.filter((event: any) => event.correlationId === params.campaignId || event.detail?.campaignId === params.campaignId) })),
    legacy(tool, 'wuzzuf_create_connection', 'WUZZUF_CREATE_CONNECTION', 'Create a Wuzzuf connection.', empty), legacy(tool, 'wuzzuf_open_login', 'WUZZUF_OPEN_LOGIN', 'Open Wuzzuf login.', empty), legacy(tool, 'wuzzuf_get_auth_status', 'WUZZUF_GET_AUTH_STATUS', 'Read Wuzzuf auth state.', empty), legacy(tool, 'wuzzuf_verify_connection', 'WUZZUF_VERIFY_CONNECTION', 'Verify Wuzzuf auth.', empty), legacy(tool, 'wuzzuf_disconnect', 'WUZZUF_DISCONNECT', 'Disconnect Wuzzuf automation.', empty), legacy(tool, 'wuzzuf_search_jobs', 'WUZZUF_SEARCH_JOBS', 'Search Wuzzuf.', Type.Object({ queries: Type.Array(Type.String(), { minItems: 1, maxItems: 10 }), locations: Type.Array(Type.String(), { minItems: 1, maxItems: 10 }), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100 })) }, { additionalProperties: false })), legacy(tool, 'wuzzuf_get_job_details', 'WUZZUF_GET_JOB_DETAILS', 'Read Wuzzuf job details.', Type.Object({ url: Type.String({ maxLength: 4000 }) }, { additionalProperties: false })), legacy(tool, 'wuzzuf_score_job', 'WUZZUF_SCORE_JOB', 'Score Wuzzuf job.', jobRef), legacy(tool, 'wuzzuf_prepare_application', 'WUZZUF_PREPARE_APPLICATION', 'Prepare Wuzzuf application.', Type.Intersect([jobRef, Type.Object({ dryRun: Type.Optional(Type.Boolean()), idempotencyKey })])), legacy(tool, 'wuzzuf_fill_application', 'WUZZUF_FILL_APPLICATION', 'Fill Wuzzuf application.', Type.Object({ applicationId: id, dryRun: Type.Optional(Type.Boolean()), idempotencyKey }, { additionalProperties: false })), legacy(tool, 'wuzzuf_get_application_review', 'WUZZUF_GET_APPLICATION_REVIEW', 'Review Wuzzuf application.', applicationRef), legacy(tool, 'wuzzuf_request_submission_approval', 'WUZZUF_REQUEST_SUBMISSION_APPROVAL', 'Request Wuzzuf submission approval.', Type.Object({ applicationId: id, idempotencyKey }, { additionalProperties: false })), legacy(tool, 'wuzzuf_submit_application', 'WUZZUF_SUBMIT_APPLICATION', 'Submit approved Wuzzuf application.', Type.Object({ applicationId: id, approvalRequestId: id, approvalToken: Type.String({ minLength: 32 }), idempotencyKey }, { additionalProperties: false }), false), legacy(tool, 'wuzzuf_get_application_status', 'WUZZUF_GET_APPLICATION_STATUS', 'Read Wuzzuf application status.', applicationRef), legacy(tool, 'wuzzuf_cancel_application', 'WUZZUF_CANCEL_APPLICATION', 'Cancel Wuzzuf application.', Type.Object({ applicationId: id, idempotencyKey }, { additionalProperties: false }))
  ]
});
function interpolate(path: string, params: Record<string, unknown>): string { return path.replace(/\{([a-zA-Z]+)\}/g, (_match, key: string) => encodeURIComponent(String(params[key] ?? ''))); }
