#!/usr/bin/env -S node --experimental-strip-types
import { randomBytes } from 'node:crypto';
import { chmodSync, closeSync, existsSync, mkdirSync, openSync, readFileSync, realpathSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { ArtifactStore } from '../../../packages/artifact-store/src/index.ts';
import { ResumeVault } from '../../../packages/resume-importers/src/index.ts';
import { defaultSitePolicyRegistry } from '../../../packages/site-policy-registry/src/index.ts';
import { Store } from '../../orchestrator/src/store.ts';

// An installed CLI manages the checkout in the caller's current directory. The
// explicit override is useful for launch agents and other non-interactive use.
const root = resolve(process.env.EXTENSION_JOBS_HOME ?? process.cwd()); const dataDir = resolve(process.env.EXTENSION_JOBS_DATA_DIR ?? resolve(root, 'data')); const pidFile = resolve(dataDir, 'daemon.pid');

const [command = 'help', ...args] = process.argv.slice(2);
try {
  if (command === 'help' || command === '--help' || command === '-h') help();
  else if (command === 'init') init();
  else if (command === 'doctor') await doctor();
  else if (command === 'start') start();
  else if (command === 'stop') stop();
  else if (command === 'status') await status();
  else if (command === 'resume') await resume(args);
  else if (command === 'connectors') connectors(args);
  else if (command === 'openclaw') openclaw(args);
  else if (command === 'extension') extension(args);
  else throw new CliError(`Unknown command: ${command}`);
} catch (error) { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; }

function help() { process.stdout.write(`Extension Jobs\n\nCommands:\n  init | doctor | start | stop | status\n  resume add <path> | list | inspect <id> | approve <id> | remove <id>\n  connectors list | enable <id> | disable <id> | status\n  openclaw install | verify\n  extension build\n`); }
function init() { ensureData(); const environment = resolve(root, '.env'); const created = !existsSync(environment); if (created) { const content = [`DATA_DIR=${dataDir}`, 'EXTENSION_ID=replace-with-extension-id', `PAIRING_CODE=${token(24)}`, `OPENCLAW_JOB_TOOL_TOKEN=${token(32)}`, `COMPOSIO_JOBS_TOOL_TOKEN=${token(32)}`, `WORKER_TOOL_TOKEN=${token(32)}`, 'JOB_SOURCE_MODE=development', ''].join('\n'); writeFileSync(environment, content, { mode: 0o600 }); chmodSync(environment, 0o600); } const store = openStore(); store.close(); process.stdout.write(`Initialized private local data and migrated the daemon database at ${dataDir}. ${created ? 'Secret values were written to .env and were not printed.' : 'Existing .env was preserved.'}\n`); }
async function doctor() { const major = Number(process.versions.node.split('.')[0]); const checks = [{ name: 'Node.js 24+', ok: major >= 24 }, { name: 'Private data directory', ok: existsSync(dataDir) && (statSync(dataDir).mode & 0o077) === 0 }, { name: 'OpenClaw CLI', ok: spawnSync('openclaw', ['--version'], { stdio: 'ignore' }).status === 0 }, { name: 'Extension manifest', ok: existsSync(resolve(root, 'apps/extension/manifest.json')) }, { name: 'Generic OpenClaw plugin', ok: existsSync(resolve(root, 'apps/openclaw-jobs/openclaw.plugin.json')) }]; for (const check of checks) process.stdout.write(`${check.ok ? 'PASS' : 'FAIL'} ${check.name}\n`); try { const response = await fetch('http://127.0.0.1:18790/health/live', { signal: AbortSignal.timeout(1_000) }); process.stdout.write(`${response.ok ? 'PASS' : 'WARN'} Local daemon\n`); } catch { process.stdout.write('WARN Local daemon is not running\n'); } if (checks.some((check) => !check.ok)) process.exitCode = 1; }
function start() { ensureData(); if (runningPid()) throw new CliError('Extension Jobs is already running'); const log = resolve(dataDir, 'daemon.log'); const output = openSync(log, 'a', 0o600); const child = spawn(process.execPath, ['--env-file-if-exists=.env', '--experimental-strip-types', 'scripts/dev.ts'], { cwd: root, detached: true, stdio: ['ignore', output, output], env: process.env }); closeSync(output); child.unref(); if (!child.pid) throw new CliError('Daemon failed to start'); writeFileSync(pidFile, `${child.pid}\n`, { mode: 0o600 }); process.stdout.write(`Started Extension Jobs orchestrator and standalone worker (PID ${child.pid}).\n`); }
function stop() { const pid = runningPid(); if (!pid) throw new CliError('Extension Jobs daemon is not running'); process.kill(pid, 'SIGTERM'); unlinkSync(pidFile); process.stdout.write('Stopped Extension Jobs daemon.\n'); }
async function status() { try { const response = await fetch('http://127.0.0.1:18790/health', { signal: AbortSignal.timeout(1_500) }); const value = await response.json() as unknown; process.stdout.write(`${JSON.stringify(value, null, 2)}\n`); if (!response.ok) process.exitCode = 1; } catch { process.stdout.write(JSON.stringify({ ok: false, running: Boolean(runningPid()) }, null, 2) + '\n'); process.exitCode = 1; } }
async function resume(args: string[]) { ensureData(); const action = args[0]; const store = openStore(); try { if (action === 'add') { const selected = args[1]; if (!selected) throw new CliError('Usage: extension-jobs resume add <path>'); const real = realpathSync(selected); const imported = await new ResumeVault(new ArtifactStore(resolve(dataDir, 'vault'))).importPath('default', real); try { store.saveRegisteredResume(imported.source, imported.sourceArtifactId, imported.profile); } catch (error) { new ArtifactStore(resolve(dataDir, 'vault')).remove(imported.sourceArtifactId); throw error; } process.stdout.write(`${JSON.stringify({ id: imported.source.id, displayName: imported.source.displayName, mediaType: imported.source.mediaType, size: imported.source.size, factCount: imported.profile.facts.length, approved: false }, null, 2)}\n`); return; } if (action === 'list') { process.stdout.write(`${JSON.stringify(store.listRegisteredResumes().map((record) => record.source), null, 2)}\n`); return; } const id = args[1]; if (!id) throw new CliError(`Usage: extension-jobs resume ${action ?? '<action>'} <id>`); const record = store.getRegisteredResume(id); if (!record) throw new CliError('Resume not found'); if (action === 'inspect') { process.stdout.write(`${JSON.stringify({ source: record.source, facts: record.profile.facts }, null, 2)}\n`); return; } if (action === 'approve') { if (!store.approveRegisteredResume(id)) throw new CliError('Resume not found'); process.stdout.write(`Approved resume ${id} in the daemon database.\n`); return; } if (action === 'remove') { const artifactId = store.removeRegisteredResume(id); if (!artifactId) throw new CliError('Resume not found'); new ArtifactStore(resolve(dataDir, 'vault')).remove(artifactId); process.stdout.write(`Removed resume ${id}, its daemon metadata, and its private vault artifact.\n`); return; } throw new CliError('Unknown resume command'); } finally { store.close(); } }
function connectors(args: string[]) { ensureData(); const action = args[0] ?? 'list'; const store = openStore(); try { const saved = new Map(store.connectorSettings().map((setting) => [setting.connectorId, setting.enabled])); if (action === 'list' || action === 'status') { const list = defaultSitePolicyRegistry.list().map((policy) => ({ id: policy.connectorId, enabled: saved.get(policy.connectorId) ?? policy.enabledByDefault, version: policy.version, capabilities: policy.capabilities, notes: policy.notes })); process.stdout.write(`${JSON.stringify(list, null, 2)}\n`); return; } const id = args[1]; const policy = defaultSitePolicyRegistry.list().find((item) => item.connectorId === id); if (!id || !policy || id === 'unsupported') throw new CliError('Unknown connector'); if (!['enable', 'disable'].includes(action)) throw new CliError('Use connectors enable <id> or disable <id>'); store.setConnectorEnabled(policy.connectorId, action === 'enable', policy.version); process.stdout.write(`${action === 'enable' ? 'Enabled' : 'Disabled'} ${id} in the daemon database. Restart the daemon to apply connector configuration.\n`); } finally { store.close(); } }
function openclaw(args: string[]) { const action = args[0]; if (action === 'install') run('openclaw', ['plugins', 'install', '--link', resolve(root, 'apps/openclaw-jobs')]); else if (action === 'verify') { run('npm', ['run', '--workspace', '@extension-jobs/openclaw-jobs', 'build']); run('openclaw', ['plugins', 'validate', '--root', resolve(root, 'apps/openclaw-jobs'), '--entry', './dist/index.js']); } else throw new CliError('Use openclaw install or verify'); }
function extension(args: string[]) { if (args[0] !== 'build') throw new CliError('Use extension build'); run('npx', ['tsc', '-p', resolve(root, 'apps/extension/tsconfig.json')]); process.stdout.write(`Built unpacked extension at ${resolve(root, 'apps/extension')}.\n`); }
function run(binary: string, commandArgs: string[]) { const result = spawnSync(binary, commandArgs, { cwd: root, stdio: 'inherit' }); if (result.status !== 0) throw new CliError(`${binary} command failed`); }
function ensureData() { mkdirSync(dataDir, { recursive: true, mode: 0o700 }); chmodSync(dataDir, 0o700); mkdirSync(resolve(dataDir, 'vault'), { recursive: true, mode: 0o700 }); }
function openStore(): Store { return new Store(resolve(dataDir, 'jobs.sqlite')); }
function runningPid(): number | undefined { try { const pid = Number(readFileSync(pidFile, 'utf8').trim()); if (!Number.isInteger(pid) || pid < 2) return undefined; process.kill(pid, 0); return pid; } catch { return undefined; } }
function token(bytes: number): string { return randomBytes(bytes).toString('base64url'); }
class CliError extends Error {}
