import { randomUUID } from 'node:crypto';
import type { JobCampaign, Schedule } from '../../../packages/shared/src/domain.ts';
import type { OrchestratorService } from './service.ts';

export class CampaignScheduler {
  private timer: NodeJS.Timeout | undefined; private ticking = false;
  private readonly service: OrchestratorService; private readonly intervalMs: number;
  constructor(service: OrchestratorService, intervalMs = 30_000) { this.service = service; this.intervalMs = intervalMs; }
  start(): void { if (this.timer) return; this.timer = setInterval(() => void this.tick(), this.intervalMs); this.timer.unref(); void this.tick(); }
  stop(): void { if (this.timer) clearInterval(this.timer); this.timer = undefined; }
  async tick(now = new Date()): Promise<void> { if (this.ticking || this.service.emergencyStop.active) return; this.ticking = true; try { for (const campaign of this.service.store.listCampaigns()) { if (campaign.state !== 'enabled' || !campaign.schedule || !isScheduleDue(campaign.schedule, now, this.service.store.latestCampaignRunAt(campaign.id))) continue; await this.execute(campaign); } } finally { this.ticking = false; } }
  private async execute(campaign: JobCampaign): Promise<void> { const correlationId = randomUUID(); const runId = this.service.store.startCampaignRun(campaign.id, correlationId); const queued = this.service.store.queue.enqueue('campaign.execute', { campaignId: campaign.id }, { correlationId, maxAttempts: 1 }); const worker = `campaign-scheduler:${process.pid}`; if (!this.service.store.queue.claimById(queued.id, worker)) { this.service.store.finishCampaignRun(runId, 'failed', { code: 'WORKFLOW_STATE_CONFLICT' }); return; } try { const result = await this.service.runCampaign(campaign); this.service.store.queue.complete(queued.id, worker); this.service.store.finishCampaignRun(runId, 'completed', { discovered: result.jobs.length, prepared: result.applications.length }); } catch (error) { this.service.store.queue.fail(queued.id, worker, error instanceof Error ? error.name : 'INTERNAL_ERROR', false); this.service.store.finishCampaignRun(runId, 'failed', { code: error instanceof Error ? error.name : 'INTERNAL_ERROR' }); } }
}

export function isScheduleDue(schedule: Schedule, now: Date, lastRunAt?: string): boolean { const [minuteText, hourText, , , weekdayText] = schedule.cron.split(' '); if (!minuteText || !hourText || !weekdayText) return false; const formatter = new Intl.DateTimeFormat('en-US', { timeZone: schedule.timezone, hour12: false, weekday: 'short', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }); const parts = Object.fromEntries(formatter.formatToParts(now).filter((part) => part.type !== 'literal').map((part) => [part.type, part.value])); const weekday = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].indexOf(parts.weekday ?? ''); const weekdayAllowed = weekdayText === '*' || weekdayText === String(weekday) || (weekdayText === '1-5' && weekday >= 1 && weekday <= 5); if (Number(parts.minute) !== Number(minuteText) || Number(parts.hour) !== Number(hourText) || !weekdayAllowed) return false; if (!lastRunAt) return true; return formatter.format(new Date(lastRunAt)) !== formatter.format(now); }
