import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import { importCvText, updateProfileFact } from '../../../packages/profile-engine/src/index.ts';
import { parseFriendlySchedule, ValidationError, asRecord, requiredString, stringArray, validateTimezone } from '../../../packages/shared/src/validation.ts';
import type { AgentSettings, CandidateProfile, ExecutionMode, JobCampaign } from '../../../packages/shared/src/domain.ts';
import { WuzzufToolError, wuzzufToolActions, type WuzzufToolAction } from '../../../packages/shared/src/wuzzuf.ts';
import { OrchestratorService } from './service.ts';
import { sanitizeAuditDetail, sanitizeDiagnostics } from '../../../packages/security/src/index.ts';
import { clientScopes, connectorIds, type Artifact, type ClientScope, type ConnectorId } from '../../../packages/shared-contracts/src/index.ts';
import type { Store } from './store.ts';
import { extname, join, resolve } from 'node:path';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { ArtifactStore } from '../../../packages/artifact-store/src/index.ts';
import { ResumeVault } from '../../../packages/resume-importers/src/index.ts';
import { tailorResume } from '../../../packages/resume-tailor/src/index.ts';
import type { NormalizedJob } from '../../../packages/shared-contracts/src/index.ts';
import { LocalWorkerClient } from './worker-client.ts';
import { DashboardSessions, handleDashboardRequest } from './dashboard-api.ts';

type ResumeRenderResult = { artifacts: { json: Artifact; html: Artifact; pdf: Artifact; diff: Artifact; validation: Artifact } };

const MAX_BODY_BYTES = 6 * 1024 * 1024;

class Sessions {
  private readonly tokens = new Map<string, number>();
  private readonly pairingCode: string; private readonly ttlMs: number; private readonly store: Store;
  constructor(pairingCode: string, ttlMs: number, store: Store) { this.pairingCode = pairingCode; this.ttlMs = ttlMs; this.store = store; }
  pair(code: string): { token: string; expiresAt: string } {
    const expected = createHash('sha256').update(this.pairingCode).digest(); const actual = createHash('sha256').update(code).digest();
    if (!timingSafeEqual(expected, actual)) throw new HttpError(401, 'Invalid pairing code');
    const token = randomBytes(32).toString('base64url'); const expires = Date.now() + this.ttlMs; this.tokens.set(createHash('sha256').update(token).digest('hex'), expires); this.store.enrollClient('extension', 'Paired Chrome extension', token, clientScopes, new Date(expires).toISOString());
    return { token, expiresAt: new Date(expires).toISOString() };
  }
  valid(token: string): boolean { const key = createHash('sha256').update(token).digest('hex'); const expires = this.tokens.get(key); if (!expires || expires < Date.now()) { this.tokens.delete(key); return false; } return true; }
}

class HttpError extends Error { readonly status: number; constructor(status: number, message: string) { super(message); this.status = status; } }

export interface BridgeOptions { allowedOrigin: string; pairingCode: string; sessionTtlMs?: number; toolToken?: string; composioToolToken?: string; workerToken?: string; workerTimeoutMs?: number; openclawScopes?: ClientScope[]; composioScopes?: ClientScope[] }

export function createBridge(service: OrchestratorService, options: BridgeOptions) {
  if (!/^chrome-extension:\/\/[a-p]{32}$/.test(options.allowedOrigin) && !options.allowedOrigin.startsWith('http://127.0.0.1:')) throw new Error('An exact extension or loopback development origin is required');
  if (options.toolToken) service.store.enrollClient('openclaw', 'OpenClaw plugin', options.toolToken, options.openclawScopes ?? defaultAgentScopes);
  if (options.composioToolToken) service.store.enrollClient('composio-host', 'Composio session host', options.composioToolToken, options.composioScopes ?? defaultAgentScopes);
  const sessions = new Sessions(options.pairingCode, options.sessionTtlMs ?? 15 * 60_000, service.store);
  const dashboardSessions = new DashboardSessions(options.pairingCode, options.sessionTtlMs ?? 15 * 60_000);
  const worker = options.workerToken ? new LocalWorkerClient(service.store, options.workerToken, options.workerTimeoutMs) : undefined;
  const limiter = new RateLimiter(120, 60_000);
  const server = createServer(async (req, res) => {
    try {
      if (!limiter.allow(req.socket.remoteAddress ?? 'loopback')) throw new HttpError(429, 'Rate limit exceeded');
      applySecurityHeaders(req, res, options.allowedOrigin);
      if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }
      const url = new URL(req.url ?? '/', 'http://127.0.0.1');
      if (await serveDashboard(req, res, url)) return;
      if (await handleDashboardRequest(req, res, url, service, dashboardSessions, worker)) return;
      if (req.method === 'GET' && url.pathname === '/health') return json(res, 200, { ok: true, emergencyStop: service.emergencyStop.active, chrome: service.wuzzuf.browserStatus() });
      if (req.method === 'GET' && url.pathname === '/health/live') return json(res, 200, { ok: true, status: 'live' });
      if (req.method === 'GET' && url.pathname === '/health/ready') { const browser = service.wuzzuf.browserStatus(); const ready = !service.emergencyStop.active; return json(res, ready ? 200 : 503, { ok: ready, storage: service.store.health(), queue: service.store.queue.health(), browser, emergencyStop: service.emergencyStop.active }); }
      if (req.method === 'GET' && url.pathname === '/health/storage') return json(res, 200, service.store.health());
      if (req.method === 'GET' && url.pathname === '/health/queue') return json(res, 200, { ok: true, counts: service.store.queue.health() });
      if (req.method === 'GET' && url.pathname === '/health/browser') return json(res, 200, { ok: true, ...service.wuzzuf.browserStatus() });
      if (req.method === 'GET' && url.pathname === '/health/wuzzuf-auth') return json(res, 200, { ok: true, ...service.wuzzuf.authStatus() });
      if (req.method === 'GET' && url.pathname === '/health/composio') return json(res, 200, { ok: true, configured: Boolean(process.env.COMPOSIO_API_KEY), secretValues: 'redacted' });
      if (req.method === 'POST' && url.pathname === '/v1/pair') { const body = asRecord(await readJson(req)); return json(res, 200, sessions.pair(requiredString(body.code, 'code', 256))); }
      if (req.method === 'GET' && url.pathname === '/v1/wuzzuf/approval-requests') { authorizeSession(req, sessions); return json(res, 200, { ok: true, data: service.wuzzuf.pendingApprovals() }); }
      const approvalDecisionMatch = url.pathname.match(/^\/v1\/wuzzuf\/approval-requests\/([^/]+)\/decision$/);
      if (req.method === 'POST' && approvalDecisionMatch) { authorizeSession(req, sessions); const body = asRecord(await readJson(req)); if (typeof body.approved !== 'boolean') throw new ValidationError('approved must be a boolean'); return json(res, 200, { ok: true, data: service.wuzzuf.decideApproval(requiredString(approvalDecisionMatch[1], 'approvalRequestId', 100), body.approved) }); }
      const artifactContentMatch = url.pathname.match(/^\/v1\/artifacts\/([^/]+)\/content$/);
      if (req.method === 'GET' && artifactContentMatch) { authorizeSession(req, sessions); const value = service.store.getArtifactContent(requiredString(artifactContentMatch[1], 'artifactId', 100)); if (!value || value.artifact.kind !== 'resume-pdf') throw new HttpError(404, 'PDF artifact not found'); return json(res, 200, { ok: true, data: { artifact: value.artifact, base64: value.content.toString('base64') }, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/data/delete') { authorizeSession(req, sessions); const body = asRecord(await readJson(req)); if (body.confirmation !== 'DELETE LOCAL DATA') throw new ValidationError('Exact deletion confirmation is required'); service.emergencyStop.engage(); service.store.queue.requestCancellationAll('personal-data-deletion'); let deleted: { artifactIds: string[] }; try { deleted = service.store.deleteUserData(); } catch (error) { if (error instanceof Error && error.message === 'ACTIVE_WORK_REMAINS') throw new HttpError(409, 'Active worker operation is cancelling; retry deletion after it stops'); throw error; } const vault = new ArtifactStore(resolve(process.env.DATA_DIR ?? './data', 'vault')); for (const artifactId of deleted.artifactIds) try { vault.remove(artifactId); } catch { /* already absent */ } return json(res, 200, { ok: true, data: { deleted: true, artifactCount: deleted.artifactIds.length }, correlationId: randomUUID() }); }
      authorize(req, sessions, service.store, requiredScope(url.pathname, req.method), options.toolToken, options.composioToolToken);
      if (req.method === 'GET' && url.pathname === '/v1/connectors') return json(res, 200, { ok: true, data: service.jobs.capabilities(), correlationId: randomUUID() });
      const connectorMatch = url.pathname.match(/^\/v1\/connectors\/([^/]+)$/);
      if (req.method === 'GET' && connectorMatch) { const id = connectorMatch[1] as ConnectorId; if (!connectorIds.includes(id)) throw new HttpError(404, 'Unknown connector'); return json(res, 200, { ok: true, data: service.jobs.capabilities(id), correlationId: randomUUID() }); }
      if (req.method === 'POST' && connectorMatch) { const id = connectorMatch[1] as ConnectorId; if (!connectorIds.includes(id)) throw new HttpError(404, 'Unknown connector'); const body = asRecord(await readJson(req)); if (typeof body.enabled !== 'boolean') throw new ValidationError('enabled must be a boolean'); return json(res, 200, { ok: true, data: service.jobs.configureConnector(id, body.enabled), correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/jobs/search') { const body = asRecord(await readJson(req)); const result = await service.jobs.search({ queries: stringArray(body.queries, 'queries', 10), locations: stringArray(body.locations, 'locations', 10), ...(body.limit === undefined ? {} : { limit: boundedNumber(body.limit, 'limit', 1, 100, 25) }) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/jobs/import-current-page') { const body = asRecord(await readJson(req)); const safeMetadata = body.safeMetadata === undefined ? undefined : asRecord(body.safeMetadata) as Record<string, string | string[] | boolean | undefined>; const result = service.jobs.importCurrentPage({ url: requiredString(body.url, 'url', 4_000), ...(typeof body.title === 'string' ? { title: body.title } : {}), ...(body.jsonLd === undefined ? {} : { jsonLd: body.jsonLd }), ...(safeMetadata ? { safeMetadata } : {}) }); return json(res, 201, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/jobs/details') { const body = asRecord(await readJson(req)); const result = service.jobs.details({ ...(typeof body.jobId === 'string' ? { jobId: requiredString(body.jobId, 'jobId', 100) } : {}), ...(typeof body.url === 'string' ? { url: requiredString(body.url, 'url', 4_000) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/jobs/score') { const body = asRecord(await readJson(req)); const result = service.jobs.score({ jobId: requiredString(body.jobId, 'jobId', 100), ...(typeof body.profileId === 'string' ? { profileId: requiredString(body.profileId, 'profileId', 100) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'GET' && url.pathname === '/v1/connectors/wuzzuf/connection') return json(res, 200, { ok: true, data: service.jobs.getWuzzufConnectionStatus(), correlationId: randomUUID() });
      if (req.method === 'POST' && url.pathname === '/v1/connectors/wuzzuf/login') return json(res, 200, { ok: true, data: await service.jobs.openWuzzufLogin(), correlationId: randomUUID() });
      if (req.method === 'POST' && url.pathname === '/v1/applications/prepare') { const body = asRecord(await readJson(req)); const result = await service.jobs.prepareApplication({ ...(typeof body.jobId === 'string' ? { jobId: requiredString(body.jobId, 'jobId', 100) } : {}), ...(typeof body.url === 'string' ? { url: requiredString(body.url, 'url', 2_000) } : {}), ...(typeof body.profileId === 'string' ? { profileId: requiredString(body.profileId, 'profileId', 100) } : {}), dryRun: body.dryRun !== false, ...(typeof body.idempotencyKey === 'string' ? { idempotencyKey: requiredString(body.idempotencyKey, 'idempotencyKey', 128) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/applications/review') { const body = asRecord(await readJson(req)); return json(res, 200, { ok: true, data: service.jobs.getApplicationReview(requiredString(body.applicationId, 'applicationId', 100)), correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/applications/fill') { const body = asRecord(await readJson(req)); const result = await service.jobs.fillApplication({ applicationId: requiredString(body.applicationId, 'applicationId', 100), ...(Array.isArray(body.approvedAnswerOverrides) ? { approvedAnswerOverrides: approvedAnswerOverrides(body.approvedAnswerOverrides) } : {}), dryRun: body.dryRun !== false, ...(typeof body.idempotencyKey === 'string' ? { idempotencyKey: requiredString(body.idempotencyKey, 'idempotencyKey', 128) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/applications/request-submission-approval') { const body = asRecord(await readJson(req)); const result = service.jobs.requestSubmissionApproval({ applicationId: requiredString(body.applicationId, 'applicationId', 100), ttlSeconds: boundedNumber(body.ttlSeconds, 'ttlSeconds', 30, 300, 120), ...(typeof body.idempotencyKey === 'string' ? { idempotencyKey: requiredString(body.idempotencyKey, 'idempotencyKey', 128) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/applications/submit') { const body = asRecord(await readJson(req)); const result = await service.jobs.submitApplication({ applicationId: requiredString(body.applicationId, 'applicationId', 100), approvalRequestId: requiredString(body.approvalRequestId, 'approvalRequestId', 100), approvalToken: requiredString(body.approvalToken, 'approvalToken', 256), ...(typeof body.idempotencyKey === 'string' ? { idempotencyKey: requiredString(body.idempotencyKey, 'idempotencyKey', 128) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/applications/cancel') { const body = asRecord(await readJson(req)); const result = await service.jobs.cancelApplication({ applicationId: requiredString(body.applicationId, 'applicationId', 100), ...(typeof body.idempotencyKey === 'string' ? { idempotencyKey: requiredString(body.idempotencyKey, 'idempotencyKey', 128) } : {}) }); return json(res, 200, { ok: true, data: result, correlationId: randomUUID() }); }
      if (req.method === 'POST' && url.pathname === '/v1/applications/status') { const body = asRecord(await readJson(req)); return json(res, 200, { ok: true, data: service.jobs.getApplicationStatus(requiredString(body.applicationId, 'applicationId', 100)), correlationId: randomUUID() }); }
      if (req.method === 'GET' && url.pathname === '/v1/resumes') return json(res, 200, { ok: true, data: service.store.listRegisteredResumes().map((record) => ({ source: record.source, facts: record.profile.facts })), correlationId: randomUUID() });
      if (req.method === 'POST' && url.pathname === '/v1/resumes/import') { const body = asRecord(await readJson(req)); const sourceName = requiredString(body.sourceName, 'sourceName', 200); const encoded = requiredString(body.base64, 'base64', 5_800_000); if (!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded)) throw new ValidationError('Invalid base64 resume'); const bytes = Buffer.from(encoded, 'base64'); const vault = new ArtifactStore(resolve(process.env.DATA_DIR ?? './data', 'vault')); const imported = await new ResumeVault(vault, 5 * 1024 * 1024).importBytes(typeof body.profileId === 'string' ? requiredString(body.profileId, 'profileId', 100) : 'default', sourceName, bytes); try { service.store.saveRegisteredResume(imported.source, imported.sourceArtifactId, imported.profile); } catch (error) { vault.remove(imported.sourceArtifactId); throw error; } service.audit(imported.source.id, 'resume.source_imported', { resumeSourceId: imported.source.id, mediaType: imported.source.mediaType, size: imported.source.size, factCount: imported.profile.facts.length }); return json(res, 201, { ok: true, data: { source: imported.source, facts: imported.profile.facts }, correlationId: randomUUID() }); }
      const registeredResumeMatch = url.pathname.match(/^\/v1\/resumes\/([^/]+)\/(approve|remove)$/);
      if (req.method === 'POST' && registeredResumeMatch) { const resumeId = requiredString(registeredResumeMatch[1], 'resumeId', 100); if (registeredResumeMatch[2] === 'approve') { const approved = service.store.approveRegisteredResume(resumeId); if (!approved) throw new HttpError(404, 'Resume not found'); service.audit(resumeId, 'resume.source_approved', { resumeSourceId: resumeId, snapshotId: approved.snapshotId }); return json(res, 200, { ok: true, data: { source: approved.source, facts: approved.profile.facts, snapshotId: approved.snapshotId }, correlationId: randomUUID() }); } const artifactId = service.store.removeRegisteredResume(resumeId); if (!artifactId) throw new HttpError(404, 'Resume not found'); new ArtifactStore(resolve(process.env.DATA_DIR ?? './data', 'vault')).remove(artifactId); service.audit(resumeId, 'resume.source_removed', { resumeSourceId: resumeId }); return json(res, 200, { ok: true, data: { removed: true }, correlationId: randomUUID() }); }
      const tailorMatch = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/tailor-resume$/);
      if (req.method === 'POST' && tailorMatch) { const body = asRecord(await readJson(req)); const response = await idempotentMutation(service.store, 'resume.tailor', body, async () => { const resumeId = requiredString(body.resumeId, 'resumeId', 100); const resume = service.store.getRegisteredResume(resumeId); const snapshot = service.store.canonicalProfileSnapshot(resumeId); if (!resume?.source.approved || !snapshot) throw new HttpError(409, 'Resume must be approved before tailoring'); const legacy = service.store.getJob(requiredString(tailorMatch[1], 'jobId', 100)); if (!legacy) throw new HttpError(404, 'Job not found'); const connectorId = service.jobs.policies.connectorForHost(new URL(legacy.url).hostname); const destination = service.jobs.destinations.detect(legacy.url).destination; const job: NormalizedJob = { id: legacy.id, fingerprint: legacy.fingerprint, title: legacy.title, employer: legacy.employer, location: legacy.location, description: legacy.description, url: legacy.url, source: { connectorId, externalId: legacy.sourceId, discoveredAt: legacy.discoveredAt ?? new Date().toISOString(), discoveryMode: service.jobs.policies.get(connectorId).capabilities.discovery }, applicationDestination: destination, requiredSkills: legacy.requiredSkills ?? [], preferredSkills: legacy.preferredSkills ?? [], remote: legacy.remote ?? false, matchScore: legacy.matchScore }; const result = tailorResume({ sourceResumeId: resumeId, profileSnapshotId: snapshot.id, profile: snapshot.profile, job }); service.store.saveTailoredResume(result); let data = result; if (worker) { const rendered = await worker.execute<ResumeRenderResult>('resume.render', 'renderResume', { document: result.document, review: result.review, validation: result.validation }); data = service.store.attachTailoredResumeArtifacts(result.tailoredResume.id, rendered.artifacts) ?? result; } service.audit(result.tailoredResume.id, 'resume.tailoring_review_created', { tailoredResumeId: result.tailoredResume.id, jobId: job.id, resumeId, valid: result.validation.valid, rendered: Boolean(worker) }); return { ok: true, data, correlationId: randomUUID() }; }); return json(res, 201, response); }
      const tailoredMatch = url.pathname.match(/^\/v1\/tailored-resumes\/([^/]+)(?:\/(approve))?$/);
      if (tailoredMatch && req.method === 'GET') { const value = service.store.getTailoredResume(tailoredMatch[1]!); if (!value) throw new HttpError(404, 'Tailored resume not found'); return json(res, 200, { ok: true, data: value, correlationId: randomUUID() }); }
      if (tailoredMatch?.[2] === 'approve' && req.method === 'POST') { const body = asRecord(await readJson(req)); const response = await idempotentMutation(service.store, 'resume.tailoring.approve', { ...body, tailoredResumeId: tailoredMatch[1] }, async () => { if (!service.store.approveTailoredResume(tailoredMatch[1]!)) throw new HttpError(404, 'Tailored resume not found'); service.audit(tailoredMatch[1]!, 'resume.tailoring_approved', { tailoredResumeId: tailoredMatch[1] }); return { ok: true, data: { approved: true }, correlationId: randomUUID() }; }); return json(res, 200, response); }
      const artifactMatch = url.pathname.match(/^\/v1\/artifacts\/([^/]+)$/);
      if (artifactMatch && req.method === 'GET') { const artifact = service.store.getArtifact(requiredString(artifactMatch[1], 'artifactId', 100)); if (!artifact) throw new HttpError(404, 'Artifact not found'); return json(res, 200, { ok: true, data: artifact, correlationId: randomUUID() }); }
      const wuzzufMatch = url.pathname.match(/^\/v1\/wuzzuf\/tools\/([A-Z_]+)$/);
      if (req.method === 'POST' && wuzzufMatch) {
        const action = wuzzufMatch[1] as WuzzufToolAction; if (!wuzzufToolActions.includes(action)) throw new HttpError(404, 'Unknown Wuzzuf action'); const body = asRecord(await readJson(req)); const data = await dispatchWuzzufAction(service, action, body); return json(res, 200, { ok: true, data });
      }
      if (req.method === 'GET' && url.pathname === '/v1/dashboard') { const legacyProfiles = service.store.listProfiles().map(publicProfile); const canonicalProfiles = service.store.listRegisteredResumes().filter((record) => record.source.approved).map((record) => service.store.registeredCandidateProfile(record.source.profileId)).filter((profile): profile is CandidateProfile => Boolean(profile)); const profiles = [...legacyProfiles, ...canonicalProfiles.filter((profile) => !legacyProfiles.some((legacy) => legacy.id === profile.id))]; return json(res, 200, { campaigns: service.store.listCampaigns(), profiles, resumes: service.store.listRegisteredResumes().map((record) => ({ source: record.source, factCount: record.profile.facts.length })), timeline: service.store.timeline().map((event) => ({ ...event, detail: sanitizeAuditDetail(event.detail) })), queue: service.store.queue.health(), agentSettings: service.settings, emergencyStop: service.emergencyStop.active }); }
      if (req.method === 'POST' && url.pathname === '/v1/profiles/import') {
        const body = asRecord(await readJson(req)); const sourceName = requiredString(body.sourceName, 'sourceName', 200); const resumeContent = typeof body.base64 === 'string' ? Buffer.from(body.base64, 'base64') : Buffer.from(requiredString(body.text, 'text', 200_000)); if (resumeContent.length > 4 * 1024 * 1024) throw new HttpError(413, 'Resume must be smaller than 4 MB'); const text = typeof body.base64 === 'string' ? await extractResumeText(sourceName, body.base64) : resumeContent.toString('utf8'); const profile = importCvText(requiredString(body.name, 'name', 100), sourceName, text); service.saveProfile(profile); service.store.saveResumeFile(profile.id, profile.cvVariants[0]!.id, sourceName, resumeContent); const settings = { ...service.settings, activeProfileId: profile.id, updatedAt: new Date().toISOString() }; service.saveSettings(settings); service.audit(profile.id, 'profile.imported', { sourceName, factCount: profile.facts.length }); return json(res, 201, publicProfile(profile));
      }
      const factMatch = url.pathname.match(/^\/v1\/profiles\/([^/]+)\/facts\/([^/]+)$/);
      if (req.method === 'POST' && factMatch) { const profile = service.store.getProfile(factMatch[1]!); if (!profile) throw new HttpError(404, 'Profile not found'); const body = asRecord(await readJson(req)); const value = body.value; if (!['string', 'number', 'boolean'].includes(typeof value)) throw new ValidationError('Invalid fact value'); const updated = updateProfileFact(profile, factMatch[2]!, value as string | number | boolean); service.saveProfile(updated); service.audit(profile.id, 'profile.fact_updated', { factId: factMatch[2] }); return json(res, 200, updated); }
      const resumeMatch = url.pathname.match(/^\/v1\/profiles\/([^/]+)\/resumes\/([^/]+)\/approve$/);
      if (req.method === 'POST' && resumeMatch) { const profile = service.store.getProfile(resumeMatch[1]!); if (!profile) throw new HttpError(404, 'Profile not found'); const body = asRecord(await readJson(req)); const approved = body.approved === true; if (!profile.cvVariants.some((resume) => resume.id === resumeMatch[2])) throw new HttpError(404, 'Resume not found'); const updated = { ...profile, cvVariants: profile.cvVariants.map((resume) => resume.id === resumeMatch[2] ? { ...resume, approved } : resume), updatedAt: new Date().toISOString() }; service.saveProfile(updated); service.audit(profile.id, approved ? 'profile.resume_approved' : 'profile.resume_unapproved', { resumeId: resumeMatch[2] }); return json(res, 200, updated); }
      if (req.method === 'POST' && url.pathname === '/v1/campaigns') {
        const body = asRecord(await readJson(req)); const now = new Date().toISOString(); const timezone = validateTimezone(requiredString(body.timezone ?? 'Africa/Cairo', 'timezone', 100));
        const mode = requiredString(body.executionMode ?? 'prepare_and_review', 'executionMode', 40) as ExecutionMode; if (!['research_only', 'prepare_and_review', 'auto_submit'].includes(mode)) throw new ValidationError('Invalid execution mode');
        const scheduleText = typeof body.schedule === 'string' && body.schedule.trim() ? body.schedule : undefined;
        const campaign: JobCampaign = {
          id: randomUUID(), name: requiredString(body.name, 'name', 100), state: 'enabled', searchQueries: stringArray(body.searchQueries, 'searchQueries'), locations: stringArray(body.locations, 'locations'),
          workplace: ['remote'], includedKeywords: stringArray(body.includedKeywords ?? [], 'includedKeywords'), excludedKeywords: stringArray(body.excludedKeywords ?? [], 'excludedKeywords'), seniority: stringArray(body.seniority ?? ['senior'], 'seniority'),
          minimumMatchScore: boundedNumber(body.minimumMatchScore, 'minimumMatchScore', 0, 100, 70), allowedSites: stringArray(body.allowedSites ?? ['development'], 'allowedSites'), maxApplicationsPerRun: boundedNumber(body.maxApplicationsPerRun, 'maxApplicationsPerRun', 1, 100, 10), maxApplicationsPerDay: boundedNumber(body.maxApplicationsPerDay, 'maxApplicationsPerDay', 1, 200, 20), timezone,
          ...(scheduleText ? { schedule: parseFriendlySchedule(scheduleText, timezone) } : {}), executionMode: mode, profileId: requiredString(body.profileId, 'profileId', 100), cvStrategy: requiredString(body.cvStrategy ?? 'selected', 'cvStrategy', 100), providerId: requiredString(body.providerId ?? 'openclaw', 'providerId', 100), model: requiredString(body.model ?? 'default', 'model', 200), dryRun: body.dryRun !== false, createdAt: now, updatedAt: now
        };
        return json(res, 201, await idempotentMutation(service.store, 'campaign.create', body, async () => service.createCampaign(campaign)));
      }
      const runMatch = url.pathname.match(/^\/v1\/campaigns\/([^/]+)\/run$/);
      if (req.method === 'POST' && runMatch) { const body = asRecord(await readJson(req)); const campaign = service.store.getCampaign(runMatch[1]!); if (!campaign) throw new HttpError(404, 'Campaign not found'); if (campaign.state === 'paused') throw new HttpError(409, 'Campaign is paused'); return json(res, 200, await idempotentMutation(service.store, 'campaign.run', { ...body, campaignId: campaign.id }, async () => service.runCampaign(campaign))); }
      const stateMatch = url.pathname.match(/^\/v1\/campaigns\/([^/]+)\/(pause|resume)$/);
      if (req.method === 'POST' && stateMatch) { const body = asRecord(await readJson(req)); const campaign = service.store.getCampaign(stateMatch[1]!); if (!campaign) throw new HttpError(404, 'Campaign not found'); return json(res, 200, await idempotentMutation(service.store, `campaign.${stateMatch[2]}`, { ...body, campaignId: campaign.id }, async () => { const updated: JobCampaign = { ...campaign, state: stateMatch[2] === 'pause' ? 'paused' : 'enabled', updatedAt: new Date().toISOString() }; service.store.saveCampaign(updated); service.audit(campaign.id, `campaign.${updated.state}`, {}); return updated; })); }
      const fillMatch = url.pathname.match(/^\/v1\/applications\/([^/]+)\/fill-result$/);
      if (req.method === 'POST' && fillMatch) { const body = asRecord(await readJson(req)); const filled = stringArray(body.filled ?? [], 'filled', 100); const skipped = stringArray(body.skipped ?? [], 'skipped', 100); service.audit(requiredString(body.correlationId, 'correlationId', 100), skipped.length ? 'application.fill_partial' : 'application.filled', { filled, skipped }, fillMatch[1]); return json(res, 200, { recorded: true }); }
      if (req.method === 'POST' && url.pathname === '/v1/chat') {
        const body = asRecord(await readJson(req)); const text = requiredString(body.text, 'text', 8_000); const profileId = typeof body.profileId === 'string' ? body.profileId : undefined; res.writeHead(200, { 'content-type': 'application/x-ndjson; charset=utf-8', 'cache-control': 'no-store' });
        for await (const chunk of service.chat(text, profileId)) res.write(`${JSON.stringify({ type: 'chunk', text: chunk })}\n`); res.end(`${JSON.stringify({ type: 'done' })}\n`); return;
      }
      if (req.method === 'GET' && url.pathname === '/v1/models') return json(res, 200, await service.discoverModels());
      if (req.method === 'POST' && url.pathname === '/v1/agent-settings') { const body = asRecord(await readJson(req)); const current = service.settings; const settings: AgentSettings = { ...current, ...(typeof body.activeProfileId === 'string' ? { activeProfileId: body.activeProfileId } : {}), chatModel: requiredString(body.chatModel ?? current.chatModel, 'chatModel', 200), answerModel: requiredString(body.answerModel ?? current.answerModel, 'answerModel', 200), matchingModel: requiredString(body.matchingModel ?? current.matchingModel, 'matchingModel', 200), temperature: boundedNumber(body.temperature, 'temperature', 0, 2, current.temperature), maximumAnswerLength: boundedNumber(body.maximumAnswerLength, 'maximumAnswerLength', 50, 5000, current.maximumAnswerLength), confidenceThreshold: boundedNumber(body.confidenceThreshold, 'confidenceThreshold', 0, 1, current.confidenceThreshold), maximumConcurrentRuns: boundedNumber(body.maximumConcurrentRuns, 'maximumConcurrentRuns', 1, 10, current.maximumConcurrentRuns), defaultDryRun: body.defaultDryRun !== false, browserHeadless: body.browserHeadless !== false, updatedAt: new Date().toISOString() }; service.saveSettings(settings); return json(res, 200, settings); }
      if (req.method === 'POST' && url.pathname === '/v1/answers/prepare') { const body = asRecord(await readJson(req)); const labels = stringArray(body.labels, 'labels', 100); return json(res, 200, await service.prepareQuestions(labels, typeof body.profileId === 'string' ? body.profileId : undefined)); }
      if (req.method === 'POST' && url.pathname === '/v1/emergency-stop') { service.emergencyStop.engage(); const cancelledJobs = service.store.queue.requestCancellationAll('emergency-stop'); service.audit(randomUUID(), 'emergency_stop.engaged', { cancelledJobs }); return json(res, 200, { stopped: true, cancelledJobs }); }
      if (req.method === 'POST' && url.pathname === '/v1/emergency-stop/reset') { service.emergencyStop.reset(); return json(res, 200, { stopped: false }); }
      throw new HttpError(404, 'Not found');
    } catch (error) {
      const status = error instanceof HttpError ? error.status : error instanceof WuzzufToolError ? error.status : error instanceof ValidationError || error instanceof SyntaxError ? 400 : 500;
      if (error instanceof WuzzufToolError) return json(res, status, { ok: false, error: { code: error.code, message: error.message, retryable: error.retryable, correlationId: error.correlationId ?? randomUUID(), ...(error.actionRequired ? { actionRequired: error.actionRequired } : {}), ...(error.diagnostics ? { diagnostics: safeDiagnostics(error.diagnostics) } : {}) } });
      json(res, status, { error: status === 500 ? 'Internal server error' : error instanceof Error ? error.message : 'Request failed' });
    }
  });
  server.requestTimeout = 65_000; server.headersTimeout = 10_000; return server;
}

class RateLimiter {
  private readonly buckets = new Map<string, { count: number; resetAt: number }>();
  private readonly limit: number; private readonly windowMs: number;
  constructor(limit: number, windowMs: number) { this.limit = limit; this.windowMs = windowMs; }
  allow(key: string): boolean { const now = Date.now(); const current = this.buckets.get(key); if (!current || current.resetAt <= now) { this.buckets.set(key, { count: 1, resetAt: now + this.windowMs }); return true; } current.count += 1; return current.count <= this.limit; }
}

async function dispatchWuzzufAction(service: OrchestratorService, action: WuzzufToolAction, body: Record<string, unknown>): Promise<unknown> {
  const applicationId = () => requiredString(body.applicationId, 'applicationId', 100); const idempotencyKey = typeof body.idempotencyKey === 'string' ? requiredString(body.idempotencyKey, 'idempotencyKey', 128) : undefined; const withIdempotency = idempotencyKey === undefined ? {} : { idempotencyKey }; const jobRef = () => ({ ...(typeof body.jobId === 'string' ? { jobId: requiredString(body.jobId, 'jobId', 100) } : {}), ...(typeof body.url === 'string' ? { url: requiredString(body.url, 'url', 2_000) } : {}), ...(typeof body.profileId === 'string' ? { profileId: requiredString(body.profileId, 'profileId', 100) } : {}) });
  switch (action) {
    case 'WUZZUF_CREATE_CONNECTION': return service.jobs.createWuzzufConnection();
    case 'WUZZUF_VERIFY_CONNECTION': return service.jobs.verifyWuzzufConnection();
    case 'WUZZUF_DISCONNECT': return service.jobs.disconnectWuzzuf();
    case 'WUZZUF_SEARCH_JOBS': return service.jobs.wuzzufSearch({ queries: stringArray(body.queries, 'queries', 10), locations: stringArray(body.locations, 'locations', 10), ...(typeof body.remote === 'boolean' ? { remote: body.remote } : {}), ...(typeof body.experienceLevel === 'string' ? { experienceLevel: requiredString(body.experienceLevel, 'experienceLevel', 100) } : {}), ...(body.employmentTypes !== undefined ? { employmentTypes: stringArray(body.employmentTypes, 'employmentTypes', 10) } : {}), ...(body.limit !== undefined ? { limit: boundedNumber(body.limit, 'limit', 1, 100, 25) } : {}) });
    case 'WUZZUF_GET_JOB_DETAILS': return service.jobs.wuzzufDetails(requiredString(body.url, 'url', 2_000));
    case 'WUZZUF_SCORE_JOB': return service.jobs.wuzzufScore(jobRef());
    case 'WUZZUF_PREPARE_APPLICATION': return service.jobs.prepareApplication({ ...jobRef(), dryRun: body.dryRun !== false, ...withIdempotency });
    case 'WUZZUF_FILL_APPLICATION': return service.jobs.fillApplication({ applicationId: applicationId(), ...(Array.isArray(body.approvedAnswerOverrides) ? { approvedAnswerOverrides: approvedAnswerOverrides(body.approvedAnswerOverrides) } : {}), dryRun: body.dryRun !== false, ...withIdempotency });
    case 'WUZZUF_GET_APPLICATION_REVIEW': return service.jobs.getApplicationReview(applicationId());
    case 'WUZZUF_REQUEST_SUBMISSION_APPROVAL': return service.jobs.requestSubmissionApproval({ applicationId: applicationId(), ttlSeconds: boundedNumber(body.ttlSeconds, 'ttlSeconds', 30, 300, 120), ...withIdempotency });
    case 'WUZZUF_SUBMIT_APPLICATION': return service.jobs.submitApplication({ applicationId: applicationId(), approvalRequestId: requiredString(body.approvalRequestId, 'approvalRequestId', 100), approvalToken: requiredString(body.approvalToken, 'approvalToken', 256), ...withIdempotency });
    case 'WUZZUF_GET_APPLICATION_STATUS': return service.jobs.getApplicationStatus(applicationId());
    case 'WUZZUF_CANCEL_APPLICATION': return service.jobs.cancelApplication({ applicationId: applicationId(), ...withIdempotency });
    case 'WUZZUF_GET_AUTH_STATUS': return service.jobs.getWuzzufConnectionStatus();
    case 'WUZZUF_OPEN_LOGIN': return service.jobs.openWuzzufLogin();
  }
}

function applySecurityHeaders(req: IncomingMessage, res: ServerResponse, allowedOrigin: string): void {
  const origin = req.headers.origin; const host = req.headers.host ?? ''; const dashboardOrigin = /^(?:127\.0\.0\.1|localhost):\d+$/.test(host) ? `http://${host}` : undefined;
  if (origin && origin !== allowedOrigin && origin !== dashboardOrigin) throw new HttpError(403, 'Origin denied');
  if (origin === allowedOrigin) res.setHeader('access-control-allow-origin', allowedOrigin);
  res.setHeader('vary', 'Origin'); res.setHeader('access-control-allow-methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS'); res.setHeader('access-control-allow-headers', 'authorization,content-type,x-csrf-token,x-correlation-id,if-match');
  res.setHeader('x-content-type-options', 'nosniff'); res.setHeader('cache-control', 'no-store'); res.setHeader('referrer-policy', 'no-referrer');
  res.setHeader('content-security-policy', "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");
  res.setHeader('permissions-policy', 'camera=(), microphone=(), geolocation=(), payment=(), usb=()');
}

async function serveDashboard(req: IncomingMessage, res: ServerResponse, url: URL): Promise<boolean> {
  if (req.method !== 'GET' && req.method !== 'HEAD') return false;
  if (url.pathname === '/') { res.writeHead(302, { location: '/dashboard/' }); res.end(); return true; }
  if (url.pathname !== '/dashboard' && !url.pathname.startsWith('/dashboard/')) return false;
  if (url.pathname === '/dashboard') { res.writeHead(302, { location: '/dashboard/' }); res.end(); return true; }
  const root = resolve(process.cwd(), 'apps/dashboard/dist');
  if (!existsSync(root)) return false;
  const relative = url.pathname.slice('/dashboard/'.length);
  const candidate = relative && !relative.includes('..') ? join(root, relative) : join(root, 'index.html');
  const path = existsSync(candidate) && statSync(candidate).isFile() ? candidate : join(root, 'index.html');
  if (!existsSync(path)) return false;
  const content = readFileSync(path);
  const type = ({ '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.woff2': 'font/woff2' } as Record<string, string>)[extname(path)] ?? 'application/octet-stream';
  res.writeHead(200, { 'content-type': type, 'content-length': content.length, 'cache-control': path.endsWith('index.html') ? 'no-store' : 'public, max-age=31536000, immutable' });
  if (req.method === 'HEAD') res.end(); else res.end(content);
  return true;
}
function authorize(req: IncomingMessage, sessions: Sessions, store: Store, scope: ClientScope | readonly ClientScope[] | undefined, toolToken?: string, composioToolToken?: string): void { const suppliedOpenClaw = req.headers['x-openclaw-tool-token']; if (toolToken && typeof suppliedOpenClaw === 'string' && secretMatches(suppliedOpenClaw, toolToken)) { if (!store.authorizeClient('openclaw', suppliedOpenClaw, scope)) throw new HttpError(403, 'Client lacks required scope'); return; } const suppliedComposio = req.headers['x-composio-tool-token']; if (composioToolToken && typeof suppliedComposio === 'string' && secretMatches(suppliedComposio, composioToolToken)) { if (!store.authorizeClient('composio-host', suppliedComposio, scope)) throw new HttpError(403, 'Client lacks required scope'); return; } const auth = req.headers.authorization; if (!auth?.startsWith('Bearer ') || !sessions.valid(auth.slice(7))) throw new HttpError(401, 'Client authentication required'); }
function secretMatches(actualValue: string, expectedValue: string): boolean { const expected = createHash('sha256').update(expectedValue).digest(); const actual = createHash('sha256').update(actualValue).digest(); return timingSafeEqual(expected, actual); }
const defaultAgentScopes: ClientScope[] = ['profile:read', 'jobs:search', 'artifacts:read', 'applications:prepare', 'applications:fill', 'applications:review', 'campaigns:read', 'campaigns:manage', 'audit:read', 'admin:emergency-stop'];
function requiredScope(pathname: string, method?: string): ClientScope | readonly ClientScope[] | undefined {
  const action = pathname.match(/^\/v1\/wuzzuf\/tools\/([A-Z_]+)$/)?.[1];
  if (action) { if (['WUZZUF_SEARCH_JOBS', 'WUZZUF_GET_JOB_DETAILS', 'WUZZUF_SCORE_JOB', 'WUZZUF_GET_AUTH_STATUS', 'WUZZUF_OPEN_LOGIN', 'WUZZUF_CREATE_CONNECTION', 'WUZZUF_VERIFY_CONNECTION', 'WUZZUF_DISCONNECT'].includes(action)) return 'jobs:search'; if (action === 'WUZZUF_PREPARE_APPLICATION') return 'applications:prepare'; if (['WUZZUF_FILL_APPLICATION', 'WUZZUF_CANCEL_APPLICATION'].includes(action)) return 'applications:fill'; if (['WUZZUF_GET_APPLICATION_REVIEW', 'WUZZUF_GET_APPLICATION_STATUS', 'WUZZUF_REQUEST_SUBMISSION_APPROVAL'].includes(action)) return 'applications:review'; if (action === 'WUZZUF_SUBMIT_APPLICATION') return 'applications:submit'; }
  if (pathname.includes('/tailor-resume')) return 'applications:prepare';
  if (pathname === '/v1/applications/prepare') return 'applications:prepare';
  if (pathname === '/v1/applications/fill' || pathname === '/v1/applications/cancel') return 'applications:fill';
  if (pathname === '/v1/applications/submit') return 'applications:submit';
  if (pathname.startsWith('/v1/applications/')) return 'applications:review';
  if (pathname.startsWith('/v1/artifacts/')) return 'artifacts:read';
  if (pathname.startsWith('/v1/tailored-resumes/')) return method === 'POST' ? 'profile:write' : 'applications:review';
  if (pathname.startsWith('/v1/connectors/') && method === 'POST') return 'profile:write';
  if (pathname === '/v1/connectors' || pathname.startsWith('/v1/connectors/') || pathname.startsWith('/v1/jobs/')) return 'jobs:search';
  if (pathname.startsWith('/v1/profiles/') || pathname === '/v1/profiles/import' || pathname.startsWith('/v1/resumes') || pathname === '/v1/agent-settings') return 'profile:write';
  if (pathname.startsWith('/v1/campaigns')) return 'campaigns:manage'; if (pathname === '/v1/emergency-stop' || pathname === '/v1/emergency-stop/reset') return 'admin:emergency-stop'; if (pathname === '/v1/dashboard') return ['profile:read', 'campaigns:read', 'audit:read']; if (pathname === '/v1/chat' || pathname === '/v1/models' || pathname === '/v1/answers/prepare') return 'profile:read'; return undefined;
}
function authorizeSession(req: IncomingMessage, sessions: Sessions): void { const auth = req.headers.authorization; if (!auth?.startsWith('Bearer ') || !sessions.valid(auth.slice(7))) throw new HttpError(401, 'Paired extension session required'); }
function publicProfile(profile: CandidateProfile): CandidateProfile { return { ...profile, facts: profile.facts.filter((fact) => fact.path !== 'source.rawText') }; }
function safeDiagnostics(value: Record<string, unknown>): Record<string, unknown> { const allowed = new Set(['applicationId', 'jobId', 'sourceId', 'state', 'errors', 'status']); return sanitizeDiagnostics(Object.fromEntries(Object.entries(value).filter(([key]) => allowed.has(key)).map(([key, item]) => [key, Array.isArray(item) ? item.map((entry) => String(entry).slice(0, 500)).slice(0, 20) : typeof item === 'string' ? item.slice(0, 500) : item]))) as Record<string, unknown>; }
function approvedAnswerOverrides(values: unknown[]) { return values.map((value) => { const item = asRecord(value); return { ...(typeof item.fieldId === 'string' ? { fieldId: requiredString(item.fieldId, 'fieldId', 200) } : {}), ...(typeof item.label === 'string' ? { label: requiredString(item.label, 'label', 500) } : {}), value: requiredString(item.value, 'value', 5_000), approved: true as const }; }); }
async function readJson(req: IncomingMessage): Promise<unknown> { let size = 0; const chunks: Buffer[] = []; for await (const chunk of req) { const buffer = Buffer.from(chunk); size += buffer.length; if (size > MAX_BODY_BYTES) throw new HttpError(413, 'Request too large'); chunks.push(buffer); } return JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}'); }
function json(res: ServerResponse, status: number, body: unknown): void { if (res.headersSent) return; const value = JSON.stringify(body); res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'content-length': Buffer.byteLength(value) }); res.end(value); }
async function idempotentMutation<T>(store: Store, operation: string, body: Record<string, unknown>, run: () => Promise<T>): Promise<T> { if (body.idempotencyKey === undefined) return run(); const key = requiredString(body.idempotencyKey, 'idempotencyKey', 128); const request = { ...body }; delete request.idempotencyKey; const requestHash = createHash('sha256').update(stableRequestJson(request)).digest('hex'); const state = store.beginIdempotent(operation, key, requestHash); if (state === 'conflict') throw new HttpError(409, 'Idempotency key was already used with different input'); if (state !== 'started') { if (state.status === 'succeeded') return state.response as T; throw new HttpError(409, 'This operation is already in progress or requires review'); } try { const result = await run(); store.finishIdempotent(operation, key, 'succeeded', result); return result; } catch (error) { store.clearIdempotent(operation, key); throw error; } }
function stableRequestJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableRequestJson).join(',')}]`; if (value && typeof value === 'object') return `{${Object.entries(value as Record<string, unknown>).filter(([, item]) => item !== undefined).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => `${JSON.stringify(key)}:${stableRequestJson(item)}`).join(',')}}`; return JSON.stringify(value); }
function boundedNumber(value: unknown, field: string, min: number, max: number, fallback: number): number { const number = value === undefined ? fallback : Number(value); if (!Number.isFinite(number) || number < min || number > max) throw new ValidationError(`Invalid ${field}`); return number; }
async function extractResumeText(sourceName: string, base64: string): Promise<string> { const data = Buffer.from(base64, 'base64'); if (data.length > 4 * 1024 * 1024) throw new HttpError(413, 'Resume must be smaller than 4 MB'); if (!sourceName.toLowerCase().endsWith('.pdf')) return data.toString('utf8'); if (data.subarray(0, 4).toString() !== '%PDF') throw new ValidationError('Invalid PDF resume'); const { PDFParse } = await import('pdf-parse'); const parser = new PDFParse({ data }); try { const result = await parser.getText(); return requiredString(result.text, 'resume text', 200_000); } finally { await parser.destroy(); } }
