import { DatabaseSync } from 'node:sqlite';
import { createHash, randomUUID } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { AgentSettings, ApplicationState, AuditEvent, CandidateProfile, Job, JobCampaign } from '../../../packages/shared/src/domain.ts';
import type { ApprovalRequestRecord, PreparedApplicationRecord, WuzzufConnection } from '../../../packages/shared/src/wuzzuf.ts';
import { assertTransition } from '../../../packages/shared/src/validation.ts';
import { applyCoreMigrations, DurableQueue } from '../../../packages/persistence/src/index.ts';
import { createProfileSnapshot, hashProfileFacts, type ImmutableProfileSnapshot } from '../../../packages/profile-engine/src/index.ts';
import type { ClientScope } from '../../../packages/shared-contracts/src/index.ts';
import { secureHashEquals } from '../../../packages/security/src/index.ts';

export class Store {
  private readonly db: DatabaseSync;
  private readonly lockOwner = randomUUID();
  private readonly lockLeaseMs: number;
  readonly queue: DurableQueue;
  constructor(path: string, options: { lockLeaseMs?: number } = {}) { const directory = dirname(path); mkdirSync(directory, { recursive: true, mode: 0o700 }); chmodSync(directory, 0o700); this.db = new DatabaseSync(path); chmodSync(path, 0o600); this.lockLeaseMs = options.lockLeaseMs ?? 5 * 60_000; this.migrate(); for (const candidate of [path, `${path}-wal`, `${path}-shm`]) if (existsSync(candidate)) chmodSync(candidate, 0o600); this.queue = new DurableQueue(this.db); }
  private migrate(): void {
    this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
      CREATE TABLE IF NOT EXISTS profiles (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS campaigns (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, fingerprint TEXT UNIQUE NOT NULL, data TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS applications (id TEXT PRIMARY KEY, job_id TEXT NOT NULL, state TEXT NOT NULL, submission_key TEXT UNIQUE, data TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, correlation_id TEXT NOT NULL, application_id TEXT, at TEXT NOT NULL, data TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS resume_files (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, source_name TEXT NOT NULL, content BLOB NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS locks (key TEXT PRIMARY KEY, acquired_at TEXT NOT NULL, owner TEXT, expires_at TEXT);
      CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, data TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS wuzzuf_connections (user_id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS approval_requests (id TEXT PRIMARY KEY, application_id TEXT NOT NULL, binding_hash TEXT NOT NULL, status TEXT NOT NULL, expires_at TEXT NOT NULL, data TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS operation_idempotency (operation TEXT NOT NULL, key TEXT NOT NULL, request_hash TEXT NOT NULL, status TEXT NOT NULL, response TEXT, updated_at TEXT NOT NULL, PRIMARY KEY(operation, key));
      CREATE INDEX IF NOT EXISTS audit_correlation_idx ON audit_events(correlation_id, at);`);
    applyCoreMigrations(this.db);
    const lockColumns = new Set((this.db.prepare('PRAGMA table_info(locks)').all() as Array<{ name: string }>).map((column) => column.name));
    if (!lockColumns.has('owner')) this.db.exec('ALTER TABLE locks ADD COLUMN owner TEXT');
    if (!lockColumns.has('expires_at')) this.db.exec('ALTER TABLE locks ADD COLUMN expires_at TEXT');
    this.db.prepare("UPDATE locks SET owner=COALESCE(NULLIF(owner,''),'legacy'), expires_at=COALESCE(NULLIF(expires_at,''),acquired_at)").run();
    this.db.prepare('DELETE FROM locks WHERE expires_at<=?').run(new Date().toISOString());
    this.db.exec('CREATE TABLE IF NOT EXISTS campaign_daily_usage (campaign_id TEXT NOT NULL, day_key TEXT NOT NULL, count INTEGER NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(campaign_id,day_key));');
  }
  saveProfile(profile: CandidateProfile): void {
    const factsHash = hashProfileFacts(profile.facts); const versionKey = createHash('sha256').update(`${factsHash}:${JSON.stringify(profile.cvVariants)}`).digest('hex'); const existing = this.db.prepare('SELECT id FROM profile_versions WHERE profile_id=? AND facts_hash=? ORDER BY version DESC LIMIT 1').get(profile.id, versionKey) as { id: string } | undefined;
    this.db.prepare('INSERT INTO profiles VALUES (?, ?, ?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated_at=excluded.updated_at').run(profile.id, JSON.stringify(profile), profile.updatedAt);
    if (!existing) this.createSnapshot(profile, versionKey);
  }
  latestProfileSnapshot(profileId: string): ImmutableProfileSnapshot | undefined { const row = this.db.prepare('SELECT data FROM profile_snapshots WHERE profile_id=? ORDER BY created_at DESC LIMIT 1').get(profileId) as { data: string } | undefined; return row ? JSON.parse(row.data) as ImmutableProfileSnapshot : undefined; }
  listProfileSnapshots(profileId: string): ImmutableProfileSnapshot[] { return (this.db.prepare('SELECT data FROM profile_snapshots WHERE profile_id=? ORDER BY created_at, rowid').all(profileId) as Array<{ data: string }>).map((row) => JSON.parse(row.data) as ImmutableProfileSnapshot); }
  getProfile(id: string): CandidateProfile | undefined { const row = this.db.prepare('SELECT data FROM profiles WHERE id=?').get(id) as { data: string } | undefined; return row ? JSON.parse(row.data) as CandidateProfile : undefined; }
  listProfiles(): CandidateProfile[] { return (this.db.prepare('SELECT data FROM profiles ORDER BY updated_at DESC').all() as Array<{ data: string }>).map((r) => JSON.parse(r.data) as CandidateProfile); }
  saveResumeFile(profileId: string, resumeId: string, sourceName: string, content: Uint8Array): void { this.db.prepare('INSERT INTO resume_files VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET content=excluded.content, source_name=excluded.source_name').run(resumeId, profileId, sourceName, Buffer.from(content), new Date().toISOString()); const profile = this.getProfile(profileId); if (profile) this.createSnapshot(profile, createHash('sha256').update(`${hashProfileFacts(profile.facts)}:${resumeId}:${createHash('sha256').update(content).digest('hex')}`).digest('hex'), { id: resumeId, content }); }
  getResumeFile(profileId: string, resumeId: string): { sourceName: string; content: Uint8Array } | undefined { const row = this.db.prepare('SELECT source_name, content FROM resume_files WHERE id=? AND profile_id=?').get(resumeId, profileId) as { source_name: string; content: Uint8Array } | undefined; return row ? { sourceName: row.source_name, content: row.content } : undefined; }
  saveAgentSettings(settings: AgentSettings): void { this.db.prepare('INSERT INTO settings VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET data=excluded.data').run('agents', JSON.stringify(settings)); }
  getAgentSettings(): AgentSettings | undefined { const row = this.db.prepare('SELECT data FROM settings WHERE key=?').get('agents') as { data: string } | undefined; return row ? JSON.parse(row.data) as AgentSettings : undefined; }
  saveCampaign(campaign: JobCampaign): void { this.db.prepare('INSERT INTO campaigns VALUES (?, ?, ?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated_at=excluded.updated_at').run(campaign.id, JSON.stringify(campaign), campaign.updatedAt); }
  getCampaign(id: string): JobCampaign | undefined { const row = this.db.prepare('SELECT data FROM campaigns WHERE id=?').get(id) as { data: string } | undefined; return row ? JSON.parse(row.data) as JobCampaign : undefined; }
  listCampaigns(): JobCampaign[] { return (this.db.prepare('SELECT data FROM campaigns ORDER BY updated_at DESC').all() as Array<{ data: string }>).map((r) => JSON.parse(r.data) as JobCampaign); }
  startCampaignRun(campaignId: string, correlationId: string): string { const id = createHash('sha256').update(`${campaignId}:${correlationId}`).digest('hex'); const now = new Date().toISOString(); this.db.prepare('INSERT INTO campaign_runs VALUES (?,?,?,?,?,?,?,?)').run(id, campaignId, 'running', correlationId, now, null, JSON.stringify({}), now); return id; }
  finishCampaignRun(id: string, status: 'completed' | 'failed', data: Record<string, unknown>): void { this.db.prepare('UPDATE campaign_runs SET status=?,completed_at=?,data=? WHERE id=?').run(status, new Date().toISOString(), JSON.stringify(data), id); }
  latestCampaignRunAt(campaignId: string): string | undefined { const row = this.db.prepare('SELECT created_at FROM campaign_runs WHERE campaign_id=? ORDER BY created_at DESC LIMIT 1').get(campaignId) as { created_at: string } | undefined; return row?.created_at; }
  saveJob(job: Job): boolean { try { this.db.prepare('INSERT INTO jobs VALUES (?, ?, ?)').run(job.id, job.fingerprint, JSON.stringify(job)); return true; } catch (e) { if (String(e).includes('UNIQUE')) return false; throw e; } }
  upsertJob(job: Job): Job { const existing = this.getJobBySource(job.source, job.sourceId); if (existing) { const updated = { ...job, id: existing.id, fingerprint: existing.fingerprint }; this.db.prepare('UPDATE jobs SET data=? WHERE id=?').run(JSON.stringify(updated), existing.id); return updated; } this.saveJob(job); return job; }
  getJob(id: string): Job | undefined { const row = this.db.prepare('SELECT data FROM jobs WHERE id=?').get(id) as { data: string } | undefined; return row ? JSON.parse(row.data) as Job : undefined; }
  getJobByUrl(url: string): Job | undefined { const rows = this.db.prepare('SELECT data FROM jobs').all() as Array<{ data: string }>; return rows.map((row) => JSON.parse(row.data) as Job).find((job) => job.url === url); }
  getJobBySource(source: string, sourceId: string): Job | undefined { const rows = this.db.prepare('SELECT data FROM jobs').all() as Array<{ data: string }>; return rows.map((row) => JSON.parse(row.data) as Job).find((job) => job.source === source && job.sourceId === sourceId); }
  createApplication(id: string, jobId: string, data: Record<string, unknown>): void { this.db.prepare('INSERT INTO applications VALUES (?, ?, ?, NULL, ?)').run(id, jobId, 'DISCOVERED', JSON.stringify(data)); }
  savePreparedApplication(record: PreparedApplicationRecord): void { this.db.prepare('INSERT INTO applications (id, job_id, state, submission_key, data) VALUES (?, ?, ?, NULL, ?) ON CONFLICT(id) DO UPDATE SET state=excluded.state, data=excluded.data').run(record.id, record.jobId, record.state, JSON.stringify(record)); if (record.state === 'SUBMITTED') this.db.prepare("UPDATE submission_attempts SET status='completed',result=?,updated_at=? WHERE application_id=? AND status='reserved'").run(JSON.stringify(record.submissionResult ?? { submitted: true }), new Date().toISOString(), record.id); if (record.state === 'FAILED_PERMANENT') this.db.prepare("UPDATE submission_attempts SET status='uncertain',result=?,updated_at=? WHERE application_id=? AND status='reserved'").run(JSON.stringify(record.errors.at(-1) ?? { code: 'INTERNAL_ERROR' }), new Date().toISOString(), record.id); }
  getPreparedApplication(id: string): PreparedApplicationRecord | undefined { const row = this.db.prepare('SELECT data, state FROM applications WHERE id=?').get(id) as { data: string; state: ApplicationState } | undefined; if (!row) return undefined; return { ...(JSON.parse(row.data) as PreparedApplicationRecord), state: row.state }; }
  getPreparedApplicationByJob(jobId: string): PreparedApplicationRecord | undefined { const row = this.db.prepare('SELECT data, state FROM applications WHERE job_id=? ORDER BY rowid DESC LIMIT 1').get(jobId) as { data: string; state: ApplicationState } | undefined; if (!row) return undefined; return { ...(JSON.parse(row.data) as PreparedApplicationRecord), state: row.state }; }
  transition(id: string, to: ApplicationState): void { const row = this.db.prepare('SELECT state FROM applications WHERE id=?').get(id) as { state: ApplicationState } | undefined; if (!row) throw new Error('Application not found'); assertTransition(row.state, to); this.db.prepare('UPDATE applications SET state=? WHERE id=?').run(to, id); this.recordApplicationTransition(id, row.state, to, randomCorrelation(), 'orchestrator'); }
  recordApplicationTransition(applicationId: string, previousState: ApplicationState, nextState: ApplicationState, correlationId: string, actor: string, detail: Record<string, unknown> = {}): void { const now = new Date().toISOString(); this.db.prepare('INSERT INTO application_events VALUES (?,?,?,?,?,?,?,?,?)').run(createHash('sha256').update(`${applicationId}:${previousState}:${nextState}:${now}:${Math.random()}`).digest('hex'), applicationId, previousState, nextState, correlationId, actor, JSON.stringify(detail), null, now); }
  reserveSubmission(id: string, key: string): boolean { try { const result = this.db.prepare('UPDATE applications SET submission_key=? WHERE id=? AND submission_key IS NULL').run(key, id); return result.changes === 1; } catch (e) { if (String(e).includes('UNIQUE')) return false; throw e; } }
  reserveSubmissionAttempt(applicationId: string, approvalId: string, key: string): boolean { this.db.exec('BEGIN IMMEDIATE'); try { const reserved = this.db.prepare('UPDATE applications SET submission_key=? WHERE id=? AND submission_key IS NULL').run(key, applicationId); if (reserved.changes !== 1) { this.db.exec('ROLLBACK'); return false; } const now = new Date().toISOString(); this.db.prepare('INSERT INTO submission_attempts VALUES (?,?,?,?,?,?,?,?)').run(createHash('sha256').update(key).digest('hex'), applicationId, approvalId, key, 'reserved', null, now, now); this.db.exec('COMMIT'); return true; } catch (error) { this.db.exec('ROLLBACK'); if (String(error).includes('UNIQUE')) return false; throw error; } }
  finishSubmissionAttempt(key: string, status: 'completed' | 'failed' | 'uncertain', result: unknown): void { this.db.prepare('UPDATE submission_attempts SET status=?,result=?,updated_at=? WHERE idempotency_key=?').run(status, JSON.stringify(result), new Date().toISOString(), key); }
  saveWuzzufConnection(record: WuzzufConnection): void { this.db.prepare('INSERT INTO wuzzuf_connections VALUES (?, ?, ?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data, updated_at=excluded.updated_at').run(record.userId, JSON.stringify(record), record.updatedAt); }
  getWuzzufConnection(userId: string): WuzzufConnection | undefined { const row = this.db.prepare('SELECT data FROM wuzzuf_connections WHERE user_id=?').get(userId) as { data: string } | undefined; return row ? JSON.parse(row.data) as WuzzufConnection : undefined; }
  saveApprovalRequest(record: ApprovalRequestRecord): void { this.db.prepare('INSERT INTO approval_requests VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET binding_hash=excluded.binding_hash, status=excluded.status, expires_at=excluded.expires_at, data=excluded.data').run(record.id, record.applicationId, record.bindingHash, record.status, record.expiresAt, JSON.stringify(record)); const revokedAt = ['rejected', 'invalidated'].includes(record.status) ? record.updatedAt : null; this.db.prepare('INSERT INTO submission_approvals (id,application_id,binding_hash,token_hash,expires_at,used_at,revoked_at,data,created_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET binding_hash=excluded.binding_hash,token_hash=excluded.token_hash,expires_at=excluded.expires_at,used_at=excluded.used_at,revoked_at=excluded.revoked_at,data=excluded.data').run(record.id, record.applicationId, record.bindingHash, record.nonceHash, record.expiresAt, record.usedAt ?? null, revokedAt, JSON.stringify(record), record.createdAt); }
  getApprovalRequest(id: string): ApprovalRequestRecord | undefined { const row = this.db.prepare('SELECT data, status FROM approval_requests WHERE id=?').get(id) as { data: string; status: ApprovalRequestRecord['status'] } | undefined; return row ? { ...(JSON.parse(row.data) as ApprovalRequestRecord), status: row.status } : undefined; }
  listApprovalRequests(status?: ApprovalRequestRecord['status']): ApprovalRequestRecord[] { const rows = status ? this.db.prepare('SELECT data, status FROM approval_requests WHERE status=? ORDER BY rowid DESC').all(status) : this.db.prepare('SELECT data, status FROM approval_requests ORDER BY rowid DESC').all(); return (rows as Array<{ data: string; status: ApprovalRequestRecord['status'] }>).map((row) => ({ ...(JSON.parse(row.data) as ApprovalRequestRecord), status: row.status })); }
  invalidateApprovalRequests(applicationId: string, exceptBinding?: string): void { const rows = this.db.prepare("SELECT data FROM approval_requests WHERE application_id=? AND status IN ('pending','approved')").all(applicationId) as Array<{ data: string }>; for (const row of rows) { const record = JSON.parse(row.data) as ApprovalRequestRecord; if (exceptBinding && record.bindingHash === exceptBinding) continue; record.status = 'invalidated'; record.updatedAt = new Date().toISOString(); this.saveApprovalRequest(record); } }
  beginIdempotent(operation: string, key: string, requestHash: string): { status: string; response?: unknown } | 'started' | 'conflict' { const row = this.db.prepare('SELECT request_hash, status, response FROM operation_idempotency WHERE operation=? AND key=?').get(operation, key) as { request_hash: string; status: string; response: string | null } | undefined; if (row) return row.request_hash !== requestHash ? 'conflict' : { status: row.status, ...(row.response ? { response: JSON.parse(row.response) as unknown } : {}) }; this.db.prepare('INSERT INTO operation_idempotency VALUES (?, ?, ?, ?, NULL, ?)').run(operation, key, requestHash, 'running', new Date().toISOString()); return 'started'; }
  finishIdempotent(operation: string, key: string, status: 'succeeded' | 'failed' | 'uncertain', response: unknown): void { this.db.prepare('UPDATE operation_idempotency SET status=?, response=?, updated_at=? WHERE operation=? AND key=?').run(status, JSON.stringify(response), new Date().toISOString(), operation, key); }
  clearIdempotent(operation: string, key: string): void { this.db.prepare('DELETE FROM operation_idempotency WHERE operation=? AND key=?').run(operation, key); }
  audit(event: AuditEvent): void { this.db.prepare('INSERT INTO audit_events VALUES (?, ?, ?, ?, ?)').run(event.id, event.correlationId, event.applicationId ?? null, event.at, JSON.stringify(event)); }
  timeline(correlationId?: string): AuditEvent[] { const rows = correlationId ? this.db.prepare('SELECT data FROM audit_events WHERE correlation_id=? ORDER BY at').all(correlationId) : this.db.prepare('SELECT data FROM audit_events ORDER BY at DESC LIMIT 200').all(); return (rows as Array<{ data: string }>).map((r) => JSON.parse(r.data) as AuditEvent); }
  applicationTimeline(applicationId: string): AuditEvent[] { return (this.db.prepare('SELECT data FROM audit_events WHERE application_id=? ORDER BY at').all(applicationId) as Array<{ data: string }>).map((row) => JSON.parse(row.data) as AuditEvent); }
  health(): { ok: true; migrationVersion: number } { const row = this.db.prepare('SELECT COALESCE(MAX(version),0) version FROM schema_migrations').get() as { version: number }; this.db.prepare('SELECT 1').get(); return { ok: true, migrationVersion: row.version }; }
  enrollClient(id: string, name: string, token: string, scopes: readonly ClientScope[], expiresAt?: string): void { const now = new Date().toISOString(); const tokenId = createHash('sha256').update(`client:${id}`).digest('hex'); this.db.prepare('INSERT INTO clients VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name').run(id, name, now); this.db.prepare('INSERT INTO auth_tokens VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET token_hash=excluded.token_hash,scopes=excluded.scopes,expires_at=excluded.expires_at,revoked_at=NULL').run(tokenId, id, createHash('sha256').update(token).digest('hex'), JSON.stringify(scopes), expiresAt ?? null, null, now); }
  authorizeClient(id: string, token: string, requiredScope?: ClientScope | readonly ClientScope[]): boolean { const row = this.db.prepare('SELECT token_hash,scopes,expires_at,revoked_at FROM auth_tokens WHERE client_id=? ORDER BY created_at DESC LIMIT 1').get(id) as { token_hash: string; scopes: string; expires_at: string | null; revoked_at: string | null } | undefined; if (!row || row.revoked_at || (row.expires_at && Date.parse(row.expires_at) <= Date.now()) || !secureHashEquals(token, row.token_hash)) return false; const scopes = JSON.parse(row.scopes) as ClientScope[]; const required = requiredScope ? Array.isArray(requiredScope) ? requiredScope : [requiredScope] : []; return required.every((scope) => scopes.includes(scope)); }
  acquireLock(key: string): boolean { const now = new Date(); const acquiredAt = now.toISOString(); const expiresAt = new Date(now.getTime() + this.lockLeaseMs).toISOString(); this.db.exec('BEGIN IMMEDIATE'); try { this.db.prepare('DELETE FROM locks WHERE expires_at IS NULL OR expires_at<=?').run(acquiredAt); const inserted = this.db.prepare('INSERT OR IGNORE INTO locks (key,acquired_at,owner,expires_at) VALUES (?,?,?,?)').run(key, acquiredAt, this.lockOwner, expiresAt); this.db.exec('COMMIT'); return inserted.changes === 1; } catch (error) { this.db.exec('ROLLBACK'); throw error; } }
  releaseLock(key: string): void { this.db.prepare('DELETE FROM locks WHERE key=? AND owner=?').run(key, this.lockOwner); }
  reserveCampaignApplication(campaignId: string, dayKey: string, maximum: number): boolean { if (!/^\d{4}-\d{2}-\d{2}$/.test(dayKey) || !Number.isInteger(maximum) || maximum < 1) throw new Error('Invalid campaign daily-limit reservation'); const now = new Date().toISOString(); this.db.exec('BEGIN IMMEDIATE'); try { this.db.prepare('INSERT OR IGNORE INTO campaign_daily_usage VALUES (?,?,0,?)').run(campaignId, dayKey, now); const result = this.db.prepare('UPDATE campaign_daily_usage SET count=count+1,updated_at=? WHERE campaign_id=? AND day_key=? AND count<?').run(now, campaignId, dayKey, maximum); this.db.exec('COMMIT'); return result.changes === 1; } catch (error) { this.db.exec('ROLLBACK'); throw error; } }
  private createSnapshot(profile: CandidateProfile, versionKey: string, resume?: { id: string; content: Uint8Array }): void { const row = this.db.prepare('SELECT COALESCE(MAX(version),0)+1 version FROM profile_versions WHERE profile_id=?').get(profile.id) as { version: number }; const snapshot = createProfileSnapshot(profile, row.version, resume); const versionId = createHash('sha256').update(`${profile.id}:${row.version}:${versionKey}`).digest('hex'); this.db.prepare('INSERT INTO profile_versions VALUES (?,?,?,?,?)').run(versionId, profile.id, snapshot.version, versionKey, snapshot.createdAt); for (const fact of snapshot.facts) this.db.prepare('INSERT INTO profile_facts VALUES (?,?,?)').run(fact.id, versionId, JSON.stringify(fact)); this.db.prepare('INSERT INTO profile_snapshots VALUES (?,?,?,?,?,?,?,?)').run(snapshot.id, profile.id, versionId, snapshot.resumeFileId ?? null, snapshot.resumeHash, snapshot.factsHash, JSON.stringify(snapshot), snapshot.createdAt); }
  close(): void { this.db.close(); }
}
function randomCorrelation(): string { return createHash('sha256').update(`${Date.now()}:${Math.random()}`).digest('hex'); }
