import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { CandidateProfile, FieldAnswer, Job, JobCampaign } from '../../../packages/shared/src/domain.ts';
import { deduplicateJobs, normalizeJob, scoreJob } from '../../../packages/shared/src/jobs.ts';
import { assertTransition } from '../../../packages/shared/src/validation.ts';
import { WuzzufToolError, type ApprovalRequestRecord, type PreparedApplicationRecord, type WuzzufConnection, type WuzzufConnectionStatus, type WuzzufSearchInput } from '../../../packages/shared/src/wuzzuf.ts';
import { isSensitiveField } from '../../../packages/profile-engine/src/index.ts';
import { WuzzufAdapter } from '../../../packages/site-adapters/src/wuzzuf-adapter.ts';
import type { Store } from './store.ts';
import type { FormFingerprint, QueueJobType } from '../../../packages/shared-contracts/src/index.ts';
import type { FormControlValue, FormField } from '../../../packages/site-adapters/src/index.ts';
import { secureHashEquals } from '../../../packages/security/src/index.ts';

interface SafetyController { readonly active: boolean; readonly signal: AbortSignal; assertRunning(): void }
interface AnswerService { readonly settings: { activeProfileId?: string; confidenceThreshold: number; defaultDryRun: boolean }; prepareQuestions(labels: string[], profileId?: string): Promise<FieldAnswer[]>; audit(correlationId: string, type: string, detail: Record<string, unknown>, applicationId?: string): void }
export interface ApprovedAnswerOverride { fieldId?: string; label?: string; value: string; approved: true }

export class WuzzufToolService {
  private readonly controllers = new Map<string, AbortController>();
  private readonly userId = process.env.WUZZUF_USER_ID ?? 'local-user';
  readonly store: Store;
  readonly adapter: WuzzufAdapter;
  private readonly safety: SafetyController;
  private readonly answers: AnswerService;

  constructor(store: Store, adapter: WuzzufAdapter, safety: SafetyController, answers: AnswerService) { this.store = store; this.adapter = adapter; this.safety = safety; this.answers = answers; }

  async search(input: WuzzufSearchInput) {
    return this.queued('wuzzuf.search', redactedSearch(input), async () => { this.safety.assertRunning(); validateSearch(input); const correlationId = randomUUID(); this.answers.audit(correlationId, 'wuzzuf.search_started', redactedSearch(input)); const raw = await this.adapter.discover(input); const normalized = raw.map(normalizeJob); const { unique, duplicateIds } = deduplicateJobs(normalized); const jobs = unique.map((job) => this.store.upsertJob(job)); this.answers.audit(correlationId, 'wuzzuf.search_completed', { discovered: raw.length, unique: jobs.length, duplicates: duplicateIds.length }); return { correlationId, jobs }; });
  }

  async details(url: string) { return this.queued('wuzzuf.fetch-details', { url: this.adapter.normalizeUrl(url) }, async () => { this.safety.assertRunning(); const correlationId = randomUUID(); const job = this.store.upsertJob(await this.adapter.readJob(new URL(this.adapter.normalizeUrl(url)))); this.answers.audit(correlationId, 'wuzzuf.job_details_read', { jobId: job.id, sourceId: job.sourceId }); return { correlationId, job }; }); }

  async score(input: { jobId?: string; url?: string; profileId?: string }) {
    this.safety.assertRunning(); const correlationId = randomUUID(); const job = await this.resolveJob(input); const profile = this.profile(input.profileId); const campaign = scoringCampaign(profile, job);
    const scored = scoreJob(job, profile, campaign); this.store.upsertJob(scored); const required = job.requiredSkills ?? []; const profileSkills = profile.facts.filter((fact) => fact.path.startsWith('skills.')).map((fact) => String(fact.value)); const matchingSkills = required.filter((skill) => profileSkills.some((value) => fuzzySkill(value, skill))); const missingSkills = required.filter((skill) => !matchingSkills.includes(skill)); const confidence = required.length ? Math.min(1, 0.65 + required.length * 0.04) : 0.55;
    this.answers.audit(correlationId, 'wuzzuf.job_scored', { jobId: scored.id, score: scored.matchScore, profileId: profile.id }); return { correlationId, jobId: scored.id, score: scored.matchScore, matchingSkills, missingSkills, explanation: scored.scoreExplanation, confidence, recommendation: scored.matchScore >= 80 ? 'prepare_application' : scored.matchScore >= 60 ? 'review' : 'skip' };
  }

  prepare(input: { jobId?: string; url?: string; profileId?: string; dryRun?: boolean; idempotencyKey?: string }) { return this.queued('wuzzuf.prepare-application', { jobId: input.jobId, dryRun: input.dryRun ?? true }, () => this.idempotent('prepare', input.idempotencyKey, input, () => this.prepareOnce(input))); }
  private async prepareOnce(input: { jobId?: string; url?: string; profileId?: string; dryRun?: boolean }) {
    this.safety.assertRunning(); const job = await this.resolveJob(input); const profile = this.profile(input.profileId); const dryRun = input.dryRun ?? true; const correlationId = randomUUID(); const lock = `application:prepare:${job.fingerprint}`;
    if (!this.store.acquireLock(lock)) throw new WuzzufToolError('WUZZUF_APPLICATION_LOCKED', 'An application for this job is already being prepared', { status: 409, retryable: true });
    let pendingSessionId: string | undefined;
    try {
      const existing = this.store.getPreparedApplicationByJob(job.id); if (existing && existing.state !== 'CANCELLED') throw new WuzzufToolError('WUZZUF_DUPLICATE_APPLICATION', 'An application for this job already exists', { status: 409, diagnostics: { applicationId: existing.id } });
      const controller = new AbortController(); const signal = AbortSignal.any([controller.signal, this.safety.signal]); const browserSession = await this.adapter.startApplication(job, { correlationId, dryRun, signal }); pendingSessionId = browserSession.id; const fields = await this.adapter.collectFields(browserSession); const answers = await this.answers.prepareQuestions(fields.map((field) => field.label), profile.id); answers.forEach((answer, index) => { answer.fieldId = fields[index]?.id ?? answer.fieldId; });
      const selectedResume = profile.cvVariants.find((resume) => resume.approved); const snapshot = this.store.latestProfileSnapshot(profile.id); const now = new Date().toISOString(); const formFingerprint = fingerprint(this.adapter.normalizeUrl(job.url), fields); const record: PreparedApplicationRecord = { id: randomUUID(), correlationId, jobId: job.id, job, profileId: profile.id, formFingerprint, ...(snapshot ? { profileSnapshotId: snapshot.id, resumeHash: snapshot.resumeHash, factsHash: snapshot.factsHash } : {}), ...(selectedResume ? { selectedResume, resumeFileId: selectedResume.id } : {}), answers, filledFields: [], skippedFields: [], validationErrors: [], sensitiveFields: answers.filter((answer) => isSensitiveField(answer.label)).map((answer) => answer.label), screenshots: [], state: 'DISCOVERED', dryRun, submissionAllowed: false, lastSuccessfulStep: 'discovered', errors: [], createdAt: now, updatedAt: now, adapterSessionId: browserSession.id };
      advance(record, ['NORMALIZED', 'DEDUPLICATED', 'SCORED', 'SELECTED', 'APPLICATION_STARTED', 'QUESTIONS_EXTRACTED', 'ANSWERS_PREPARED', 'WAITING_FOR_APPROVAL']); record.reviewRevision = this.bindingHash(record); this.store.savePreparedApplication(record); this.controllers.set(record.id, controller); this.answers.audit(correlationId, 'wuzzuf.application_prepared', { jobId: job.id, dryRun, answerCount: answers.length, sensitiveCount: record.sensitiveFields.length, approvedResume: !!selectedResume }, record.id); pendingSessionId = undefined; return this.review(record.id);
    } catch (error) { if (pendingSessionId) await this.adapter.cancel(pendingSessionId); throw error; } finally { this.store.releaseLock(lock); }
  }

  fill(input: { applicationId: string; approvedAnswerOverrides?: ApprovedAnswerOverride[]; dryRun?: boolean; idempotencyKey?: string }) { return this.queued('wuzzuf.fill-application', { applicationId: input.applicationId, dryRun: input.dryRun ?? true }, () => this.idempotent('fill', input.idempotencyKey, input, () => this.fillOnce(input))); }
  private async fillOnce(input: { applicationId: string; approvedAnswerOverrides?: ApprovedAnswerOverride[]; dryRun?: boolean }) {
    this.safety.assertRunning(); const record = this.application(input.applicationId); if (terminal(record.state)) throw new WuzzufToolError('WUZZUF_INVALID_APPLICATION_STATE', `Cannot fill application in ${record.state}`, { status: 409 }); const dryRun = input.dryRun ?? true; const signal = this.signal(record.id); const overrides = input.approvedAnswerOverrides ?? [];
    await this.assertFormUnchanged(record);
    const answers = record.answers.map((answer) => { const override = overrides.find((item) => item.fieldId === answer.fieldId || item.label === answer.label); if (!override || isSensitiveField(answer.label)) return answer; return { ...answer, value: override.value, confidence: 1, confirmationRequired: false, reason: 'Explicitly approved answer override' }; });
    advance(record, ['FILLING']); const result = await this.adapter.fillFields(this.browserSession(record), answers, { correlationId: record.correlationId, dryRun, signal }); let resumeUploaded = false;
    if (!dryRun && record.selectedResume?.approved) { const file = this.store.getResumeFile(record.profileId, record.selectedResume.id); if (file) resumeUploaded = (await this.adapter.uploadApprovedFile(this.browserSession(record), { id: record.selectedResume.id, approved: true, sourceName: file.sourceName, content: file.content })).uploaded; }
    record.answers = answers; record.filledFields = [...result.filled, ...(resumeUploaded ? ['Approved resume'] : [])]; record.skippedFields = [...new Set([...result.skipped, ...record.sensitiveFields, ...(record.selectedResume?.approved ? [] : ['Approved resume'])])]; record.dryRun = record.dryRun || dryRun; advance(record, ['VALIDATING']); const validation = await this.adapter.validate(this.browserSession(record)); record.validationErrors = validation.errors; if (!dryRun) { const values = await this.adapter.collectFieldValues(this.browserSession(record)); const mismatches = filledValueMismatches(answers, result.filled, values); if (mismatches.length) { advance(record, ['FORM_CHANGED']); record.submissionAllowed = false; this.store.invalidateApprovalRequests(record.id); this.save(record); throw new WuzzufToolError('FORM_VALUES_MISMATCH', 'The browser form values do not match the reviewed answers.', { status: 409, diagnostics: { fields: mismatches }, actionRequired: 'Prepare and review the application again.' }); } record.formValueHash = formValueHash(values); } if (validation.valid) advance(record, ['READY_TO_SUBMIT']); else record.lastSuccessfulStep = 'validation_failed'; record.submissionAllowed = validation.valid && !record.dryRun && record.skippedFields.length === 0 && record.selectedResume?.approved === true && !!record.formValueHash && !this.safety.active;
    try { record.screenshots.push(await this.adapter.screenshot(record.adapterSessionId!, 'review')); } catch { /* diagnostics must not alter form state */ }
    record.reviewRevision = this.bindingHash(record); this.store.invalidateApprovalRequests(record.id, record.reviewRevision); this.save(record); this.answers.audit(record.correlationId, validation.valid ? 'wuzzuf.application_filled' : 'wuzzuf.application_validation_failed', { filled: record.filledFields, skipped: record.skippedFields, validationErrors: validation.errors, dryRun, resumeUploaded }, record.id); return this.review(record.id);
  }

  review(applicationId: string) { const record = this.application(applicationId); return { ...publicRecord(record), auditTimeline: this.store.applicationTimeline(applicationId) }; }
  status(applicationId: string) { const record = this.application(applicationId); return { applicationId: record.id, state: record.state, lastSuccessfulStep: record.lastSuccessfulStep, errors: record.errors, timestamps: { createdAt: record.createdAt, updatedAt: record.updatedAt, submittedAt: record.submittedAt }, correlationId: record.correlationId, submissionResult: record.submissionResult }; }

  requestSubmissionApproval(input: { applicationId: string; ttlSeconds?: number; idempotencyKey?: string }) {
    return this.idempotentSync('approval-request', input.idempotencyKey, input, () => {
      this.safety.assertRunning(); const record = this.application(input.applicationId); this.assertReadyForApproval(record); const now = new Date(); const bindingHash = this.bindingHash(record); this.store.invalidateApprovalRequests(record.id, bindingHash);
      const request: ApprovalRequestRecord = { id: randomUUID(), applicationId: record.id, bindingHash, nonceHash: hash(randomBytes(24).toString('base64url')), status: 'pending', expiresAt: new Date(now.getTime() + Math.max(30, Math.min(input.ttlSeconds ?? 120, 300)) * 1000).toISOString(), createdAt: now.toISOString(), updatedAt: now.toISOString() };
      this.store.saveApprovalRequest(request); this.answers.audit(record.correlationId, 'wuzzuf.submission_approval_requested', { approvalRequestId: request.id, expiresAt: request.expiresAt }, record.id); return this.publicApproval(request, record);
    });
  }

  decideApproval(requestId: string, approved: boolean) {
    const request = this.approvalRequest(requestId); const record = this.application(request.applicationId); if (request.status !== 'pending') throw new WuzzufToolError('WUZZUF_APPROVAL_NOT_PENDING', `Approval request is ${request.status}`, { status: 409 });
    if (Date.parse(request.expiresAt) <= Date.now()) { request.status = 'expired'; request.updatedAt = new Date().toISOString(); this.store.saveApprovalRequest(request); throw new WuzzufToolError('WUZZUF_APPROVAL_EXPIRED', 'Approval request expired', { status: 409 }); }
    if (request.bindingHash !== this.bindingHash(record)) { request.status = 'invalidated'; request.updatedAt = new Date().toISOString(); this.store.saveApprovalRequest(request); throw new WuzzufToolError('WUZZUF_APPROVAL_INVALIDATED', 'The reviewed application changed; request a new approval.', { status: 409 }); }
    const now = new Date().toISOString(); const approvalToken = approved ? randomBytes(32).toString('base64url') : undefined; request.status = approved ? 'approved' : 'rejected'; if (approvalToken) request.nonceHash = hash(approvalToken); request.decidedAt = now; request.updatedAt = now; this.store.saveApprovalRequest(request); this.answers.audit(record.correlationId, approved ? 'wuzzuf.submission_approval_granted' : 'wuzzuf.submission_approval_rejected', { approvalRequestId: request.id }, record.id); return { ...this.publicApproval(request, record), ...(approvalToken ? { approvalToken } : {}) };
  }
  pendingApprovals() { return this.store.listApprovalRequests('pending').map((request) => this.publicApproval(request, this.application(request.applicationId))); }

  submit(input: { applicationId: string; approvalRequestId: string; approvalToken?: string; idempotencyKey?: string }) { return this.queued('wuzzuf.submit-application', { applicationId: input.applicationId, approvalRequestId: input.approvalRequestId }, () => this.idempotentSubmission(input)); }
  private async submitOnce(input: { applicationId: string; approvalRequestId: string; approvalToken?: string }) {
    this.safety.assertRunning(); const record = this.application(input.applicationId); if (record.submissionResult?.submitted) return { applicationId: record.id, correlationId: record.correlationId, ...record.submissionResult, submittedAt: record.submissionResult.at }; if (record.dryRun) throw new WuzzufToolError('WUZZUF_DRY_RUN_BLOCKED', 'Dry-run applications can never submit', { status: 409 }); if (record.state !== 'READY_TO_SUBMIT') throw new WuzzufToolError('WUZZUF_NOT_READY_TO_SUBMIT', `Application is ${record.state}`, { status: 409 }); const lock = `application:submit:${record.id}`; if (!this.store.acquireLock(lock)) throw new WuzzufToolError('WUZZUF_APPLICATION_LOCKED', 'Application submission is already active', { status: 409 });
    let clickStarted = false; let submissionKey: string | undefined;
    try {
      const approval = this.approvalRequest(input.approvalRequestId); this.assertApproval(approval, record, input.approvalToken); await this.assertFormUnchanged(record); await this.assertFormValuesUnchanged(record); const validation = await this.adapter.validate(this.browserSession(record)); if (!validation.valid) throw new WuzzufToolError('WUZZUF_VALIDATION_FAILED', 'Application became invalid before submission', { status: 409, diagnostics: { errors: validation.errors } });
      submissionKey = hash(`${record.id}:${record.job.fingerprint}:${this.bindingHash(record)}`); if (!this.store.reserveSubmissionAttempt(record.id, approval.id, submissionKey)) throw new WuzzufToolError('DUPLICATE_SUBMISSION_PREVENTED', 'Submission has already been reserved; review its result before retrying.', { status: 409 }); this.markApprovalUsed(approval); advance(record, ['SUBMITTING']); this.save(record); this.answers.audit(record.correlationId, 'wuzzuf.submission_started', { jobId: record.jobId }, record.id);
      const result = await this.adapter.submit(this.browserSession(record), { correlationId: record.correlationId, dryRun: false, signal: this.signal(record.id), onSubmitStarted: () => { clickStarted = true; } }); advance(record, ['SUBMITTED']); record.submittedAt = new Date().toISOString(); record.submissionResult = { ...result, at: record.submittedAt }; record.submissionAllowed = false; const sessionId = record.adapterSessionId; delete record.adapterSessionId; this.save(record); clickStarted = false; this.answers.audit(record.correlationId, 'wuzzuf.submission_completed', { submitted: result.submitted, confirmation: result.confirmation }, record.id); if (sessionId) await this.adapter.cancel(sessionId); this.controllers.delete(record.id); return { applicationId: record.id, correlationId: record.correlationId, ...result, submittedAt: record.submittedAt };
    } catch (error) {
      const code = clickStarted ? 'WUZZUF_SUBMISSION_OUTCOME_UNKNOWN' : error instanceof WuzzufToolError ? error.code : 'WUZZUF_SUBMISSION_FAILED'; const message = clickStarted ? 'Submission was attempted, but its outcome could not be confirmed. Review Wuzzuf manually; it will not be retried.' : error instanceof Error ? error.message : 'Submission failed'; record.errors.push({ code, message, at: new Date().toISOString() }); if (clickStarted) advance(record, ['FAILED_PERMANENT']); this.save(record); this.answers.audit(record.correlationId, 'wuzzuf.submission_rejected', { code }, record.id); if (clickStarted) throw new WuzzufToolError(code, message, { status: 409, actionRequired: 'Review the application in Wuzzuf manually.' }); throw error;
    } finally { this.store.releaseLock(lock); }
  }

  cancel(input: string | { applicationId: string; idempotencyKey?: string }) {
    const value = typeof input === 'string' ? { applicationId: input } : input;
    return this.idempotent('cancel', value.idempotencyKey, value, async () => { const record = this.application(value.applicationId); if (terminal(record.state)) return this.status(value.applicationId); this.controllers.get(value.applicationId)?.abort(new Error('Application cancelled')); if (record.adapterSessionId) await this.adapter.cancel(record.adapterSessionId); advance(record, ['CANCELLED']); record.submissionAllowed = false; this.store.invalidateApprovalRequests(record.id); this.save(record); this.answers.audit(record.correlationId, 'wuzzuf.application_cancelled', {}, record.id); return this.status(record.id); });
  }

  authStatus() { const correlationId = randomUUID(); const connection = this.connection(); return { correlationId, ...connection, authenticated: connection.status === 'authenticated', code: connectionCode(connection.status), browser: this.adapter.browserStatus() }; }
  async verifyConnection() { const correlationId = randomUUID(); try { const status = await this.adapter.authenticationStatus(this.safety.signal); const previous = this.connection(); const mapped: WuzzufConnectionStatus = status.authenticated ? 'authenticated' : status.code === 'WUZZUF_CHALLENGE_REQUIRED' ? 'security_check_required' : previous.status === 'authenticated' ? 'expired' : 'expired'; const connection = this.saveConnection(mapped, true); return { correlationId, ...connection, authenticated: mapped === 'authenticated', code: connectionCode(mapped) }; } catch (error) { this.saveConnection('browser_required', false); throw error; } }
  async createConnection() { await this.openLogin(); return this.verifyConnection(); }
  async disconnect() { await this.adapter.disconnect(); const connection = this.saveConnection('disconnected', false); return { correlationId: randomUUID(), ...connection, authenticated: false, code: connectionCode(connection.status) }; }
  browserStatus() { return this.adapter.browserStatus(); }
  async openLogin() { const correlationId = randomUUID(); const result = await this.adapter.openLogin(); this.saveConnection(result.status === 'manual_verification_required' ? 'security_check_required' : 'expired', false); this.answers.audit(correlationId, 'wuzzuf.login_browser_opened', {}); return { correlationId, ...result }; }
  async close() { for (const controller of this.controllers.values()) controller.abort(); this.controllers.clear(); await this.adapter.close(); }

  private async resolveJob(input: { jobId?: string; url?: string }): Promise<Job> { if (input.jobId) { const job = this.store.getJob(input.jobId); if (!job) throw new WuzzufToolError('WUZZUF_JOB_NOT_FOUND', 'Job was not found', { status: 404 }); return job; } if (!input.url) throw new WuzzufToolError('WUZZUF_JOB_REFERENCE_REQUIRED', 'Provide jobId or url'); const normalized = this.adapter.normalizeUrl(input.url); const stored = this.store.getJobByUrl(normalized); return stored ?? this.store.upsertJob(await this.adapter.readJob(new URL(normalized))); }
  private profile(profileId?: string): CandidateProfile { const id = profileId ?? this.answers.settings.activeProfileId; const profile = id ? this.store.getProfile(id) : this.store.listProfiles()[0]; if (!profile) throw new WuzzufToolError('WUZZUF_PROFILE_REQUIRED', 'Import a candidate profile first', { status: 409 }); return profile; }
  private application(id: string): PreparedApplicationRecord { const record = this.store.getPreparedApplication(id); if (!record?.job) throw new WuzzufToolError('WUZZUF_APPLICATION_NOT_FOUND', 'Application was not found', { status: 404 }); return record; }
  private browserSession(record: PreparedApplicationRecord) { if (!record.adapterSessionId) throw new WuzzufToolError('WUZZUF_APPLICATION_SESSION_NOT_FOUND', 'Application browser session is no longer active; prepare again', { status: 409 }); return { id: record.adapterSessionId, url: record.job.url }; }
  private signal(id: string) { const controller = this.controllers.get(id); if (!controller) throw new WuzzufToolError('WUZZUF_APPLICATION_SESSION_NOT_FOUND', 'Application browser session is no longer active; prepare again', { status: 409 }); return AbortSignal.any([controller.signal, this.safety.signal]); }
  private save(record: PreparedApplicationRecord) { record.updatedAt = new Date().toISOString(); this.store.savePreparedApplication(record); }
  private connection(): WuzzufConnection { const existing = this.store.getWuzzufConnection(this.userId); if (existing) return existing; const now = new Date().toISOString(); return { id: randomUUID(), userId: this.userId, status: 'disconnected', createdAt: now, updatedAt: now }; }
  private saveConnection(status: WuzzufConnectionStatus, verified: boolean): WuzzufConnection { const existing = this.connection(); const now = new Date().toISOString(); const record: WuzzufConnection = { ...existing, status, updatedAt: now, ...(verified ? { lastVerifiedAt: now } : {}) }; this.store.saveWuzzufConnection(record); return record; }
  private assertReadyForApproval(record: PreparedApplicationRecord) { if (record.state !== 'READY_TO_SUBMIT') throw new WuzzufToolError('WUZZUF_NOT_READY_TO_SUBMIT', 'Application must be filled and valid before approval', { status: 409 }); if (record.dryRun) throw new WuzzufToolError('WUZZUF_DRY_RUN_BLOCKED', 'Disable dry-run and refill before requesting approval', { status: 409 }); if (record.skippedFields.length || record.validationErrors.length) throw new WuzzufToolError('WUZZUF_REVIEW_INCOMPLETE', 'Resolve skipped fields and validation errors before approval', { status: 409 }); }
  private async assertFormUnchanged(record: PreparedApplicationRecord): Promise<void> { if (!record.formFingerprint) return; const current = fingerprint(this.adapter.normalizeUrl(record.job.url), await this.adapter.collectFields(this.browserSession(record))); if (current.formVersion === record.formFingerprint.formVersion) return; this.invalidateChangedForm(record, 'FORM_CHANGED', 'The Wuzzuf application form changed after review.'); }
  private async assertFormValuesUnchanged(record: PreparedApplicationRecord): Promise<void> { const current = formValueHash(await this.adapter.collectFieldValues(this.browserSession(record))); if (record.formValueHash === current) return; this.invalidateChangedForm(record, 'FORM_VALUES_CHANGED', 'The Wuzzuf application values changed after review.'); }
  private invalidateChangedForm(record: PreparedApplicationRecord, code: string, message: string): never { advance(record, ['FORM_CHANGED']); record.submissionAllowed = false; this.store.invalidateApprovalRequests(record.id); this.save(record); throw new WuzzufToolError(code, message, { status: 409, diagnostics: { applicationId: record.id, state: record.state }, actionRequired: 'Prepare and review the application again.' }); }
  private bindingHash(record: PreparedApplicationRecord): string { return hash(stableJson({ applicationId: record.id, jobFingerprint: record.job.fingerprint, profileSnapshotId: record.profileSnapshotId ?? null, resumeId: record.selectedResume?.id ?? null, resumeHash: record.resumeHash ?? null, factsHash: record.factsHash ?? null, formVersion: record.formFingerprint?.formVersion ?? null, formValueHash: record.formValueHash ?? null, answers: record.answers.map((answer) => ({ fieldId: answer.fieldId, label: answer.label, value: answer.value, confidence: answer.confidence, confirmationRequired: answer.confirmationRequired })), filledFields: record.filledFields, skippedFields: record.skippedFields, validationErrors: record.validationErrors, dryRun: record.dryRun })); }
  private approvalRequest(id: string): ApprovalRequestRecord { const request = this.store.getApprovalRequest(id); if (!request) throw new WuzzufToolError('WUZZUF_APPROVAL_REQUIRED', 'A current human-approved submission request is required.', { status: 403, actionRequired: 'Request approval and confirm it in the extension.' }); return request; }
  private assertApproval(request: ApprovalRequestRecord, record: PreparedApplicationRecord, approvalToken?: string) { if (request.applicationId !== record.id || request.status !== 'approved' || !approvalToken || !secureHashEquals(approvalToken, request.nonceHash)) throw new WuzzufToolError('APPROVAL_REQUIRED', 'A valid one-use approval token from the paired extension is required.', { status: 403, actionRequired: 'Confirm a current approval request in the extension.' }); if (Date.parse(request.expiresAt) <= Date.now()) { request.status = 'expired'; request.updatedAt = new Date().toISOString(); this.store.saveApprovalRequest(request); throw new WuzzufToolError('APPROVAL_EXPIRED', 'Approval request expired.', { status: 403 }); } if (request.bindingHash !== this.bindingHash(record)) { request.status = 'invalidated'; request.updatedAt = new Date().toISOString(); this.store.saveApprovalRequest(request); throw new WuzzufToolError('APPROVAL_INVALIDATED', 'The application changed after approval.', { status: 409, actionRequired: 'Review the changes and request approval again.' }); } }
  private markApprovalUsed(request: ApprovalRequestRecord) { request.status = 'used'; request.usedAt = new Date().toISOString(); request.updatedAt = request.usedAt; this.store.saveApprovalRequest(request); }
  private publicApproval(request: ApprovalRequestRecord, record: PreparedApplicationRecord) { return { id: request.id, applicationId: request.applicationId, status: request.status, expiresAt: request.expiresAt, createdAt: request.createdAt, updatedAt: request.updatedAt, job: { id: record.job.id, title: record.job.title, employer: record.job.employer, fingerprint: record.job.fingerprint }, resume: record.selectedResume ? { id: record.selectedResume.id, name: record.selectedResume.name, sourceName: record.selectedResume.sourceName } : null, answers: record.answers.map((answer) => ({ fieldId: answer.fieldId, label: answer.label, value: answer.value, confirmationRequired: answer.confirmationRequired })), blockers: [...record.skippedFields, ...record.validationErrors] }; }
  private async queued<T>(type: QueueJobType, payload: unknown, run: () => Promise<T>): Promise<T> { this.safety.assertRunning(); const queued = this.store.queue.enqueue(type, payload); const workerId = `orchestrator-inline:${process.pid}`; if (!this.store.queue.claimById(queued.id, workerId)) throw new WuzzufToolError('WORKFLOW_STATE_CONFLICT', 'The durable browser job could not be claimed.', { status: 409, retryable: true }); try { const result = await run(); this.store.queue.complete(queued.id, workerId); return result; } catch (error) { const retryable = error instanceof WuzzufToolError && error.retryable; this.store.queue.fail(queued.id, workerId, error instanceof WuzzufToolError ? error.code : 'INTERNAL_ERROR', retryable); throw error; } }
  private async idempotent<T>(operation: string, suppliedKey: string | undefined, input: unknown, run: () => Promise<T>): Promise<T> { const { key, requestHash } = idempotency(operation, suppliedKey, input); const state = this.store.beginIdempotent(operation, key, requestHash); if (state === 'conflict') throw new WuzzufToolError('WUZZUF_IDEMPOTENCY_CONFLICT', 'Idempotency key was already used with different input.', { status: 409 }); if (state !== 'started') { if (state.status === 'succeeded') return state.response as T; throw new WuzzufToolError('WUZZUF_OPERATION_IN_PROGRESS', 'This operation is already running or requires review.', { status: 409, retryable: state.status === 'running' }); } try { const result = await run(); this.store.finishIdempotent(operation, key, 'succeeded', result); return result; } catch (error) { this.store.clearIdempotent(operation, key); throw error; } }
  private idempotentSync<T>(operation: string, suppliedKey: string | undefined, input: unknown, run: () => T): T { const { key, requestHash } = idempotency(operation, suppliedKey, input); const state = this.store.beginIdempotent(operation, key, requestHash); if (state === 'conflict') throw new WuzzufToolError('WUZZUF_IDEMPOTENCY_CONFLICT', 'Idempotency key was already used with different input.', { status: 409 }); if (state !== 'started') { if (state.status === 'succeeded') return state.response as T; throw new WuzzufToolError('WUZZUF_OPERATION_IN_PROGRESS', 'This operation is already running.', { status: 409, retryable: true }); } try { const result = run(); this.store.finishIdempotent(operation, key, 'succeeded', result); return result; } catch (error) { this.store.clearIdempotent(operation, key); throw error; } }
  private async idempotentSubmission(input: { applicationId: string; approvalRequestId: string; idempotencyKey?: string }) { const { key, requestHash } = idempotency('submit', input.idempotencyKey, input); const state = this.store.beginIdempotent('submit', key, requestHash); if (state === 'conflict') throw new WuzzufToolError('WUZZUF_IDEMPOTENCY_CONFLICT', 'Idempotency key was already used with different input.', { status: 409 }); if (state !== 'started') { if (state.status === 'succeeded') return state.response; if (state.status === 'uncertain') throw new WuzzufToolError('WUZZUF_SUBMISSION_OUTCOME_UNKNOWN', 'Submission outcome is unknown and will not be retried.', { status: 409, actionRequired: 'Review Wuzzuf manually.' }); throw new WuzzufToolError('WUZZUF_OPERATION_IN_PROGRESS', 'Submission is already running.', { status: 409 }); } try { const result = await this.submitOnce(input); this.store.finishIdempotent('submit', key, 'succeeded', result); return result; } catch (error) { if (error instanceof WuzzufToolError && error.code === 'WUZZUF_SUBMISSION_OUTCOME_UNKNOWN') this.store.finishIdempotent('submit', key, 'uncertain', { code: error.code, message: error.message }); else this.store.clearIdempotent('submit', key); throw error; } }
}

function advance(record: PreparedApplicationRecord, states: PreparedApplicationRecord['state'][]): void { for (const state of states) { assertTransition(record.state, state); record.state = state; record.lastSuccessfulStep = state.toLowerCase(); } record.updatedAt = new Date().toISOString(); }
function terminal(state: PreparedApplicationRecord['state']): boolean { return ['SUBMITTED', 'CANCELLED', 'REJECTED_BY_USER', 'DUPLICATE', 'SKIPPED', 'FAILED_PERMANENT'].includes(state); }
function hash(value: string): string { return createHash('sha256').update(value).digest('hex'); }
function stableJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`; if (value && typeof value === 'object') return `{${Object.entries(value as Record<string, unknown>).filter(([, item]) => item !== undefined).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableJson(item)}`).join(',')}}`; return JSON.stringify(value); }
function idempotency(operation: string, suppliedKey: string | undefined, input: unknown) { const requestHash = hash(stableJson(input)); return { key: suppliedKey ?? hash(`${operation}:${requestHash}`), requestHash }; }
function connectionCode(status: WuzzufConnectionStatus) { return status === 'authenticated' ? 'AUTHENTICATED' : status === 'security_check_required' ? 'WUZZUF_CHALLENGE_REQUIRED' : status === 'expired' ? 'WUZZUF_LOGIN_REQUIRED' : status === 'browser_required' ? 'CHROME_CDP_REQUIRED' : 'WUZZUF_DISCONNECTED'; }
function validateSearch(input: WuzzufSearchInput): void { if (!input.queries?.length || input.queries.length > 10 || !input.locations?.length || input.locations.length > 10) throw new WuzzufToolError('WUZZUF_INVALID_SEARCH', 'queries and locations must contain 1–10 values'); if (input.limit !== undefined && (!Number.isInteger(input.limit) || input.limit < 1 || input.limit > 100)) throw new WuzzufToolError('WUZZUF_INVALID_SEARCH', 'limit must be between 1 and 100'); }
function redactedSearch(input: WuzzufSearchInput) { return { queryCount: input.queries.length, locationCount: input.locations.length, remote: input.remote, experienceLevel: input.experienceLevel, employmentTypes: input.employmentTypes, limit: input.limit }; }
function scoringCampaign(profile: CandidateProfile, job: Job): JobCampaign { const now = new Date().toISOString(); return { id: `wuzzuf-score-${job.id}`, name: 'Wuzzuf score', state: 'enabled', searchQueries: [job.title], locations: [job.location], workplace: job.remote ? ['remote'] : ['onsite'], includedKeywords: [], excludedKeywords: [], seniority: job.seniority ? [job.seniority] : [], minimumMatchScore: 0, allowedSites: ['wuzzuf'], maxApplicationsPerRun: 1, maxApplicationsPerDay: 1, executionMode: 'research_only', profileId: profile.id, cvStrategy: 'selected', providerId: 'local', model: 'deterministic', dryRun: true, createdAt: now, updatedAt: now }; }
function fuzzySkill(a: string, b: string): boolean { const clean = (value: string) => value.toLowerCase().replace(/[^a-z0-9+#.]+/g, ' ').trim(); return clean(a).includes(clean(b)) || clean(b).includes(clean(a)); }
function fingerprint(normalizedUrl: string, fields: FormField[]): FormFingerprint { const normalized = fields.map((field) => ({ label: field.label.trim().toLowerCase(), type: field.type, required: field.required, options: [...(field.options ?? [])].map((option) => option.trim().toLowerCase()).sort() })); const fieldsHash = hash(stableJson(normalized)); const submitControlHash = hash('wuzzuf:semantic-submit-control:v1'); return { normalizedUrl, fieldsHash, submitControlHash, formVersion: hash(`${normalizedUrl}:${fieldsHash}:${submitControlHash}`), capturedAt: new Date().toISOString() }; }
function formValueHash(values: FormControlValue[]): string { return hash(stableJson(values.map((item) => ({ id: item.id, type: item.type, value: item.value })).sort((a, b) => a.id.localeCompare(b.id)))); }
function filledValueMismatches(answers: FieldAnswer[], filledLabels: string[], values: FormControlValue[]): string[] { const controls = new Map(values.map((item) => [item.id, item])); return answers.filter((answer) => answer.fieldId && filledLabels.includes(answer.label)).flatMap((answer) => { const control = controls.get(answer.fieldId!); if (!control) return [answer.label]; let expected = String(answer.value); if (control.type === 'checkbox') { const parsed = /^(yes|true|checked|1)$/i.test(expected.trim()) ? true : /^(no|false|unchecked|0)$/i.test(expected.trim()) ? false : undefined; if (parsed === undefined) return [answer.label]; expected = String(parsed); } else if (control.type === 'radio') expected = 'true'; return control.value === expected ? [] : [answer.label]; }); }
function publicRecord(record: PreparedApplicationRecord) { const { adapterSessionId: _adapterSessionId, ...safe } = record; return safe; }
