import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { CandidateProfile, FieldAnswer, Job, JobCampaign } from '../../../packages/shared/src/domain.ts';
import { deduplicateJobs, normalizeJob, scoreJob } from '../../../packages/shared/src/jobs.ts';
import { assertTransition } from '../../../packages/shared/src/validation.ts';
import { WuzzufToolError, type PreparedApplicationRecord, type WuzzufSearchInput } from '../../../packages/shared/src/wuzzuf.ts';
import { isSensitiveField } from '../../../packages/profile-engine/src/index.ts';
import { WuzzufAdapter } from '../../../packages/site-adapters/src/wuzzuf-adapter.ts';
import { normalizeWuzzufUrl } from '../../../packages/site-adapters/src/wuzzuf-parser.ts';
import type { Store } from './store.ts';

interface SafetyController { readonly active: boolean; readonly signal: AbortSignal; assertRunning(): void }
interface AnswerService { readonly settings: { activeProfileId?: string; confidenceThreshold: number; defaultDryRun: boolean }; prepareQuestions(labels: string[], profileId?: string): Promise<FieldAnswer[]>; audit(correlationId: string, type: string, detail: Record<string, unknown>, applicationId?: string): void }
export interface ApprovedAnswerOverride { fieldId?: string; label?: string; value: string; approved: true }

export class WuzzufToolService {
  private readonly controllers = new Map<string, AbortController>();
  constructor(readonly store: Store, readonly adapter: WuzzufAdapter, private readonly safety: SafetyController, private readonly answers: AnswerService) {}

  async search(input: WuzzufSearchInput) {
    this.safety.assertRunning(); validateSearch(input); const correlationId = randomUUID(); this.answers.audit(correlationId, 'wuzzuf.search_started', redactedSearch(input));
    const raw = await this.adapter.discover(input); const normalized = raw.map(normalizeJob); const { unique, duplicateIds } = deduplicateJobs(normalized); const jobs = unique.map((job) => this.store.upsertJob(job));
    this.answers.audit(correlationId, 'wuzzuf.search_completed', { discovered: raw.length, unique: jobs.length, duplicates: duplicateIds.length }); return { correlationId, jobs };
  }

  async details(url: string) { this.safety.assertRunning(); const correlationId = randomUUID(); const job = this.store.upsertJob(await this.adapter.readJob(new URL(normalizeWuzzufUrl(url, this.baseUrl)))); this.answers.audit(correlationId, 'wuzzuf.job_details_read', { jobId: job.id, sourceId: job.sourceId }); return { correlationId, job }; }

  async score(input: { jobId?: string; url?: string; profileId?: string }) {
    this.safety.assertRunning(); const correlationId = randomUUID(); const job = await this.resolveJob(input); const profile = this.profile(input.profileId); const campaign = scoringCampaign(profile, job);
    const scored = scoreJob(job, profile, campaign); this.store.upsertJob(scored); const required = job.requiredSkills ?? []; const profileSkills = profile.facts.filter((fact) => fact.path.startsWith('skills.')).map((fact) => String(fact.value)); const matchingSkills = required.filter((skill) => profileSkills.some((value) => fuzzySkill(value, skill))); const missingSkills = required.filter((skill) => !matchingSkills.includes(skill)); const confidence = required.length ? Math.min(1, 0.65 + required.length * 0.04) : 0.55;
    this.answers.audit(correlationId, 'wuzzuf.job_scored', { jobId: scored.id, score: scored.matchScore, profileId: profile.id }); return { correlationId, jobId: scored.id, score: scored.matchScore, matchingSkills, missingSkills, explanation: scored.scoreExplanation, confidence, recommendation: scored.matchScore >= 80 ? 'prepare_application' : scored.matchScore >= 60 ? 'review' : 'skip' };
  }

  async prepare(input: { jobId?: string; url?: string; profileId?: string; dryRun?: boolean }) {
    this.safety.assertRunning(); const job = await this.resolveJob(input); const profile = this.profile(input.profileId); const dryRun = input.dryRun ?? true; const correlationId = randomUUID(); const lock = `application:prepare:${job.fingerprint}`;
    if (!this.store.acquireLock(lock)) throw new WuzzufToolError('WUZZUF_APPLICATION_LOCKED', 'An application for this job is already being prepared', { status: 409, retryable: true });
    try {
      const existing = this.store.getPreparedApplicationByJob(job.id); if (existing && existing.state !== 'CANCELLED') throw new WuzzufToolError('WUZZUF_DUPLICATE_APPLICATION', 'An application for this job already exists', { status: 409, diagnostics: { applicationId: existing.id } });
      const controller = new AbortController(); const signal = AbortSignal.any([controller.signal, this.safety.signal]); const browserSession = await this.adapter.startApplication(job, { correlationId, dryRun, signal }); const fields = await this.adapter.collectFields(browserSession); const answers = await this.answers.prepareQuestions(fields.map((field) => field.label), profile.id); answers.forEach((answer, index) => { answer.fieldId = fields[index]?.id ?? answer.fieldId; });
      const selectedResume = profile.cvVariants.find((resume) => resume.approved); const now = new Date().toISOString(); const record: PreparedApplicationRecord = { id: randomUUID(), correlationId, jobId: job.id, job, profileId: profile.id, ...(selectedResume ? { selectedResume } : {}), answers, filledFields: [], skippedFields: [], validationErrors: [], sensitiveFields: answers.filter((answer) => isSensitiveField(answer.label)).map((answer) => answer.label), screenshots: [], state: 'DISCOVERED', dryRun, submissionAllowed: false, lastSuccessfulStep: 'discovered', errors: [], createdAt: now, updatedAt: now, adapterSessionId: browserSession.id };
      advance(record, ['NORMALIZED', 'DEDUPLICATED', 'SCORED', 'SELECTED', 'APPLICATION_STARTED', 'QUESTIONS_EXTRACTED', 'ANSWERS_PREPARED', 'WAITING_FOR_APPROVAL']); this.store.savePreparedApplication(record); this.controllers.set(record.id, controller); this.answers.audit(correlationId, 'wuzzuf.application_prepared', { jobId: job.id, dryRun, answerCount: answers.length, sensitiveCount: record.sensitiveFields.length, approvedResume: !!selectedResume }, record.id); return this.review(record.id);
    } finally { this.store.releaseLock(lock); }
  }

  async fill(input: { applicationId: string; approvedAnswerOverrides?: ApprovedAnswerOverride[]; dryRun?: boolean }) {
    this.safety.assertRunning(); const record = this.application(input.applicationId); if (terminal(record.state)) throw new WuzzufToolError('WUZZUF_INVALID_APPLICATION_STATE', `Cannot fill application in ${record.state}`, { status: 409 }); const dryRun = input.dryRun ?? true; const signal = this.signal(record.id); const overrides = input.approvedAnswerOverrides ?? [];
    const answers = record.answers.map((answer) => { const override = overrides.find((item) => item.fieldId === answer.fieldId || item.label === answer.label); if (!override || isSensitiveField(answer.label)) return answer; return { ...answer, value: override.value, confidence: 1, confirmationRequired: false, reason: 'Explicitly approved answer override' }; });
    advance(record, ['FILLING']); const result = await this.adapter.fillFields(this.browserSession(record), answers, { correlationId: record.correlationId, dryRun, signal }); record.answers = answers; record.filledFields = result.filled; record.skippedFields = [...new Set([...result.skipped, ...record.sensitiveFields, ...(record.selectedResume?.approved ? [] : ['Approved resume'])])]; record.dryRun = record.dryRun || dryRun; advance(record, ['VALIDATING']); const validation = await this.adapter.validate(this.browserSession(record)); record.validationErrors = validation.errors; if (validation.valid) advance(record, ['READY_TO_SUBMIT']); else record.lastSuccessfulStep = 'validation_failed'; record.submissionAllowed = validation.valid && !record.dryRun && record.skippedFields.length === 0 && record.selectedResume?.approved === true && !this.safety.active; try { record.screenshots.push(await this.adapter.screenshot(record.adapterSessionId!, 'review')); } catch { /* screenshot failure does not change form state */ } this.save(record); this.answers.audit(record.correlationId, validation.valid ? 'wuzzuf.application_filled' : 'wuzzuf.application_validation_failed', { filled: result.filled, skipped: record.skippedFields, validationErrors: validation.errors, dryRun }, record.id); return this.review(record.id);
  }

  review(applicationId: string) { const record = this.application(applicationId); return { ...publicRecord(record), auditTimeline: this.store.applicationTimeline(applicationId) }; }

  status(applicationId: string) { const record = this.application(applicationId); return { applicationId: record.id, state: record.state, lastSuccessfulStep: record.lastSuccessfulStep, errors: record.errors, timestamps: { createdAt: record.createdAt, updatedAt: record.updatedAt, submittedAt: record.submittedAt }, correlationId: record.correlationId, submissionResult: record.submissionResult }; }

  createApprovalToken(applicationId: string, ttlSeconds = 120) {
    this.safety.assertRunning(); const record = this.application(applicationId); if (record.state !== 'READY_TO_SUBMIT') throw new WuzzufToolError('WUZZUF_NOT_READY_TO_SUBMIT', 'Application must be filled and valid before approval', { status: 409 }); if (record.dryRun) throw new WuzzufToolError('WUZZUF_DRY_RUN_BLOCKED', 'Disable dry-run and refill before creating approval', { status: 409 }); if (record.skippedFields.length || record.validationErrors.length) throw new WuzzufToolError('WUZZUF_REVIEW_INCOMPLETE', 'Resolve skipped fields and validation errors before approval', { status: 409 }); const token = randomBytes(24).toString('base64url'); const now = new Date(); const expiresAt = new Date(now.getTime() + Math.max(30, Math.min(ttlSeconds, 300)) * 1000).toISOString(); this.store.saveApprovalToken({ id: randomUUID(), applicationId, tokenHash: hash(token), expiresAt, createdAt: now.toISOString() }); this.answers.audit(record.correlationId, 'wuzzuf.approval_token_created', { expiresAt }, applicationId); return { applicationId, approvalToken: token, expiresAt };
  }

  async submit(input: { applicationId: string; approvalToken: string }) {
    this.safety.assertRunning(); const record = this.application(input.applicationId); if (record.dryRun) throw new WuzzufToolError('WUZZUF_DRY_RUN_BLOCKED', 'Dry-run applications can never submit', { status: 409 }); if (record.state === 'SUBMITTED' || record.submissionResult?.submitted) throw new WuzzufToolError('WUZZUF_DUPLICATE_SUBMISSION', 'Application has already been submitted', { status: 409 }); if (record.state !== 'READY_TO_SUBMIT') throw new WuzzufToolError('WUZZUF_NOT_READY_TO_SUBMIT', `Application is ${record.state}`, { status: 409 }); const lock = `application:submit:${record.id}`; if (!this.store.acquireLock(lock)) throw new WuzzufToolError('WUZZUF_APPLICATION_LOCKED', 'Application submission is already active', { status: 409 });
    try {
      const tokenState = this.store.consumeApprovalToken(record.id, hash(input.approvalToken), new Date().toISOString()); if (tokenState !== 'valid') throw new WuzzufToolError(`WUZZUF_APPROVAL_TOKEN_${tokenState.toUpperCase()}`, `Approval token is ${tokenState}`, { status: 403 }); const validation = await this.adapter.validate(this.browserSession(record)); if (!validation.valid) throw new WuzzufToolError('WUZZUF_VALIDATION_FAILED', 'Application became invalid before submission', { status: 409, diagnostics: { errors: validation.errors } }); if (!this.store.reserveSubmission(record.id, `wuzzuf:${record.job.sourceId}`)) throw new WuzzufToolError('WUZZUF_DUPLICATE_SUBMISSION', 'Submission has already been reserved', { status: 409 }); advance(record, ['SUBMITTING']); this.save(record); this.answers.audit(record.correlationId, 'wuzzuf.submission_started', { jobId: record.jobId }, record.id); const result = await this.adapter.submit(this.browserSession(record), { correlationId: record.correlationId, dryRun: false, signal: this.signal(record.id) }); advance(record, ['SUBMITTED']); record.submittedAt = new Date().toISOString(); record.submissionResult = { ...result, at: record.submittedAt }; record.submissionAllowed = false; this.save(record); this.answers.audit(record.correlationId, 'wuzzuf.submission_completed', { submitted: result.submitted, confirmation: result.confirmation }, record.id); return { applicationId: record.id, correlationId: record.correlationId, ...result, submittedAt: record.submittedAt };
    } catch (error) { this.answers.audit(record.correlationId, 'wuzzuf.submission_rejected', { code: error instanceof WuzzufToolError ? error.code : 'WUZZUF_SUBMISSION_FAILED' }, record.id); throw error; } finally { this.store.releaseLock(lock); }
  }

  async cancel(applicationId: string) { const record = this.application(applicationId); if (terminal(record.state)) return this.status(applicationId); this.controllers.get(applicationId)?.abort(new Error('Application cancelled')); if (record.adapterSessionId) await this.adapter.cancel(record.adapterSessionId); advance(record, ['CANCELLED']); record.submissionAllowed = false; this.save(record); this.answers.audit(record.correlationId, 'wuzzuf.application_cancelled', {}, record.id); return this.status(record.id); }
  async authStatus() { const correlationId = randomUUID(); const status = await this.adapter.authenticationStatus(this.safety.signal); return { correlationId, ...status }; }
  async openLogin() { const correlationId = randomUUID(); const result = await this.adapter.openLogin(); this.answers.audit(correlationId, 'wuzzuf.login_browser_opened', {}); return { correlationId, ...result }; }
  async close() { for (const controller of this.controllers.values()) controller.abort(); this.controllers.clear(); await this.adapter.close(); }

  private get baseUrl() { return process.env.WUZZUF_BASE_URL ?? 'https://wuzzuf.net'; }
  private async resolveJob(input: { jobId?: string; url?: string }): Promise<Job> { if (input.jobId) { const job = this.store.getJob(input.jobId); if (!job) throw new WuzzufToolError('WUZZUF_JOB_NOT_FOUND', 'Job was not found', { status: 404 }); return job; } if (!input.url) throw new WuzzufToolError('WUZZUF_JOB_REFERENCE_REQUIRED', 'Provide jobId or url'); const normalized = normalizeWuzzufUrl(input.url, this.baseUrl); const stored = this.store.getJobByUrl(normalized); return stored ?? this.store.upsertJob(await this.adapter.readJob(new URL(normalized))); }
  private profile(profileId?: string): CandidateProfile { const id = profileId ?? this.answers.settings.activeProfileId; const profile = id ? this.store.getProfile(id) : this.store.listProfiles()[0]; if (!profile) throw new WuzzufToolError('WUZZUF_PROFILE_REQUIRED', 'Import a candidate profile first', { status: 409 }); return profile; }
  private application(id: string): PreparedApplicationRecord { const record = this.store.getPreparedApplication(id); if (!record?.job) throw new WuzzufToolError('WUZZUF_APPLICATION_NOT_FOUND', 'Application was not found', { status: 404 }); return record; }
  private browserSession(record: PreparedApplicationRecord) { if (!record.adapterSessionId) throw new WuzzufToolError('WUZZUF_APPLICATION_SESSION_NOT_FOUND', 'Application browser session is no longer active; prepare again', { status: 409 }); return { id: record.adapterSessionId, url: record.job.url }; }
  private signal(id: string) { const controller = this.controllers.get(id); if (!controller) throw new WuzzufToolError('WUZZUF_APPLICATION_SESSION_NOT_FOUND', 'Application browser session is no longer active; prepare again', { status: 409 }); return AbortSignal.any([controller.signal, this.safety.signal]); }
  private save(record: PreparedApplicationRecord) { record.updatedAt = new Date().toISOString(); this.store.savePreparedApplication(record); }
}

function advance(record: PreparedApplicationRecord, states: PreparedApplicationRecord['state'][]): void { for (const state of states) { assertTransition(record.state, state); record.state = state; record.lastSuccessfulStep = state.toLowerCase(); } record.updatedAt = new Date().toISOString(); }
function terminal(state: PreparedApplicationRecord['state']): boolean { return ['SUBMITTED', 'CANCELLED', 'REJECTED_BY_USER', 'DUPLICATE', 'SKIPPED', 'FAILED_PERMANENT'].includes(state); }
function hash(value: string): string { return createHash('sha256').update(value).digest('hex'); }
function validateSearch(input: WuzzufSearchInput): void { if (!input.queries?.length || input.queries.length > 10 || !input.locations?.length || input.locations.length > 10) throw new WuzzufToolError('WUZZUF_INVALID_SEARCH', 'queries and locations must contain 1–10 values'); if (input.limit !== undefined && (!Number.isInteger(input.limit) || input.limit < 1 || input.limit > 100)) throw new WuzzufToolError('WUZZUF_INVALID_SEARCH', 'limit must be between 1 and 100'); }
function redactedSearch(input: WuzzufSearchInput) { return { queryCount: input.queries.length, locationCount: input.locations.length, remote: input.remote, experienceLevel: input.experienceLevel, employmentTypes: input.employmentTypes, limit: input.limit }; }
function scoringCampaign(profile: CandidateProfile, job: Job): JobCampaign { const now = new Date().toISOString(); return { id: `wuzzuf-score-${job.id}`, name: 'Wuzzuf score', state: 'enabled', searchQueries: [job.title], locations: [job.location], workplace: job.remote ? ['remote'] : ['onsite'], includedKeywords: [], excludedKeywords: [], seniority: job.seniority ? [job.seniority] : [], minimumMatchScore: 0, allowedSites: ['wuzzuf'], maxApplicationsPerRun: 1, maxApplicationsPerDay: 1, executionMode: 'research_only', profileId: profile.id, cvStrategy: 'selected', providerId: 'local', model: 'deterministic', dryRun: true, createdAt: now, updatedAt: now }; }
function fuzzySkill(a: string, b: string): boolean { const clean = (value: string) => value.toLowerCase().replace(/[^a-z0-9+#.]+/g, ' ').trim(); return clean(a).includes(clean(b)) || clean(b).includes(clean(a)); }
function publicRecord(record: PreparedApplicationRecord) { const { adapterSessionId: _adapterSessionId, ...safe } = record; return safe; }
